### ISSUE TITLE
Remove Visual Studio project files

### ISSUE THREAD

**Issue by erikd** [xiph/flac#100]
Once the CMake build system has been merged (#97) it should be possible to remove the VS project files. Posting this idea here so that people can comment.

The VS project files will not be done until *after* the next release, which will contain both the CMake build system *and* the existing VS project files.

**Comment by neheb** [comment]
I have no comment on Visual Studio.

CMake support would be excellent as it would allow to get rid of some hacks that we carry in OpenWrt.

**Comment by MarcusJohnson91** [comment]
@neheb Just curious, why does OpenWRT need Flac?

**Comment by neheb** [comment]
Library

**Comment by lvqcl** [comment]
1) I don't know how to use CMake. A small section in the README file (for newbies) would be nice.

2) What versions of Visual Studio are supported by this build system?

**Comment by MarcusJohnson91** [comment]
@neheb  uh?

OpenWRT is router firmware... why does it need the FLAC library? FLAC is for lossless audio de/compression...

**Comment by neheb** [comment]
It has a minidlna package for example

**Comment by neheb** [comment]
@lvqcl quick search indicates VS9 2008 and above. Seems the previous visual studio versions were deprecated.

@MarcusJohnson91 

```
libs/flac/Makefile:define Package/libflac
libs/flac/Makefile:define Package/libflac/install
libs/flac/Makefile:$(eval $(call BuildPackage,libflac))
libs/libaudiofile/Makefile:  DEPENDS:=$(CXX_DEPENDS) +libflac
libs/libextractor/Makefile:     flac:+libflac \
multimedia/gst1-plugins-good/Makefile:$(eval $(call GstBuildPlugin,flac,FLAC codec,audio pbutils tag,,+libflac))
multimedia/minidlna/Makefile:   +libid3tag +libflac +libvorbis +libuuid \
sound/mpd/Makefile:         +AUDIO_SUPPORT:alsa-lib +boost +boost-container +libexpat +libflac
sound/sox/Makefile:             +libvorbis +alsa-lib +libflac
sound/squeezelite/Makefile:    DEPENDS+= +libflac +libvorbis +libmpg123 +libfaad2 \
```

**Comment by erikd** [comment]
@lvqcl A commit that adds documentation to the README about building with CMake had need added to #97.

**Comment by jherby2k** [comment]
As is, are the visual studio project files broken, or do they generate different output vs the cmake method?

**Comment by erikd** [comment]
THE VS files are old, difficult to maintain, don't play well with git, but most importantly, they can be created from scratch from the CMake build system.
