### ISSUE TITLE
[cmake] msbuild error MSB5004

### ISSUE THREAD

**Issue by Chocobo1** [xiph/flac#101]
I'm using MSVC 2019 and compiling the latest master branch.

I ran:
```
cmake -G "Visual Studio 16 2019" -A Win32 ..\
msbuild FLAC.sln /target:FLAC++
```
Then msbuild shows the error:
```
Solution file error MSB5004: The solution file has two projects named "flac"
```

I suspect it is because these 2 are the same name `flac`:
https://github.com/xiph/flac/blob/master/src/flac/CMakeLists.txt#L4
https://github.com/xiph/flac/blob/master/src/libFLAC/CMakeLists.txt#L59
AFAIK MSVC solution file name is case-insensitive so in this case so they will be treated in-differently and thus result in error.

I tried to rename one of them to some other name, then the problem is gone.

**Comment by erikd** [comment]
@krokoziabla @evpobr Maybe you can help with this?

**Comment by evpobr** [comment]
Confirm, build faild with `BUILD_SHARED_LIBS` set to `ON`, static build works. Name clash i guess. Working on fix.

**Comment by Chocobo1** [comment]
Thanks for the patch!
