### ISSUE TITLE
[cmake] linking with libFLAC++

### ISSUE THREAD

**Issue by Chocobo1** [xiph/flac#102]
MSVC 2019 and flac latest git master branch (95a94232a8c51f6433f33c2e8f1ae8a84813bb86) built with cmake.

I'm trying to work with libFLAC++ but I kept hitting these errors when linking:
```
2>flac.obj : error LNK2001: unresolved external symbol _FLAC__stream_decoder_new
2>flac.obj : error LNK2001: unresolved external symbol _FLAC__stream_decoder_process_until_end_of_metadata
2>flac.obj : error LNK2001: unresolved external symbol _FLAC__stream_decoder_set_md5_checking
2>flac.obj : error LNK2001: unresolved external symbol _FLAC__stream_decoder_process_single
2>flac.obj : error LNK2001: unresolved external symbol _FLAC__stream_decoder_init_ogg_stream
2>flac.obj : error LNK2001: unresolved external symbol _FLAC__stream_decoder_set_metadata_respond
2>flac.obj : error LNK2001: unresolved external symbol _FLAC__stream_decoder_init_stream
2>flac.obj : error LNK2001: unresolved external symbol _FLAC__stream_decoder_delete
```

After some digging I found that I should also link to libFLAC which then solves the linking error.
The extra linking to libFLAC isn't required when libFLAC++ is built with msvc solution files, so here is my question: Is the extra linking to libFLAC expected/a bug when using cmake?

**Comment by erikd** [comment]
@krokoziabla @evpobr Maybe you can help with this?

**Comment by evpobr** [comment]
Yes, you need to link FLAC and Ogg libraries. CMake works in this way, link only what you need.

Bundled Visual Studio projects have special option "Link library dependencies" set to create static libraries with all dependencies. This creates bloated static library and not actually recommended,

@krokoziabla , you can add something like this to mimic the same behaviour:

```cmake
target_link_libraries(FLAC++ PRIVATE "-WHOLEARCHIVE:FLAC++")
```

If you want to add it please also add option to disable it.

@Chocobo1 , use some package manager please. This is how it works with [Vcpkg](https://github.com/microsoft/vcpkg):

* Clone it.
* Run `bootstrap-vcpkg.bat` to build it
* Integrate with Visual Studio: `vcpkg integrate install`
* Install flac: `vcpkg install libflac:x86-windows-static libflac:x64-windows-static`
* Edit your project file if you link static libraries:
  ```
    <PropertyGroup Label="Globals">
    <!-- .... -->
    <VcpkgTriplet Condition="'$(Platform)'=='Win32'">x86-windows-static</VcpkgTriplet>
    <VcpkgTriplet Condition="'$(Platform)'=='x64'">x64-windows-static</VcpkgTriplet>
  </PropertyGroup>
  ```
That's all. You don't need to set include paths or add libraries, everything works.

**Comment by Chocobo1** [comment]
>Yes, you need to link FLAC and Ogg libraries. CMake works in this way, link only what you need.

I'm not sure we are talking the same thing. To be clear, I'm not talking about ogg, it is about whether I really need flac C library when I'm linking to flac C++ library, as said this wasn't the case when using msvc sln files.

>Bundled Visual Studio projects have special option "Link library dependencies" set to create static libraries with all dependencies. This creates bloated static library and not actually recommended,

I've not found anything related in msvc sln file, is the option true by default?
https://github.com/xiph/flac/blob/master/src/libFLAC/libFLAC_static.vcxproj
https://github.com/xiph/flac/blob/master/src/libFLAC%2B%2B/libFLAC%2B%2B_static.vcxproj

>If you want to add it please also add option to disable it.

Just curious, if flac C++ library always requires linking with flac C library then in what cases you need to disable it?

>@Chocobo1 , use some package manager please. This is how it works with Vcpkg:

Thank you, I'll try it some time.

**Comment by krokoziabla** [comment]
@Chocobo1 Unfortunately I don't have deep knowledge of MSVS but I can say forsure that if you build your client project with CMake and reference FLAC by using find_package() command you won't need explicitly link against the C library.

But in general, yeah, libFLAC++ is just a wrapper around libFLAC so anyhow it depends on it.

**Comment by Chocobo1** [comment]
OK, thanks for the help!
