### ISSUE TITLE
Provide compiled releases & include DLL files

### ISSUE THREAD

**Issue by Eagle3386** [xiph/flac#113]
The official [download page](https://xiph.org/flac/download.html) clearly states for the Windows package:
> **command-line tools only**, the file flac-X.Y.Z-win.zip contains both 32 and 64 bit **binaries**

I'd therefore like to request usage of GitHub's free (!) power to setup the complete build chain in order to release builds directly from/to here.
This way, developers like me don't need to setup a full C(++) environment just to build the FLAC lib they're then using in there (non-) C(++) IDE.

**Comment by Eagle3386** [comment]
@erikd Any news regarding an updated build chain providing release straight off of GitHub? It'd really help other developers..

**Comment by a-vrma** [comment]
> Any news regarding an updated build chain providing release straight off of GitHub? It'd really help other developers.

I'm looking into uploading artifacts from the current GitHub actions workflow and adding a Windows job. It's up to @erikd if he wants to host those on xiph.org. In the meantime you can get builds from <https://www.rarewares.org/lossless.php>

**Comment by Eagle3386** [comment]
@erikd / @a-vrma How are things going so far?
