### ISSUE TITLE
sys/param.h need not define MIN and MAX (e.g. mingw)

### ISSUE THREAD

**Issue by sezero** [xiph/flac#115]
sys/param.h from mingw doesn't define MIN and MAX macros.
As a result, if gcc is older than 4.3, this results in a
build failure.  I suggest something like the following:

```
diff --git a/src/libFLAC/include/private/macros.h b/src/libFLAC/include/private/macros.h
index 02eada4..3a8072e 100644
--- a/src/libFLAC/include/private/macros.h
+++ b/src/libFLAC/include/private/macros.h
@@ -51,8 +51,10 @@
 /* Whatever other unix that has sys/param.h */
 #elif defined(HAVE_SYS_PARAM_H)
 #include <sys/param.h>
+#if defined(MIN) && defined(MAX)
 #define flac_max(a,b) MAX(a,b)
 #define flac_min(a,b) MIN(a,b)
+#endif
 
 /* Windows VS has them in stdlib.h.. XXX:Untested */
 #elif defined(_MSC_VER)
```

**Comment by lvqcl** [comment]
GCC 4.3.0 release date is March 5, 2008. Why do you want to use such ancient compilers?

**Comment by sezero** [comment]
> GCC 4.3.0 release date is March 5, 2008. Why do you want to use such ancient compilers?

Because I can, and that toolchain supports many things, except for incorrect assumptions of course.

**Comment by erikd** [comment]
@sezero We support a large number of compilers and build systems. Doing so is a huge amount of work. That means that when you find things like this, its up to you to fix it and supply a patch. If the patch is reasonable it will be merged. However, it will remain untested (by us, the FLAC devs) which means it may regress. That means that you should periodically test that git HEAD builds, especially in the run up to a new release.

The alternative of course, is just to use a more recent compiler.

**Comment by sezero** [comment]
> [snip]  its up to you to fix it and supply a patch.

Which I did above.  Do you specifically prefer a pull request instead of a patch?

**Comment by erikd** [comment]
So it compiles with that patch? If so were do `MIN` and `MAX` come from?

Yes, I refer a PR because then it gets build in CI. However, the CMake build system is currently broken in CI, so let me fix that first.

**Comment by sezero** [comment]
> So it compiles with that patch?

Yes (why would I submit a non-working patch..)

> If so were do `MIN` and `MAX` come from?

From nowhere.  You have fallbacks in there when flac_min and flac_max
are left undefined, that's how it compiles successfully.

> Yes, I refer a PR because then it gets build in CI. However, the
> CMake build system is currently broken in CI, so let me fix that first.

OK, I'll wait for your notification.

**Comment by sezero** [comment]
Well, I went ahead and created https://github.com/xiph/flac/pull/117
Feel free to merge.
