### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [xiph/flac#125]
Greetings Flac developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

To help you getting started, we can attach our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by guidovranken** [comment]
I'm creating FLAC fuzzers, see https://github.com/google/oss-fuzz/pull/2695
Any maintainers who are willing to receive bug reports from OSS-Fuzz?
Please give me your e-mail address (linked to a Google account).

**Comment by Google-Autofuzz** [comment]
Great! :)

**Comment by rillian** [comment]
Thanks!

**Comment by erikd** [comment]
@guidovranken I am more than happy to receive oss-fuzz reports, but does it have to be to a Gmail/Google account?

**Comment by guidovranken** [comment]
Without a Google account, you will receive e-mail notifications with basic information about the bug, but you won't be able to log in to oss-fuzz.com and see things like stack traces and download testcases.

**Comment by erikd** [comment]
I do have a Google account.

**Comment by guidovranken** [comment]
Can you give me the e-mail address?

**Comment by erikd** [comment]
erik.de.castro.lopo@gmail.com

**Comment by lvqcl** [comment]
Are signed overflows prohibited?

**Comment by guidovranken** [comment]
You mean when fuzzing at OSS-Fuzz? I've configured the fuzzer to run with Undefined Behavior Sanitizer, so yes, signed overflow will trigger a crash. If this is a problem, I can disable UBSAN, but it's always prudent to fix signed overflows because they can in theory lead to worse problems than simply wrong computations.

**Comment by guidovranken** [comment]
@erikd The first bug has been found: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16457
Are you able to log in and see it?
The fuzzer source code is here: https://github.com/guidovranken/flac-fuzzers/blob/master/fuzzer_decoder.cpp
Can you understand it? Do you need any help with analyzing the bug?

**Comment by guidovranken** [comment]
@erikd 

I am working on a fuzzer for the encoder.

Is it normal that this consumes a large amount of memory (>2GB)?

```cpp
#include "FLAC++/encoder.h"
namespace FLAC {
	namespace Encoder {
        class FuzzerStream : public Stream {
            public:
                FuzzerStream(void) :
                    Stream() { }

                ::FLAC__StreamEncoderWriteStatus write_callback(const FLAC__byte buffer[], size_t bytes, uint32_t samples, uint32_t current_frame) override {
                    return FLAC__STREAM_ENCODER_WRITE_STATUS_OK;
                }
        };
    }
}

int main(void)
{
    FLAC::Encoder::FuzzerStream encoder;

    if ( encoder.init() != FLAC__STREAM_ENCODER_INIT_STATUS_OK ) { return 0; }
    encoder.set_channels(2);
    encoder.set_bits_per_sample(16);

    const FLAC__int32 samples[] = {-1717986919, -1718017639, -1717986919, -1717986919, -1717986919, -1717986919, -1717986919, -1, -1, -1, -1720280679, 1431655765, -1717986919, -16755303, -1717986919, -1717986919, -1717986919, -6710887, -1, -1, -1, -1717986919, -1717986919, -1717986919, -1717986919, -1717986919, -1717986919};
    const uint32_t numSamples = sizeof(samples) / sizeof(samples[0]) / 2;

    encoder.process_interleaved(samples, numSamples);
    encoder.finish();

    return 0;
}
```

**Comment by erikd** [comment]
Yeah, I can see that. Don't have time to look today (its Friday here) but will get to it tomorrow,

**Comment by guidovranken** [comment]
Ok, that might be a bug then.

If I limit the input sample values to the encoder to the range ```<-10485760,10485760>```, the memory problem is gone.

**Comment by erikd** [comment]
You currently seem to be fuzzing the exncoder. I would have thought fuzzing the decoder would have been higher priority.

**Comment by guidovranken** [comment]
No the decoder fuzzer is already running (the bug reports you got so far concern the decoder).
The encoder fuzzer will be added shortly, and will run simultaneously.

**Comment by Google-Autofuzz** [comment]
I see that it has been [merged](https://github.com/google/oss-fuzz/pull/2707) to OSS-Fuzz. Thank you for integrating it to OSS-Fuzz.
