### ISSUE TITLE
FLAC__bool is defined as int

### ISSUE THREAD

**Issue by neheb** [xiph/flac#129]
Any reason why this is?

I'm running the codebase through static analysers and they're telling me there's implicit conversion between bool and int going on.

**Comment by erikd** [comment]
The vast majority of this code base was written in the late 1990s and early 2000s. From memory `bool` was added in to C99 and at the time FLAC was written many compilers did not support it.

If `FLAC__bool`'s definition cane be changed to `bool` or better yet replace all FLAC internal use of `FLAC_bool ` with `bool` then I would be in favor of that.

**Comment by neheb** [comment]
I wrote a small test using bool. It compiles even with -std=c89.

Probably some libraries at the time lacked stdbool.h, which seems to work even in c89 mode.

**Comment by neheb** [comment]
Seems this is actually an MSVC problem. bool was introduced in 2015...

**Comment by neheb** [comment]
Since this is going nowhere...
