### ISSUE TITLE
should use libogg.lib instead of libogg_static.lib

### ISSUE THREAD

**Issue by fuchanghao** [xiph/flac#137]
In ogg 1.3.4 it's output-lib changed to libogg.lib not libogg_static.lib.

flac should change the lib name too.

**Comment by erikd** [comment]
I don't use the CMake build system.  Please feel free to provide a PR to fix this.

**Comment by jbaker6953** [comment]
The problem with that is that flac.exe 1.3.4 is then built dependent on ogg.dll rather than statically. I came here to report this very issue.

**Comment by jbaker6953** [comment]
As a side note: the libogg source builds libogg.dll, but flac project looks for ogg.dll.

**Comment by fuchanghao** [comment]
> 
> 
> As a side note: the libogg source builds libogg.dll, but flac project looks for ogg.dll.

No, it needs libogg_static.lib in the objs\release\lib path.

But from ogg 1.3.4 the name of library called libogg.lib not libogg_static.lib.

**Comment by jbaker6953** [comment]
What I mean is that if you build flac with libogg.lib flac.exe won't run. It throws an error about missing 'ogg.dll'.

**Comment by zvezdochiot** [comment]
@jbaker6953 say> What I mean is that if you build flac with libogg.lib flac.exe won't run. It throws an error about missing 'ogg.dll'.

What is this static? This is a dynamic link, only a curve.

**Comment by NotTsunami** [comment]
Pinging @krokoziabla as he's the one who most recently worked on the CMake files

**Comment by ktmf01** [comment]
CMake had quite an overhaul with e0b62a6, especially with respect to ogg. I haven't had problems with this in a while, neither has CI. Can I close this issue?
