### ISSUE TITLE
FLAC 1.3.3 package seems to don't include CMakeLists.txt

### ISSUE THREAD

**Issue by melpon** [xiph/flac#140]
GitHub source [tag 1.3.3](https://github.com/xiph/flac/tree/f764434a39e8a8715d5871bb263189e5a7298280) includes CMakeLists.txt, but the released [tarball](https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.3.tar.xz) does not.

**Comment by NotTsunami** [comment]
1.3.3 release was a mess, just wait for 1.3.4.

**Comment by erikd** [comment]
Awww, it wasn't that bad. The only problems were with the CMale build system and 1.3.3 we the first release where that even worked (even if it was only in Git).

**Comment by NotTsunami** [comment]
> Awww, it wasn't that bad. The only problems were with the CMale build system and 1.3.3 was the first release where that even worked (even if it was only in Git).
No hard feelings lol, just waiting for 1.3.4 :smile:

**Comment by erikd** [comment]
Fixed in https://github.com/xiph/flac/pull/143.
