### ISSUE TITLE
Need support for the 24 bit flac file decode to wav file 

### ISSUE THREAD

**Issue by vishalvaza** [xiph/flac#144]
Hi there,
I am trying to execute code given in the [https://github.com/xiph/flac/blob/master/examples/cpp/decode/file/main.cpp](url) file.
but in comment section it is written for the 16 bit support only.
what changes will required to support that sample code to work for the 24 bit FLAC file.

**Comment by erikd** [comment]
That is an example program. The actual FLAC executable decodes 24 bit FLAC to 24 bit WAV without a problem.

**Comment by vishalvaza** [comment]
Ya i check the executable file but I am using libFLAC as library and use sample encode and decode example file so can suggest me where code need to be change which can support 24bit or 32bit stereo files.

**Comment by erikd** [comment]
The libFLAC API is actually rather poor. It f you want an easy API that allows the reading and writing of 24 bit FLAC files I would suggest libsndfile.

**Comment by vishalvaza** [comment]
I want to convert FLAC file to WAV file format of any data (like 16 bit, 24 bit or 32 bit).

**Comment by erikd** [comment]
That can be done with libsndfile. In fact there is a command line program (`sndfile-convert`) in the libsndfile repo that converts FLAC to WAV and can convert bit widths on the way.

**Comment by vishalvaza** [comment]
Thanks for the help.
