### ISSUE TITLE
FLAC failed to build due to error C2375 on windows with MSVC

### ISSUE THREAD

**Issue by spacelg** [xiph/flac#152]
Environment:
Windows Server 2016 + VS2017 + flac master branch latest source code.

Issue description:
I tried to build flac using VS2017 on Windows Server 2016. We found that flac failed to build due to error C2375: 'flac_internal_set_utf8_filenames': redefinition; different linkage.  It can be first reproduced on b917d45 revision. Could you please help take a look at this? Thanks in advance!

Repro steps:
1. git clone https://github.com/xiph/flac D:\FLAC\src
2. Open a VS 2017 x86 command prompt as admin and browse to D:\FLAC\src
3. devenv /upgrade FLAC.sln
4. msbuild FLAC.sln /t:Rebuild /p:Configuration=Release;Platform=Win32 /p:WindowsTargetPlatformVersion=10.0.17134.0

[log_x86_build.log](https://github.com/xiph/flac/files/3737259/log_x86_build.log)

Actual result:
D:\FLAC\src\src\libFLAC\windows_unicode_filenames.c(67): error C2375: 'flac_internal_set_utf8_filenames': redefinition; different linkage [D:\FLAC\src\src\libFLAC\libFLAC_dynamic.vcxproj]
D:\FLAC\src\src\libFLAC\windows_unicode_filenames.c(72): error C2375: 'flac_internal_get_utf8_filenames': redefinition; different linkage [D:\FLAC\src\src\libFLAC\libFLAC_dynamic.vcxproj]
D:\FLAC\src\src\libFLAC\windows_unicode_filenames.c(79): error C2375: 'flac_internal_fopen_utf8': redefinition; different linkage [D:\FLAC\src\src\libFLAC\libFLAC_dynamic.vcxproj]
D:\FLAC\src\src\libFLAC\windows_unicode_filenames.c(101): error C2375: 'flac_internal_stat64_utf8': redefinition; different linkage [D:\FLAC\src\src\libFLAC\libFLAC_dynamic.vcxproj]
D:\FLAC\src\src\libFLAC\windows_unicode_filenames.c(117): error C2375: 'flac_internal_chmod_utf8': redefinition; different linkage [D:\FLAC\src\src\libFLAC\libFLAC_dynamic.vcxproj]
D:\FLAC\src\src\libFLAC\windows_unicode_filenames.c(133): error C2375: 'flac_internal_utime_utf8': redefinition; different linkage [D:\FLAC\src\src\libFLAC\libFLAC_dynamic.vcxproj]
D:\FLAC\src\src\libFLAC\windows_unicode_filenames.c(152): error C2375: 'flac_internal_unlink_utf8': redefinition; different linkage [D:\FLAC\src\src\libFLAC\libFLAC_dynamic.vcxproj]

**Comment by erikd** [comment]
@evpobr ?

**Comment by evpobr** [comment]
> Open a VS 2017 x86 command prompt as admin and browse to D:\FLAC\src

@spacelg , correct me if i wrong - we are talking about [FLAC.sln](https://github.com/xiph/flac/blob/35b369ebee98f0b8fff474e401dae05bf060311b/FLAC.sln) in root directory, not CMake generated one? I don't see `FLAC.sln` in `src/` directory.

**Comment by sezero** [comment]
Does the attached patch help?

[patch.txt](https://github.com/xiph/flac/files/3741629/patch.txt)

**Comment by sezero** [comment]
See https://github.com/xiph/flac/pull/153
