### ISSUE TITLE
Aarch64 support

### ISSUE THREAD

**Issue by coreyjjames** [xiph/flac#156]
Hello,

I am a computer programming student and for a class I am tasked with finding an open source project that I can optimize for aarch64. I found this library and noticed that you have optimized for x86_64 and PPC. 
Would you be open to me adding some optimizations for Aarch64?

**Comment by erikd** [comment]
If you can hook this up and get it working then I am fine with it.

The only foreseeable problem is that it may be difficult to get CI for Aarch64.

**Comment by coreyjjames** [comment]
Cool, I'll see what I can do.

**Comment by petterreinholdtsen** [comment]
[Corey James]
> I am a computer programming student and for a class I am tasked with
> finding an open source project that I can optimize for aarch64. I
> found this library and noticed that you have optimized for x86_64 and
> PPC.
> Would you be open to me adding some optimizations for Aarch64?

Sound fun and useful.  There is however the minior question about long
term maintenance.  Would you be willing to maintain these optimizations
after the class is over, ie update them if there are bugs found and
adjust them as the flac library changes internally?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by coreyjjames** [comment]
@petterreinholdtsen I won't be able to actively monitor the changes myself but if anyone finds a bug or something in the future you can contact me here on Github and I can take a look at it.

**Comment by coreyjjames** [comment]
@petterreinholdtsen I won't be able to actively monitor the changes myself but if anyone finds a bug or something in the future you can contact me here on Github and I can take a look at it.

**Comment by NotTsunami** [comment]
If you do contribute this changes, I also recommend submitting them to the Android flac repository too, as most modern devices are using a derivative of the ARMv8 architecture (with AArch64 being the 64-bit state). Their Gerrit server can be found [here](https://android-review.googlesource.com/).

**Comment by coreyjjames** [comment]
@NotTsunami Sure, I can look into doing that. I should have a PR for this repo this week or the next week. I got the optimization working with my test so far, yielding about a 50% increase in speed to encoding a file on aarch64. I need to do a bit more testing, and then I can put up my PR.

**Comment by klslz** [comment]
Hi.

Is this aarch64 project dead?

It hasn't been migrated into master as it seems. 
Neon support is only reported when configuring the topic/aarch64 branch.

If it is not dead.

I'd like to mention the NEON should then be treated like SSE.

SSE is  falsely reported as YES  On ARM btw.

SSE optimizations : ....................... yes

Shouldn't there also a "NEON optimizations: .... yes" field?

Than I'd suggest to also add a "disable/enable-neon" config option.


Considering the huge performance gains that have been suggested I'd love to see neon working
on aarch64.

Thx.

**Comment by coreyjjames** [comment]
@klslz 
Nope, It is not dead I am still working on it.

At the moment the optimizations are working. I am just looking into the Autotools configurations. For some reason, it is considerably slower than Cmake. From my test so far the Autotools tests seem to be running the optimization code, but I am not getting the speed increase like I get when I compile with Cmake.

Yes, I can look into removing the false reporting of SSE optimizations and adding a Neon optimization to the config summary and add a "disable/enable-neon" config option.

**Comment by NotTsunami** [comment]
Looking through the build logs it looks like both AVX and SSE were both somehow reported on OSX on CMake builds.

**Comment by NotTsunami** [comment]
Note: I just made the same comment in #183, but the CPU detection in CMake just recently changed so hopefully on a rebase that might be fixed.

**Comment by klslz** [comment]
Thx. Looking forward to it.

I did wonder if the permanent ASM = NO  on ARM also relates to these CPU optimization features or if it just an x86 feature!?!?

**Comment by klslz** [comment]
Hi.

I did some benchmark tests to verify the NEON impact.

I used 

* the standard Arch Linux binary, 
* the git topic/aarch64 binary 
* and the git master binary.

I've been running  and RPI4 with 1500MHz and performance governor.
gcc version 9.3.0 and kernel 5.4.49

I've been using "perf" 

Below the results.

```
##ALARM REPO

Performance counter stats for '/bin/flac --totally-silent --compression-level-5 -f -o /tmp/test.flac.1 /tmp/test.wav' (10 runs):

          4,685.93 msec task-clock                #    1.000 CPUs utilized            ( +-  0.03% )
                11      context-switches          #    0.002 K/sec                    ( +- 13.95% )
                 0      cpu-migrations            #    0.000 K/sec                  
               169      page-faults               #    0.036 K/sec                    ( +-  0.57% )
     7,028,770,689      cycles                    #    1.500 GHz                      ( +-  0.03% )
    15,053,486,788      instructions              #    2.14  insn per cycle           ( +-  0.01% )
   <not supported>      branches                                                    
        15,143,102      branch-misses                                                 ( +-  0.41% )

           4.68767 +- 0.00137 seconds time elapsed  ( +-  0.03% )
           
           
###aarch64/NEON
           
Performance counter stats for '/bin/flac --totally-silent --compression-level-5 -f -o /tmp/test.flac.1 /tmp/test.wav' (10 runs):

          2,944.89 msec task-clock                #    1.000 CPUs utilized            ( +-  0.10% )
                12      context-switches          #    0.004 K/sec                    ( +- 11.72% )
                 0      cpu-migrations            #    0.000 K/sec                  
               163      page-faults               #    0.055 K/sec                    ( +-  0.31% )
     4,417,222,370      cycles                    #    1.500 GHz                      ( +-  0.10% )
     7,868,773,092      instructions              #    1.78  insn per cycle           ( +-  0.00% )
   <not supported>      branches                                                    
        13,817,927      branch-misses                                                 ( +-  1.31% )

           2.94608 +- 0.00291 seconds time elapsed  ( +-  0.10% )


###GIT master

./perf stat -r 10 -B $BIN --totally-silent --compression-level-$COMPRESSIONLEVEL -f -o $OF.1 $IF

 Performance counter stats for '/bin/flac --totally-silent --compression-level-5 -f -o /tmp/test.flac.1 /tmp/test.wav' (10 runs):

          4,062.89 msec task-clock                #    1.000 CPUs utilized            ( +-  0.06% )
                 5      context-switches          #    0.001 K/sec                    ( +-  5.66% )
                 0      cpu-migrations            #    0.000 K/sec                  
               163      page-faults               #    0.040 K/sec                    ( +-  0.33% )
     6,094,242,420      cycles                    #    1.500 GHz                      ( +-  0.06% )
    12,076,494,304      instructions              #    1.98  insn per cycle           ( +-  0.00% )
   <not supported>      branches                                                    
        14,163,496      branch-misses                                                 ( +-  0.57% )

           4.06377 +- 0.00233 seconds time elapsed  ( +-  0.06% )


```
As you can see the locally compiled git master branch binary is already faster then the distro default binary.
That's gonna be the reference.

Ten cycles have been run.

The git Neon enabled binary causes a 27,5% performance improvement over the master branch if I'm not mistaken.

It's not 100%. But it looks very nice.

**Comment by tmkk** [comment]
I've applied more optimizations to [lpc_intrin_neon.c](https://github.com/tmkk/flac/blob/aarch64_neon/src/libFLAC/lpc_intrin_neon.c), which includes:
* more optimized versions of `FLAC__lpc_compute_autocorrelation_intrin_neon_lag_*` functions
* new `FLAC__lpc_compute_residual_from_qlp_coefficients_*` functions

Higher compression level should make larger improvement. I observed about 3.8x improvement in compression level 8 over the plain C version on Apple A8 processor.
A complete repository (for building/testing) is [here](https://github.com/tmkk/flac/tree/aarch64_neon), which is based on PR #183.

**Comment by klslz** [comment]
I ran above benchmark once more, now adding the https://github.com/tmkk/flac.git aarch64_neon branch to the test cases.

Platform: 
* RPI4 @1500MHz
* RaspberryPI OS64 (aarch64)
* kernel 5.10.4
* gcc 8.3.0

The result on the new platform confirms earlier benchmarks still showing a ~27% better performance of the aarch64 neon binary.

However. The new testcase that's supposed to show even further ARM Neon optimizations doesn't show any improvement. I even found the binary performing slightly (~1%) worse then the topic/aarch64 branch sources.

Anyhow.

Further learnings.

The RPiOS platform binary (1.3.2.)  performs ~20% worse then the flac repo master binary.
Let's consider the RPiOs binary the 100% reference. 
From that perspective the Neon enabled binary shows an ~40% improvement. 
That's what I'd consider a substantial and worthwhile step up. I hope that one day somebody merges
the topic/aarch64 tree into the master.

Enjoy.

**Comment by tmkk** [comment]
@klslz `lpc_intrin_neon.c` in `topic/aarch64` branch has bugs which wrongly speedup the encoding speed. Looking into a generated file, it is larger than a normally encoded file. It is fixed in the latest PR based on https://github.com/coreyjjames/flac/tree/addAarch64Support.

**Comment by tmkk** [comment]
Some measurement numbers when encoding 7m44s 44.1kHz/16bit wav file 5 times (2320 sec total):

```
Cortex-A76 2.84GHz on Android 10/termux, clang 11.0.0
    [compression level 5]
        master      6.3s
       PR #184      5.2s (21% improvement)
      my impl.      4.5s (40% improvement)
    [compression level 8]
        master     28.6s
       PR #184     17.3s (65% improvement)
      my impl.     12.5s (129% improvement)

A8 1.1GHz on iOS 8.4, clang 12.0.0
    [compression level 5]
        master     31.5s
       PR #184     26.3s (19% improvement)
      my impl.     21.3s (48% improvement)
    [compression level 8]
        master    221.7s
       PR #184     91.0s (144% improvement)
      my impl.     50.0s (343% improvement)
```

**Comment by klslz** [comment]
Here's a benchmark summary of my recent testcases.
compression level level 5

```
_______________________________________________________________


	date:		Jan-05-2021 18:08
	os:		Debian GNU/Linux 10 (buster)
	arch:		aarch64
	kernel:		5.10.4
	gcc:		8.3.0
	RPI:		Pi 4 Model B Rev 1.1
	CPU freq:	1500 (MHz)
	CPU temp:	48.2'C

_______________________________________________________________

	repo:		https://github.com/xiph/flac.git
	version:	flac 1.3.3-bfd4f13
	TC1:		3.57
_______________________________________________________________

	repo:		host platform
	version:	flac 1.3.2
	TC2:		4.18  ( 17.09% )
_______________________________________________________________

	repo:		https://github.com/xiph/flac.git
	branch:		topic/aarch64
	version:	flac 1.3.3-9242aab
	TC3:		2.71  ( -24.09% )
_______________________________________________________________

	repo:		https://github.com/tmkk/flac.git
	branch:		aarch64_neon
	version:	flac 1.3.3-77e4eb9
	TC4:		2.74  ( -23.25% )
_______________________________________________________________

	repo:		https://github.com/coreyjjames/flac.git
	branch:		addAarch64Support
	version:	flac 1.3.3-80ae044
	TC5:		2.78  ( -22.13% )

_______________________________________________________________
```

**Comment by klslz** [comment]
Hi. 

Sorry for reviving this old discussion.

@tmkk and @coreyjjames

I tried today both your latest aarch64-neon branches against the latest master sources on a RPI4.

gcc is 10.2.1 (on RPiOS Bullseye) 

I could not detect any difference between any of the builds.

Is there an explanation from your side?

THX

**Comment by ktmf01** [comment]
Hi @klslz,

Please look at #245 for updates to this issue. As far as I know, RPiOS is 32-bit and therefore does not benefit from the Aarch64 improvements.

**Comment by klslz** [comment]
@ktmf01 

Great to see that you take care of the subject. Looks promising. Hopefully you'll get your changes merged.

I am wondering if there'll be also a config option "NEON yes/no" similar to sse  and some printouts during config/compilation about NEON stats. If I recall it correctly so far there weren't any.

Anyhow. 

RPiOS is also available in 64bit. And there are several more RPi OSes which run AARCH64 mainly for the RPI4. 
Especially on low muscle systems like that, performance gains are highly appreciated.

THX

**Comment by ktmf01** [comment]
@klslz It is possible to use the more general --disable-asm-optimizations in configure and -DFLAC__NO_ASM=1 in cmake. Configure does output whether compilation of neon optimizations was detected to be possible at the end of the output. The other output to look for is:

```
checking arm_neon.h usability... yes
checking arm_neon.h presence... yes
checking for arm_neon.h... yes
[...]
checking whether arm_neon.h has A64 functions... yes
```

When using cmake, look for the following lines

```
-- Looking for arm_neon.h
-- Looking for arm_neon.h - found
[...]
-- Check CPU architecture is aarch64
-- Check CPU architecture is aarch64 - yes
-- Check whether A64 NEON can be used
-- Check whether A64 NEON can be used - yes
```

**Comment by klslz** [comment]
Based on your autoc-double branch on my PI4 RPIOS64 Bullseye with gcc 10.2.1 . 
Just a default config.

Looks great.

```
Configuration summary :

    FLAC version : ............................ 1.3.3

    Host CPU : ................................ aarch64
    Host Vendor : ............................. unknown
    Host OS : ................................. linux-gnu

    Compiler is GCC : ......................... yes
    GCC version : ............................. 10
    Compiler is Clang : ....................... no
    SSE optimizations : ....................... no
    Neon optimizations : ...................... yes
    Asm optimizations : ....................... yes
    Ogg/FLAC support : ........................ yes
    Stack protector  : ........................ yes
    Fuzzing support (Clang only) : ............ no
```

**Comment by klslz** [comment]
Remark: 
--disable-asm-optimizations won't disable neon support.
 A  "--disable-neon" like --disable-sse asf option  is missing.

**Comment by ktmf01** [comment]
Please leave remarks and problems considering push request #245 at the comment thread for that push request, not here. Also, please be more specific with what the problem is. Currently I cannot reproduce this problem.

**Comment by klslz** [comment]
Of course. Sorry. I'll do later on. I'll also attach some logs.

**Comment by ktmf01** [comment]
ARM64 support is merged, closing this
