### ISSUE TITLE
Question about the pkg-config files install paths when using CMake

### ISSUE THREAD

**Issue by DeadSix27** [xiph/flac#160]
In the cmake config for libflac++ and libflac the .pc files get installed to:
`${CMAKE_INSTALL_DATAROOTDIR}/pkgconfig`
`${CMAKE_INSTALL_DATADIR}/pkgconfig`

Shouldn't it be `${CMAKE_INSTALL_LIBDIR}/pkgconfig`
Example from your other project `opus`:
```
 install(FILES ${CMAKE_CURRENT_BINARY_DIR}/opus.pc
          DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig) 
```
Seems datarootdir and datadir resolve to `share/` instead of the needed `lib/` where everyone else stores their pkgconfig files, including opus..

Sources:
https://github.com/xiph/flac/blob/master/src/libFLAC%2B%2B/CMakeLists.txt#L53
https://github.com/xiph/flac/blob/master/src/libFLAC/CMakeLists.txt#L129

Patch:
https://github.com/DeadSix27/flac/commit/d8f189ac0e5d0f051e5d844bc21c253ce505e18e

If this is indeed an issue I can provide a PR if wanted.

**Comment by neheb** [comment]
The pkgconfig files must be formatted as follows:

```
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=@CMAKE_INSTALL_PREFIX@
libdir=${exec_prefix}/lib
included it=${prefix}/include
```

Otherwise it will not work in OpenWrt.

**Comment by DeadSix27** [comment]
Shouldn't OpenWrt patch that for themselves down stream?

**Comment by neheb** [comment]
No. That format I showed is consistent between multiple projects.

**Comment by DeadSix27** [comment]
Well, still, the format was never the problem, the path is.

**Comment by erikd** [comment]
@DeadSix27 Is the install path when using the CMake build system the same as when using the Autotool build system?

**Comment by DeadSix27** [comment]
Nope, autotools installs it into the correct path:
`/usr/bin/install -c -m 644 flac++.pc '****/lib/pkgconfig'

CMake into the wrong, as seen in the original post.

**Comment by erikd** [comment]
I maintain the Autotool build system. Someone familiar with the CMake build system should sort this out. 

People who have worked on the CMake stuff before include @evpobr @sezero @krokoziabla .

**Comment by DeadSix27** [comment]
Done: https://github.com/xiph/flac/pull/165
