### ISSUE TITLE
Add Oss-Fuzz targets to CMake build

### ISSUE THREAD

**Issue by erikd** [xiph/flac#164]
Needs to match the Autotool build as close as is reasonable:

* Disabled by default
* Enabled when using the Clang compiler
* Disabled with GCC (even when enabled) because GCC does not have `--lFuzzer`.

**Comment by ktmf01** [comment]
As the build script in oss-fuzz has become more and more specific, and the code relies more and more on the `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` define (which I rather not have anyone set accidentally or unknowingly with `--enable-oss-fuzzers`), there is very little use building the fuzzers outside a specific fuzzing-related environment like the oss-fuzz Docker environment.

As the oss-fuzz script really need only one build system to work with, I don't think duplicating accomplishes anything but guaranteed bit-rot. Therefore I'm closing this issue.
