### ISSUE TITLE
FLAC__STREAM_ENCODER_INIT_STATUS_ENCODER_ERROR

### ISSUE THREAD

**Issue by moisespr123** [xiph/flac#172]
Latest code fails at initialization:

```
ERROR initializing encoder
init_status = FLAC__STREAM_ENCODER_INIT_STATUS_ENCODER_ERROR
state = FLAC__STREAM_ENCODER_FRAMING_ERROR
```

**Comment by moisespr123** [comment]
Affects files of 16MB or larger.

**Comment by erikd** [comment]
This is encoding right from say a WAV file larger than 16MB?

**Comment by moisespr123** [comment]
Yes, any file that's equal or over 16MB.

**Comment by erikd** [comment]
I have reverted that commit as it looks like this is non-trivial to fix.
