### ISSUE TITLE
Specific encoding options should always have precedence over presets

### ISSUE THREAD

**Issue by vlakoff** [xiph/flac#20]
Currently, extending encode presets depends on the order of the arguments.

This command applies the "-epr8" options:

    flac --best -epr8 myfile.wav

While this command doesn't apply them:

    flac -epr8 --best myfile.wav

I think the user expects the options he specifies to take precedence over the preset, no matter in what order they are specified.

See the options parsing [in encode.c](https://github.com/xiph/flac/blob/master/src/flac/encode.c#L2095)

**Comment by erikd** [comment]
If anything, I think this is more of a documentation bug. The `--best` option chooses a set of "best" defaults which can then be modified, by more specific options like `--epr8`.

**Comment by erikd** [comment]
It might be worth printing a warning if general encoding options are included after specific ones like in your second example.

**Comment by ktmf01** [comment]
There's a fix for this in #381
