### ISSUE TITLE
CMake: Possible accidental revert of pkg-config install path fix

### ISSUE THREAD

**Issue by DeadSix27** [xiph/flac#200]
A while ago I submitted this PR: https://github.com/xiph/flac/pull/165
Which got accepted and merged, however with this commit

https://github.com/xiph/flac/commit/acadefddac6b6a3a67d7628432c4b1380fbc2044#diff-dbdb1e093de269c9266f1344e48033cfR124

You seem to have reverted said path fix back to the original wrong path**s**.

Was this intentional? It breaks software depending on the pkg-config files since it installs to share/ rather than lib/pkgconfig which is the more common and most used path. (afaik)

**Comment by erikd** [comment]
@evpobr ? If this is indeed unintended, please raise a new PR with the correction and as @DeadSix27 to review the PR.

**Comment by evpobr** [comment]
@DeadSix27 , sorry for that.

**Comment by evpobr** [comment]
Hm, test build broken, but it is not commit issue. Probably Ubuntu servers are down.
