### ISSUE TITLE
Build fails - Incorrect gcc pie flag

### ISSUE THREAD

**Issue by h1z1** [xiph/flac#204]
https://github.com/xiph/flac/blob/7a35c528495b6d8a51e87e007f6810b5553101bc/CMakeLists.txt#L40

Though it'd probably be better to let cmake deal with flag resolution, the above forces no-pie on GNU compilers.   The option in gcc however is [-fno-pie](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#index-no-pie) and was added in GCC5.x

Any reason this was forced rather then use something like set(CMAKE_POSITION_INDEPENDENT_CODE OFF)?

**Comment by evpobr** [comment]
@krokoziabla ?
