### ISSUE TITLE
Git commit dates

### ISSUE THREAD

**Issue by evpobr** [xiph/flac#207]
37e675b and 4fbb6d4 both have strange commit dates in history (february). previous commit is correct (april).

**Comment by erikd** [comment]
That is how Git works. Dates are attached to git commits so that if the commits are not applied in the same order they are created, the dates will not be in order.

**Comment by evpobr** [comment]
According to [How GitHub uses the Git author date and commit date](https://help.github.com/en/github/setting-up-and-managing-your-github-profile/troubleshooting-commits-on-your-timeline#how-github-uses-the-git-author-date-and-commit-date) there are two dates in commit. Ok, i had no problems with `git pull upstream master`, so probably it is ok.

**Comment by erikd** [comment]
If you want to see both dates, `git log --pretty=fuller`.
