### ISSUE TITLE
clang-format of the tree

### ISSUE THREAD

**Issue by neheb** [xiph/flac#208]
While running clang-tidy on the tree, I've noticed inconsistencies in the codebase (mixed TAB and space, various code styles used, etc...).

How about running clang-format through the whole codebase in order to have a consistent style?

The main question would be which style is desired.

**Comment by erikd** [comment]
The most import thing we have in the repository other than the code itself is the change history.

I an see the benefit of applying an auto formater at the start of a project, applying an auto formater to an existing code base destroys the change history for close to zero benefit.

If auto formatting could be applied to the additions of diffs, they this may be worth considering.

**Comment by neheb** [comment]
There is integration with git clang-format, sure.

This is another project's approach to the problem: https://github.com/gerbera/gerbera/commit/0f1083e1dd4f390a548c3e4fdc5dc29dc159b4f6

No idea how this could be integrated with travis.

**Comment by erikd** [comment]
Having it as a CI check is fine, but how do people ensure its correct locally before pucking code to github?

Installing the required tools is probably easy to do on Linux but I wonder how easy this would be on Mac, Windows and other platforms.

@evpobr ?

**Comment by erikd** [comment]
Also I am not trying to be an asshat here, but I would like point out that the usefulness of this proposal is pretty minor in comparison to tackling the issues like #164 and #192 which I have not tackled due to lack of free time.

Discussing formatting issues and how to fix them are pretty close to the definition of bike shedding.

**Comment by neheb** [comment]
There's git integration: git clang-format HEAD~1

The real question is what style should be used. https://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options

**Comment by erikd** [comment]
For this to be considered at all we need:

* Formatting to only be applied to the changes to a file in a commit, not the whole file and not the whole project (for reasoning see https://github.com/xiph/flac/issues/208#issuecomment-623774148 ).
* It must be something that can be checked/validated in CI (if it is not checked it will get screwed up).
* It must be something that any dev can apply locally (for all there major OSes) before they push to GH (waiting for CI to provide a patch is too much friction on the development process).

**Comment by neheb** [comment]
All of that is true.

**Comment by erikd** [comment]
Ok, so it now depends on how easy this is for me to set up. The easier it is, the more likely it is to happen.

**Comment by ValZapod** [comment]
> base destroys the change history for close to zero benefit.

No, it does not. You will just have to do blame before the tidy commit. Github permits thag woth no problems.
