### ISSUE TITLE
seek_absolute does not report data corruption

### ISSUE THREAD

**Issue by bemoody** [xiph/flac#209]
The following base64-encoded data is an invalid FLAC file:

```
ZkxhQwAAACIBAAEAAABSAABSCsRA8AAAAwBy4b1wnrOxXtO4fYKpLBkGhAAAKCAAAAByZWZlcmVu
Y2UgbGliRkxBQyAxLjMuMiAyMDE3MDEwMQAAAAD/+IkIABMYAAAAAQACAAMAaqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgKZi//iJ
CAEUGAEAAQEBAgEDAGqqqqqqqqqqqqqqqqqqqqqrqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqoCyBP/4iQgCHRgCAAIBAgICAwBqqqqqqqqqqqqqqqqqqqqqqqqq
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqAjq4=
```

It consists of three frames with 256 samples each, but the second frame has been corrupted by flipping one bit.

If we try to read this file sequentially, libFLAC will correctly report that there is a CRC mismatch (the error callback will be invoked.)

However, if we start out by calling FLAC__stream_decoder_seek_absolute to jump to the middle of the corrupted frame, then libFLAC will *not* invoke the error callback.  From what I can tell, this makes it impossible for the application to detect corrupted data in this case.

For example, using the flac command-line tool:

- "flac -d -f bad.flac --skip=255" will report an error.

- "flac -d -f bad.flac --skip=256" will not report an error, but will silently fill the start of the output file with zeroes.

Ideally, seek_absolute should invoke the error callback (before invoking the write callback) if there is a CRC error in the *target* frame, but not in any other frames that it might attempt to decode in the process of searching for the target frame.

**Comment by ktmf01** [comment]
I just took a look at this, and it seems it is very similar to #276. Sorry for not taking a look at this sooner. 

Anyway, it seems #283 solves this issue. 
- "flac -d -f bad.flac --skip=255" will report an error, but adding -F will allow to decode it anyway
- "flac -d -f bad.flac --skip=256" will report a seek error, and adding -F will **not** allow decoding to continue. It simply cannot find the frame where sample 256 belongs to, as it won't accept the frame it belong to

Thanks for reporting
