### ISSUE TITLE
FLAC__stream_decoder_process_single decodes final frame twice?

### ISSUE THREAD

**Issue by mrkkrp** [xiph/flac#22]
Here is the minimal example that demonstrates the problem:

```c
#include <FLAC/stream_decoder.h>
#include <FLAC/metadata.h>
#include <stdlib.h>
#include <stdio.h>

static FLAC__StreamDecoderWriteStatus write_callback
  ( const FLAC__StreamDecoder *decoder
  , const FLAC__Frame *frame
  , const FLAC__int32 *const ibuffer[]
  , void *client_data)
{
  return FLAC__STREAM_DECODER_WRITE_STATUS_CONTINUE;
}

static void error_callback
  ( const FLAC__StreamDecoder *decoder
  , FLAC__StreamDecoderErrorStatus status
  , void *client_data )
{
  return;
}

int main (int argc, char *argv[])
{
  unsigned block_size, state;
  FLAC__StreamDecoder *decoder = FLAC__stream_decoder_new();

  FLAC__stream_decoder_init_file(decoder, argv[1], write_callback, NULL, error_callback, NULL);
  FLAC__stream_decoder_process_until_end_of_metadata(decoder);

  /* Total samples: 14442750 */

  while ((state = FLAC__stream_decoder_get_state(decoder)) != FLAC__STREAM_DECODER_END_OF_STREAM)
    {
      printf("State so far: %d\n", state);
      FLAC__stream_decoder_process_single(decoder);
      block_size = FLAC__stream_decoder_get_blocksize(decoder);
      printf("Processed frame of size: %d\n", block_size);
    }
  FLAC__stream_decoder_delete(decoder);
}
```

Compile it:

```
$ gcc -lFLAC -o my_prog main.c
```

Next I feed it a FLAC file that I know contains exactly 14442750 samples. With frame size of 4096, the behavior I expect is that the program prints

```
State so far: 2
Processed frame of size: 4096
```

…quite a few times, but eventually it should say that it processed the final frame of length `14442750 % 4096 == 254` samples. After that the status sholud change to `FLAC__STREAM_DECODER_END_OF_STREAM` and the application should finish.

The actual result is:

```
…
Processed frame of size: 4096
State so far: 2
Processed frame of size: 254
State so far: 2
Processed frame of size: 254
```

As you can see it processes 254 final samples twice, which leads to exactly 254 “extra” samples in output (the code that puts the result into a buffer is not shown here for simplicity).

Is this a bug or a feature? Am I wrong in my undrestanding of how it should work?

**Comment by lvqcl** [comment]
Not a programmer myself, but I suspect that the behaviour of FLAC__stream_decoder_process_single() is the same as of usual file reading routines:

http://stackoverflow.com/questions/4533063/how-does-ifstreams-eof-work

**Comment by mrkkrp** [comment]
Heh indeed, looks like it. It's been a while I used C for something like this, so I must have forgotten how it works. Anyway, it solves the problem, closing.
