### ISSUE TITLE
configure script no longer available in 1.3.3?

### ISSUE THREAD

**Issue by ellenjohnson** [xiph/flac#225]
Hi all!  I'm upgrading to 1.3.3 and see the configure script has been deleted since 1.3.2.  However, the build instructions still say to run configure.   Are you recommending now that we generate our own configure script via autogen.sh as mentioned in the note about "if you want to build completely from scratch"?
Thanks!

**Comment by ellenjohnson** [comment]
Thank you Ralph!  I see the configure script in the 1.3.3 source you link to.

The xiph.org site "Downloads" section (https://www.xiph.org/downloads/) has 1.3.2 as latest version, that's why I downloaded the tagged release for 1.3.3 from github.  Is there substantial difference between the github tagged 1.3.3 release and the release you pointed to apart from configure file(s)?

As I'm upgrading libogg, libflac, and libvorbis, should I have downloaded the source through xiph.org instead of github?

**Comment by erikd** [comment]
The versions from Github is the tagged version in the Git repo, but not the official release. The official release contains files (like `configure` and `Makefile`) that are not kept in git because they are generated files.

If you want the official realease then Xiph.org is the place to get it.

**Comment by erikd** [comment]
Closing this.

**Comment by ellenjohnson** [comment]
Thank you Erik and Ralph for pointing me to the flac downloads at https://ftp.osuosl.org/pub/xiph/releases/flac/.  But I'm still confused as to why the the libflac-1.3.3.tar.xz at Xiph.org doesn't have the CMake files (CMakeLists.txt, etc.) from when CMake support was added, yet the README in this download includes instructions to build with CMake.  

Ideally I would like a libflac 1.3.3 that contains both configure and CMake support.  So I think right now my best bet is to download flac from Xiph.org, then patch it with the CMake additions from the 1.3.3 tagged release in github.

**Comment by rillian** [comment]
Yes, the CMake build description wasn't included in the 1.3.3 release. Copying it from the tag or just building with cmake directly from the tag is fine.

This oversight was corrected in commit 6d0e222a6e03f1258129b9939d3eb47870d5502a so subsequent releases should have both builds available.
