### ISSUE TITLE
Any plans for 1.3.4?

### ISSUE THREAD

**Issue by gabor-zoka** [xiph/flac#239]
https://github.com/xiph/flac/commit/5f5035d2093421c43770eb0f0628e2f60aea61a5 is causing pain for me as I have 5 tracks in my collection where flac -t integrity checks fail due to this. It renders MD5 useless.

I asked my disto to patch it, but 4 months on no progress despite me giving a patch to the build system. But they pick up new releases quickly. 

So I have to build my own now. I know I am not alone with this problem.

I think this fix alone would deserve a release. Please consider this request.

Thanks,

Gábor

**Comment by erikd** [comment]
I will try to look at this on the weekend.

**Comment by gabor-zoka** [comment]
Thank you Erik. Much appreciated.

**Comment by gabor-zoka** [comment]
Hello Erik,

Could you consider the release? I ran into this again. 

Thank you for your time.

**Comment by ValZapod** [comment]
This is rediculous. ĢCC 11 is already out (27 April 2021), made Debian update to it.

**Comment by erikd** [comment]
@ValZapod What are you talking about?

> GCC 11 is already out (27 April 2021)

Is there any reason why you can't compile this with gcc 11?

>  make Debian update to it as a default 

What does Debian have to do with this?

**Comment by ValZapod** [comment]
They need to switch to new GCC, I mean.

**Comment by erikd** [comment]
@ValZapod The version Debian chooses to use to compile FLAC is completely out of my control. If you want Debian to build FLAC with a specifica GCC version, you need to bring that up with the Debian maintainers.

**Comment by gabor-zoka** [comment]
@erikd, what about a new cut of flac? You kindly replied to @ValZapod digression, but not the main question.

Isn't it bad enough that 'flac -t' checks do not work for tracks where md5 starts with 00 if you compile with any new gcc? I have loads of tracks of that. Not a rare case. The aformetion fix is in master, and a new release would pick it up and we could resume normality. I can compile it myself, but this must bother a large use base. 

Thank you,

Gabor

**Comment by erikd** [comment]
Its a matter of having the amount of required time and remember how the hell to do a release.

**Comment by rillian** [comment]
@erikd Hope you don't mind, I've been merging a few minor patches to help things move forward. Given the CVE report in #243 I think we should try to get a release out. I'm happy to work on that if you don't have time.

**Comment by erikd** [comment]
@rillian I do not mind al all. I have been trouble finding the time and motivation. I don't really so any C coding any more and work is keeping me super busy.

**Comment by rillian** [comment]
Ok, thanks. I'll see what I can do. I might need your help posting the release to sourceforge, but the rest I should be able to do.

Thanks everyone who's been reviewing pending patches. Very helpful!

**Comment by gabor-zoka** [comment]
Gentle reminder for a 1.3.4 release please. Reason is laid out at the start of the thread. Archlinux maintainer do not patch the official build. Thanks.

Gabor

**Comment by rillian** [comment]
I've created a 1.3.x branch with the fixes from the current default branch, minus the API changes. If there are no hitches with that I would like to post a v1.3.4 release from that branch tomorrow.

**Comment by roman-orekhov** [comment]
> I've created a 1.3.x branch with the fixes from the current default branch, minus the API changes. If there are no hitches with that I would like to post a v1.3.4 release from that branch tomorrow.

Can you please fix #286 before that? Do you maybe need a PR for that?

**Comment by ktmf01** [comment]
1.3.4 will only include fixes that were already in git and security related fixes. Sorry.

**Comment by roman-orekhov** [comment]
Oh ok. Hope that 1.3.5 won't take as much to release then :D

**Comment by rillian** [comment]
v1.3.4 is [now released](https://github.com/xiph/flac/releases/tag/1.3.4)!
