### ISSUE TITLE
Proper way to build with mingw/cmake

### ISSUE THREAD

**Issue by eddiezato** [xiph/flac#249]
I ran into some problems building with mingw/cmake.
My script:
```Bash
#!/bin/bash
export CC=clang CXX=clang++
git clone https://github.com/xiph/flac.git --recursive
cd flac
cmake -B build -G Ninja -S ./ \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_OGG=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_DOCS=OFF \
    -DINSTALL_MANPAGES=OFF \
    -DFLAC__NO_DLL=ON \
    -DCMAKE_EXE_LINKER_FLAGS='-fstack-protector-strong -static'
ninja -C build
```
1. There are lines in the output of cmake that worry me:
```
-- Looking for byteswap.h
-- Looking for byteswap.h - not found
...
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - not found
-- Looking for termios.h
-- Looking for termios.h - not found
-- Looking for clock_gettime
-- Looking for clock_gettime - not found
```
2. `flac.exe` requires `libintl-8.dll` at startup.

How can I solve these two problems?

**Comment by ktmf01** [comment]
Perhaps a bit late, but I'm replying anyway:
1. Why do the mentioned lines worry you? There are no errors, just notices? 
2. Is there any particular reason you don't want flac to be dependent on libintl-8.dll? What is the output of ldd on flac.exe?

**Comment by eddiezato** [comment]
1. I dunno, if there was an attempt to find these files, perhaps they are needed.
2. The reason is to get a single `flac.exe` without any dependencies to carry around.

In any case, I have already [managed](https://github.com/eddiezato/builds/blob/main/flac.sh) to build without using `cmake` and this issue can probably be closed if no one plans to figure out single-file static builds with `mingw/cmake`.

**Comment by eddiezato** [comment]
Do I necessarily need `libiconv` and `libintl` when building `flac.exe` with `cmake`? I made sure that they were not found and got my standalone `flac.exe` which doesn't need any dll's and works flawlessly.

**Comment by ktmf01** [comment]
No, that isn't necessary. I think this is an oversight in the cmake files. For MSVC for example, those libs aren't necessary either. I'll look into it.
