### ISSUE TITLE
flac-1.3.2: case07-expect.meta test failure

### ISSUE THREAD

**Issue by tgurr** [xiph/flac#25]
The release tarball available on http://downloads.xiph.org/releases/flac/ doesn't carry the changes from ac39d3719f16dfb6e08d2fbde8ccaf34a266c81d for the case07-expect.meta file, resulting in a test failure:

[...]
test case06: --set-tag=TITLE... OK
test case07: --show-vendor-tag --show-tag=ARTIST... make[1]: Leaving directory '/var/tmp/paludis/build/media-libs-flac-1.3.2/work/flac-1.3.2/test'
ERROR: metadata does not match expected ../test/metaflac-test-files/case07-expect.meta
make[1]: *** [Makefile:707: check] Error 1
make: *** [Makefile:486: check-recursive] Error 1
[...]

**Comment by erikd** [comment]
The mirroring for download.xiph.org (hosted by http://osuosl.org/ ) is borked.

For now https://sourceforge.net/projects/flac/files/flac-src/ may be a better option. The sha256sum should be:
```
91cfc3ed61dc40f47f050a109b08610667d73477af6ef36dcad31c31a4a8d53f  flac-1.3.2.tar.xz
```

**Comment by tgurr** [comment]
Thanks, that one works fine.

**Comment by erikd** [comment]
Cool. I'll close this then. Someone is working on getting the mirrors fixed.
