### ISSUE TITLE
compression_levels_ should be const

### ISSUE THREAD

**Issue by randomascii** [xiph/flac#26]
While doing a cleanup pass over globals that are in the read/write segment but could/should be in the read-only segment I noticed that compression_levels_ is not marked as const but could be:

https://github.com/xiph/flac/blob/master/src/libFLAC/stream_encoder.c#L102

This would move the array to the read-only segment which slightly reduces private memory. FWIW.

**Comment by erikd** [comment]
Good point. I'll fix that.

**Comment by randomascii** [comment]
Thanks! 396 bytes down...
