### ISSUE TITLE
[Embedded]"long long" not recognize by my compiler (VisualDSP++4.5)

### ISSUE THREAD

**Issue by Tolgotha** [xiph/flac#27]
Hello,

I'm trying to implement a Flac encoder/decoder on a Sharc DSP board, with VisualDSP++ 4.5 as the compiler IDE, but I keep encountering the same error when compiling:

__int64 "long long" is a nonstandard type

This happen when the compiler interpret any line with the use of "__int64" type. Have you any ideas how can I bypass this problem?  

Best regards,

Tolgotha

**Comment by erikd** [comment]
> I'm trying to implement a Flac encoder/decoder on a Sharc DSP board, with VisualDSP++ 4.5 as the > compiler IDE, but I keep encountering the same error when compiling:
> 
> __int64 "long long" is a nonstandard type

What file? What line number?

Unfortunately, I have no experience with VisualDSP. How are you configuring an building it? Does your system have a 64 bit signed integer type?

**Comment by Tolgotha** [comment]
Here is the file & line where the error is:

"include/types.h", line 44: cc0450:  error: the type "long long" is nonstandard
  typedef __int64 __time64_t;

The software implementation is based on a "talkthrought" implementation, which allows me to :
- **Step1**: Use an input of the board (RCA input)
- **Step2**: Make it throught the DSP for audio processing, and then 
- **Step3**: Leading the signal to an output (RCA output)

Flac implementation comes on **Step 2**, I simply add the source code to my project , include the header in my main function, and finally juste use the function "encoder" in the flac example encoding directory (the encoder example provided).

The documentation of the system (ADSP 21161, i forget to mention it) clearly told that it supports **64 bits operations & movement between register**.

At a certain point, the compilation failed and told me that "unistd.h" was missing from my project, i look for it on the internet to find a convenient one. I had to add then "sdkddkver.h" & "__mingw.h".

My thought about what I've just described:
- **I may have take an incorrect "unistd.h" file**, but in this case did you have any advice on how to define "unistd.h" to implement Flac on a system which does not have an os? ( As an embedded system, the only file upload on the board will be the ones of the Flac recorder I try to implement)

**Comment by erikd** [comment]
Sorry, you did not answer my question "How are you configuring an building it?".

Are you using the `Makefile.lite` build system, the autoconf one or something else?

**Comment by lvqcl** [comment]
IMHO this problem with VisualDSP++ 4.5 is totally unrelated to FLAC

**Comment by erikd** [comment]
@lvqcl I would agree, but I am still trying to help. I also wonder where @Tolgotha got the `unistd.h` file they are using.

**Comment by Tolgotha** [comment]
Thank you everybody for the answers, it helps me a lot!

So first of all, sorry for not having been clear enough about the build, i didn't build Flac becore trying to compile the project containing the other file, should I ? I first wanted to check if the compiler get no error. (I work under windows as VisualDSP don't work under linux...)

Function like chown() or unlink() seem to be understood by the compiler but not implemented as i got such error:

_[Error li1021]  The following symbols referenced in processor 'p0' could not be resolved:
        'chown [_chown]' referenced from 'Debug\main.doj'_

**Comment by Tolgotha** [comment]
I forgot, here is the file i use to include "unistd.h":
https://sourceforge.net/p/mingw/mingw-org-wsl/ci/4.0.0/tree/include/unistd.h

I thought that if i was developping under Windows os, even if the project will be implemented on a embedded system, I would need a "unistd.h" related to Windows.

**Comment by erikd** [comment]
That file is obviously not correct (to me anyway) for Visual DSP. That is the "unistd.h" for the MinGW compiler for Windows. You need to write (or get from somewhere) a valid "unistd.h" for Visual DSP.

**Comment by Tolgotha** [comment]
Okay, thank you for clearing that point!

So, do you think I first have to make & build Flac (with MSVC) under windows before importing it under my VisualDSP project?

**Comment by erikd** [comment]
> So, do you think I first have to make & build Flac (with MSVC) under windows before importing it under my VisualDSP project?

Building under Windows first does nothing more than waste your time.

**Comment by Tolgotha** [comment]
Thank you very much sir, I'll try to write my own unistd.h and let you know how it worked! 
The final goal is to create kind of an audio recorder card (multitrack) for live purpose.
