### ISSUE TITLE
Errors in metadata are silently dropped/cause overrun of block

### ISSUE THREAD

**Issue by ktmf01** [xiph/flac#291]
Digging a little more after sending in #290 I found the current handling of errors in metadata blocks is really inconsistent

- When a streaminfo or cuesheet block is too short, libFLAC overreads into the next block/frame
- When a streaminfo or seektable is too long, the remainder is silently ignored
- When a vorbis comment block isn't filled, the remainder is silently ignored
- When a vorbis comment block is too long, the remaining comments are silently ignored
- Without #290, when a picture block is too short, libFLAC overreads into the next block/frame

I'd say this behaviour should be changed. I suggest adding a new error, `FLAC__STREAM_DECODER_ERROR_STATUS_BAD_METADATA` or using `FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM` in case anything is found that is not according to spec or when the contents of a block are suggested to be smaller or larger than the blockheader states. After emitting such an error, the decoder should stop parsing metadata completely (if the block itself is corrupt, the metadata block lengths cannot be trusted either, and the decoder might lose sync. Resyncing to metadata blocks is not possible) and start looking for a frame sync code.

Please comment.

**Comment by rillian** [comment]
If we're changing the API, adding a `BAD_METADATA` error seems reasonable.

The decoder certainly shouldn't over-read, but some applications, in the context of Ogg, pad the vorbiscomment data to make it possible to edit the file later without having the re-write all the subsequent audio data. You mentioned concern about losing frame sync, so maybe I don't understand correctly what you mean by "too long", but if there's a way to leave empty space at the end of a comment or seektable block, where it's not ambiguous, that's a useful thing to support.

**Comment by ktmf01** [comment]
> The decoder certainly shouldn't over-read, but some applications, in the context of Ogg, pad the vorbiscomment data to make it possible to edit the file later without having the re-write all the subsequent audio data. [...] but if there's a way to leave empty space at the end of a comment or seektable block, where it's not ambiguous, that's a useful thing to support.

There is already a PADDING metadata block type for those purposes, so also allowing padding in the blocks themselves seems superfluous.

> You mentioned concern about losing frame sync, so maybe I don't understand correctly what you mean by "too long"

The problem I see here is that a file becomes completely unreadable when metadata blocks aren't checked for consistency, because contrary to FLAC audio frames, FLAC metadata blocks have no intrinsic consistency checks except for checking the length of the contents with the length written in the header. Here's an explanation.

Presume a bit is flipped in a FLAC audio frame. The FLAC format has been designed to properly handle these, and the libFLAC decoder does pretty well: if one of the CRCs doesn't check out, data in the headers doesn't make sense or the residual contains illegal values, the decoder can simply drop a block and look for a sync code, either 0xFFF8 or 0xFFF9, and check that frame for consistency.

However, when a bit is flipped in a FLAC metadata block and the decoder stops reading a block too early (underreads) or too late (overreads), it expects the next metadata block header to be just where it stopped reading. There is no sync code and it simply has to assume the next 4 bytes form a metadata block header. Chances are 1 to 127 it will reject it because of an illegal value, but else it will skip a number of bytes between 0 and 2^24 depending on what bytes it stumbled. There is one flag bit which tells the decoder a metadata block is the last one, but being fed random data chances are 50% it will assume finding another block, skipping another 0 to 2^24 bytes. Depending on the size of a file, it might even reach end-of-stream before even trying to start parsing audio frames.

Doing some sanity checks on the metadata contents will quickly reveal that a metadata block is corrupt. When the decoder then stops looking for more metadata and starts looking for a frame sync code, it is assured the decoder won't accidentally skip audio data.

**Comment by ktmf01** [comment]
This is fixed by #290, which was extended after being mentioned in the first message in this issue
