### ISSUE TITLE
flac -d --keep-foreign-metadata with wrong foreign metadata yields wrong error message.

### ISSUE THREAD

**Issue by H2Swine** [xiph/flac#296]
Situation: `flac -d --keep-foreign-metadata` on a file that has AIFF metadata creates `ERROR reading foreign metadata: no foreign metadata found (022)`. 
User would expect it to say it has wrong metadata, not to suggest it has none. 
Also I am not sure what is expected behaviour on a file that _indeed has no_ metadata: err out, or produce one which keeps all the foreign metadata that are, namely none?

Likewise,  `--keep-foreign-metadata --force-rf64-format` yields the same as with wav,  `--keep-foreign-metadata --force-aiff-format` produces that error when the .flac file has metadata not from AIFF - and since I don't have any tool that can tag .w64, I couldn't get `--keep-foreign-metadata --force-wave64-format` to produce anything but errors. 

Tried win64 flac.exe versions 1.3.1 and 1.3.4.  FLAC files attached.

[issue_--keep-foreign-metadata.zip](https://github.com/xiph/flac/files/8172931/issue_--keep-foreign-metadata.zip)

**Comment by ktmf01** [comment]
@dericed If I recall correctly you are/were a regular user of this functionality of flac. Besides the problem mentioned here I've always wondered about the folllowing: If a user encodes a WAV/AIFF file to flac and flac finds foreign metadata (which is not being stored), it warns the user and suggests using --keep-foreign-metadata. However, if a flac file is being decoded, no similar warning is present. Should flac also warn the user in the latter case?

Could you perhaps provide an opinion on what behaviour seems best, and whether you suggest other changes? Should warnings be errors or the other way around?

**Comment by ktmf01** [comment]
Issue #61 is related

**Comment by ktmf01** [comment]
Other issues with --keep-foreign-metadata:
https://sourceforge.net/p/flac/bugs/485/
https://sourceforge.net/p/flac/bugs/486/

**Comment by ktmf01** [comment]
Okay, I've working on this today. Here's a warning when a file is decoded without --keep-foreign-metadata

```
src/flac/flac -df tagged.aiff.flac
[...]
tagged.aiff.flac: WARNING: found foreign metadata, use --keep-foreign-metadata to restore
tagged.aiff.flac: done 
```
And one for decoding to the wrong filetype
```
src/flac/flac -df --keep-foreign-metadata tagged.aiff.flac
[...]
tagged.aiff.flac: ERROR reading foreign metadata: found foreign metadata of wrong type, try decoding to AIFF instead
```
```
src/flac/flac -df --keep-foreign-metadata tagged.wav.flac -o test.aiff
[...]
tagged.wav.flac: ERROR reading foreign metadata: found foreign metadata of wrong type, try decoding to WAV or RF64 instead
```
I'll send in a PR soon, but in the meantime, any comments?

**Comment by ktmf01** [comment]
Even more additions: the option -keep-foreign-metadata-if-present, which only warns, no errors
```
src/flac/flac --keep-foreign-metadata-if-present -f -d tagged.aiff.flac
[...]
tagged.aiff.flac: WARNING reading foreign metadata: found foreign metadata of wrong type, try decoding to AIFF instead
tagged.aiff.flac: done         
```

```
src/flac/flac --keep-foreign-metadata-if-present -d somefile.flac
[...]
somefile.flac: WARNING reading foreign metadata: no foreign metadata found (022)
somefile.flac: done
```
