### ISSUE TITLE
flac failed to build with error MSB4126: The specified solution configuration "Release|arm64" is invalid.

### ISSUE THREAD

**Issue by YangYang129** [xiph/flac#302]
flac failed to build with error MSB4126: The specified solution configuration "Release|arm64" is invalid with MSVC on windows. It can reproduces on version https://github.com/xiph/flac/commit/2610594d04e6deb5c9bc0c8c7f620769c0c1149a. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019 (16.11.9)
Operating system: Windows server 2019

**Steps to reproduce:**
1. open VS2019 x64 tools command
2. git clone https://github.com/xiph/flac F:\gitP\xiph\flac
3. cd F:\gitP\xiph\flac
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
5. devenv /upgrade ..\libogg-1.3.2\win32\VS2010\libogg_static.sln
6. msbuild ..\libogg-1.3.2\win32\VS2010\libogg_static.sln /t:Rebuild /p:Configuration=Release;Platform=arm64

**Build.log:**
[build (1).log](https://github.com/xiph/flac/files/8195193/build.1.log)

**Error info:**
F:\gitP\xiph\flac\FLAC.sln.metaproj : error MSB4126: The specified solution configuration "Release|arm64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [F:\gitP\xiph\flac\FLAC.sln]

**Comment by ktmf01** [comment]
The MSVC solution files don't provide an arm64 target, so this is expected. Can you try configuring the build with CMake? See the README file for instructions

**Comment by YangYang129** [comment]
@ktmf01 Thank you very much
