### ISSUE TITLE
metaflac question for script

### ISSUE THREAD

**Issue by syswombat** [xiph/flac#307]
Hello 
i have debian 11 Kernel: 5.16.0-5-amd64 x86_64 

and done a little script to rip some music CD's it works so far

mkdir -p ~/Musik/rip-CD/
cd ~/Musik/rip-CD/

abcde -o flac

find ~/Musik/rip-CD/ -name "*.flac" -print0 |xargs -0 metaflac --import-picture-from="3|*.jpg"
find ~/Musik/rip-CD/ -name "*.flac" -print0 |xargs -0 metaflac --import-picture-from="3|~/Musik/rip-CD/cover.jpg"
find ~/Musik/rip-CD/ -name "*.flac" -print0 |xargs -0 metaflac --import-picture-from="cover.jpg"
find ~/Musik/rip-CD/ -name "*.flac" -print0 |xargs -0 metaflac --import-picture-from=cover.jpg

But non of this will add the cover into the flac file 

what is wrong with this commands?

have a nice day
vinc

**Comment by ktmf01** [comment]
Shouldn't you be using
```
find ~/Musik/rip-CD/ -name "*.flac" -print0 |xargs -0 metaflac --import-picture-from=cover.jpg
```
So with `-name "*.flac"` instead of `-name ".flac"`?

**Comment by ktmf01** [comment]
@syswombat Can you clarify whether this fixes this issue, so I can close it?

**Comment by ktmf01** [comment]
I'm closing this because of the lack of response
