### ISSUE TITLE
Building with CMake never defines HAVE_LANGINFO_CODESET

### ISSUE THREAD

**Issue by CircuitCoder** [xiph/flac#308]
Buliding with CMake + Ninja never adds `-DHAVE_LANGINFO_CODESET` to compiler options, so locale detection is not complete in such situation.

Notably, ArchLinux now builds flac with CMake + Ninja (https://github.com/archlinux/svntogit-packages/blob/packages/flac/trunk/PKGBUILD), which causes some locale issue when tagging FLAC files. See: https://github.com/svend/cuetools/issues/38#issuecomment-1082859037

**Comment by NotTsunami** [comment]
@CircuitCoder Does #309 work for you? I copied the test how it is in autotools, it fails on darwin and ubuntu CIs, but I'm not sure what systems use this header.

**Comment by CircuitCoder** [comment]
@NotTsunami Sorry for the late response. Actually the test fails with the following compiler error:
```
/root/workspace/flac/build/CMakeFiles/CMakeTmp/src.c:3:16: error: initializer element is not constant
    3 |     char* cs = nl_langinfo(CODESET);
      |                ^~~~~~~~~~~
```
It seems that right now cs is a global variable initialized with nl_langinfo. Maybe `char* cs = ...` need to be moved into inside the main function?

**Comment by NotTsunami** [comment]
> @NotTsunami Sorry for the late response. Actually the test fails with the following compiler error:
> 
> ```
> /root/workspace/flac/build/CMakeFiles/CMakeTmp/src.c:3:16: error: initializer element is not constant
>     3 |     char* cs = nl_langinfo(CODESET);
>       |                ^~~~~~~~~~~
> ```
> 
> It seems that right now cs is a global variable initialized with nl_langinfo. Maybe `char* cs = ...` need to be moved into inside the main function?

I'll push another patchset tonight.

**Comment by NotTsunami** [comment]
> @NotTsunami Sorry for the late response. Actually the test fails with the following compiler error:
> 
> ```
> /root/workspace/flac/build/CMakeFiles/CMakeTmp/src.c:3:16: error: initializer element is not constant
>     3 |     char* cs = nl_langinfo(CODESET);
>       |                ^~~~~~~~~~~
> ```
> 
> It seems that right now cs is a global variable initialized with nl_langinfo. Maybe `char* cs = ...` need to be moved into inside the main function?

Just pushed the new patchset if you want to give it a whirl! I'll try to spin up an Arch box in the next couple days if I don't hear back and attempt to replicate.

**Comment by CircuitCoder** [comment]
@NotTsunami It seems to be working now on Arch!
![image](https://user-images.githubusercontent.com/2051572/164348341-c2425fac-5802-4840-a1a6-6d0d47a38307.png)

**Comment by ktmf01** [comment]
@CircuitCoder Thanks for reporting and @NotTsunami thanks for sending in a fix. I've opened #324, as I think issues like these should problems should be proactively handled
