### ISSUE TITLE
Conversion from 'double' to 'float', possible loss of data errors

### ISSUE THREAD

**Issue by Gradius2** [xiph/flac#313]
Hi,

Compiling with the last MSVS 2022, I got a lot _double to float, and possible loss from data_ errors.

I can see the project was used for VS 2010, that's way too undated and old.

_Changing Platform Toolset to "v143" (was "v100"): v100 = VS2010_

The errors:
5>C:\flac\src\libFLAC\format.c(580,110): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
5>C:\flac\src\libFLAC\format.c(582,106): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
5>C:\flac\src\libFLAC\format.c(584,74): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
-----------
5>C:\flac\src\libFLAC\metadata_iterators.c(579,25): warning C4244: 'return': conversion from 'const __int64' to 'off_t', possible loss of data
5>C:\flac\src\libFLAC\metadata_iterators.c(1117,33): warning C4244: '+=': conversion from 'const __int64' to 'uint32_t', possible loss of data
5>C:\flac\src\libFLAC\metadata_iterators.c(1129,44): warning C4244: '=': conversion from '__int64' to 'uint32_t', possible loss of data
5>C:\flac\src\libFLAC\metadata_iterators.c(1152,35): warning C4244: '-=': conversion from 'const __int64' to 'uint32_t', possible loss of data
5>C:\flac\src\libFLAC\metadata_iterators.c(1647,34): warning C4244: '=': conversion from '__int64' to 'uint32_t', possible loss of data
5>C:\flac\src\libFLAC\metadata_iterators.c(1652,37): warning C4244: '=': conversion from '__int64' to 'uint32_t', possible loss of data
5>C:\flac\src\libFLAC\metadata_iterators.c(1666,36): warning C4244: '=': conversion from 'const __int64' to 'uint32_t', possible loss of data
-----------
5>C:\flac\src\libFLAC\metadata_object.c(1127,28): warning C4244: '=': conversion from 'FLAC__uint64' to 'uint32_t', possible loss of data
-----------
5>C:\flac\src\libFLAC\stream_encoder.c(3974,148): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
5>C:\flac\src\libFLAC\stream_encoder.c(3976,145): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
-----------
5>C:\flac\src\libFLAC\window.c(71,101): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(80,64): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(80,100): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(90,71): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(90,110): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(90,149): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(112,77): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(112,120): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(112,163): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(112,206): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(133,65): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(142,63): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(151,67): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(151,104): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(151,141): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(160,68): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(160,101): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(160,134): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(203,58): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(204,70): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(228,57): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(232,57): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(254,57): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(258,57): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(262,57): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
5>C:\flac\src\libFLAC\window.c(266,57): warning C4244: 'function': conversion from 'double' to 'float', possible loss of data
-----------
9>C:\flac\src\test_seeking\main.c(151,35): warning C4244: '=': conversion from '__int64' to 'uint32_t', possible loss of data
9>C:\flac\src\test_seeking\main.c(323,20): warning C4244: '=': conversion from '__int64' to 'long', possible loss of data
-----------
12>C:\flac\src\share\grabbag\picture.c(290,54): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
12>C:\flac\src\share\grabbag\picture.c(308,59): warning C4244: 'function': conversion from 'const __int64' to 'FLAC__uint32', possible loss of data
-----------
20>C:\flac\src\test_streams\main.c(110,9): warning C4244: 'function': conversion from 'FLAC__uint64' to 'int', possible loss of data
20>C:\flac\src\test_streams\main.c(111,11): warning C4244: 'function': conversion from 'FLAC__uint64' to 'int', possible loss of data
20>C:\flac\src\test_streams\main.c(112,11): warning C4244: 'function': conversion from 'FLAC__uint64' to 'int', possible loss of data
20>C:\flac\src\test_streams\main.c(113,11): warning C4244: 'function': conversion from 'FLAC__uint64' to 'int', possible loss of data
========== Build: 26 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Please, consider to update to VS2022 now (yes, retail is out since March 31, 2022, and the last update is from this month).

**Comment by NotTsunami** [comment]
Regarding the Visual Studio project files, using CMake with Visual Studio is the preferred way to build now. Taken from the README:

`When building with MSVC, using CMake is preferred, see Building with
CMake for more information. Building with MSVC using solution files
is deprecated and these files will be removed in the future.`

**Comment by Gradius2** [comment]
Actually, cmake from flac is pretty much a mess.  Of course I tried and doesn't works at all.  Lots of errors.

**Comment by Gradius2** [comment]
I changed few things.  100% the same error.  cmake or not, has nothing to do with the erros.

**Comment by ktmf01** [comment]
Those aren't errors, they are warnings. It would be nice if they were silenced, but none of them (currently) contain anything noteworthy.

Please report any difficulty you have working with CMake. As mentioned, the sln files will be removed at some point in the near future in favor of building with CMake.

As to why flac still uses MSVC 2010 files: it is very easy to upgrade these files, but very hard to downgrade. As Visual Studio 2012 is still supported by Microsoft and people use old versions for various reasons, we do not upgrade unless necessary.

One reason to use an older version is for example to target Windows XP. MSVC 2017 is the last version to support that.

**Comment by Gradius2** [comment]
@ktmf01 

Yes, I know sln will be removed soon.  Why would anyone wants to downgrade?

If 2017 was the last under XP (pretty dead to me), then at least make it VS2017 up-to-dated.

**Comment by ktmf01** [comment]
> @ktmf01 
> 
> Yes, I know sln will be removed soon.  Why would anyone wants to downgrade?

To use the files with older versions of VS

> If 2017 was the last under XP (pretty dead to me), then at least make it VS2017 up-to-dated.

That would make it difficult to use these with VS versions older than 2017, and it would provide no benefit for a VS2022 user such as yourself I presume. Microsoft still provides support for versions as old as VS2012, so I don't see why FLAC shouldn't too.

What benefit do you expect from updating these files to VS2017?

**Comment by ccawley2011** [comment]
It's possible to have the MSVC projects automatically select use the default platform toolset for the version of Visual Studio that's being used. For reference, this is how SDL2 does it: https://github.com/libsdl-org/SDL/commit/b0daa9f1db90ac568383a9a1741a9e2629fd1004

**Comment by ktmf01** [comment]
As FLAC is moving to CMake for MSVC, this isn't really necessary, soon the sln files will be removed. The warnings will stay however, that's why I sent in PR #321
