### ISSUE TITLE
increase possible values for sample rate.

### ISSUE THREAD

**Issue by tandersn** [xiph/flac#322]
This is simply a "feature request".  Myself and some others have been using flac to encode RF samples from SDRs and such other devices, in the Mhz range. It works great, sometimes the resulting file is 45% of original. However, flac doesn't seem to accept sample rate values into the Mhz region so we have been using actual sample rate / 1000 (40msps file encoded as 40ksps).  

Just wondering if it would be possible to allow for sample rates much higher than current ones? 

(like use unsigned long long int to get up to 18,446,744,073,709,551,615 )

**Comment by ktmf01** [comment]
FLAC was obviously not designed for these uses. It is nice to see that it works well though. My question to you is: what problems do you experience with your current approach? The FLAC format uses a 20-bit field to store sample rate, this can not be changed without breaking backward compatibility. I would suggest storing the actual sample rate in a tag (also known as a vorbis comment field).

You could write a script that uses metaflac to read and write a tag like ACTUAL_SAMPLE_RATE or something similar, whatever works for you. I presume compatibility with audio players isn't necessary anyway?

**Comment by tandersn** [comment]
Thanks for your response. It would just have been nice to be able to do something like "ffmpeg -i file.flac" and get the actual sample rate, and have some of the other tools work natively.  Right now i just specify 1/1000th of sample in flac command and then multiply by 1000 upon reading.

**Comment by ktmf01** [comment]
> It would just have been nice to be able to do something like "ffmpeg -i file.flac" and get the actual sample rate

That just happens to work when you add a tag like ACTUAL_SAMPLE_RATE. ffmpeg shows all FLAC tags when invoked like that.
