### ISSUE TITLE
Download failed for flac via brew

### ISSUE THREAD

**Issue by kuwapa** [xiph/flac#334]
Hello, thank you for maintaining this project!

I'm trying to install this project - https://github.com/Genymobile/scrcpy and one of the dependencies is flac. However, on doing brew install scrcpy, the process is failing and stopping at failing to download Flac. This is the error message I see

```
==> Downloading https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
Trying a mirror...
==> Downloading https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.4.tar.xz
Error: scrcpy: Failed to download resource "flac"
Download failed: Homebrew-installed `curl` is not installed for: https://downloads.xiph.org/releases/flac/flac-1.3.4.tar.xz
```

I'm running macOS High Sierra 10.13.4 on a MBP 2015 model. 

Please guide on how to resolve this error. Thank you so much!

**Comment by ktmf01** [comment]
This seems to be a brew problem, not a FLAC one. Can you try this solution? https://github.com/Homebrew/discussions/discussions/2357#discussioncomment-1544008

**Comment by kuwapa** [comment]
Thank you @ktmf01. I didn't try the solution in the method you mentioned but I tried directly installing flac via brew instead of it being installed as a dependency of scrcpy and that worked! Thanks.
