### ISSUE TITLE
[doc] link to git repo is wrong

### ISSUE THREAD

**Issue by fireattack** [xiph/flac#344]
At both https://xiph.org/flac/developers.html and https://xiph.org/flac/download.html , the link to git repo is https://git.xiph.org/?p=flac.git;a%3Dsummary and it's down. From what I can see on [WaybackMachine](https://web.archive.org/web/20190503011125/https://git.xiph.org/?p=flac.git;a%3Dsummary), it probably was down for at least 2 years. Maybe we should change the target to here?

**Comment by ktmf01** [comment]
Yes, I know. I've sent in a patch 2 years ago here: http://lists.xiph.org/pipermail/flac-dev/2020-July/006486.html

However, the previous FLAC maintainer has quietly left, so I'm currently trying to care of this repository. I only have write access to this one, not to [#xiph/flac-website](https://github.com/xiph/flac-website/).

**Comment by ktmf01** [comment]
This has been fixed: https://github.com/xiph/flac-website/commit/62768e988d6e016ebad49f7086154d058cab6929
