### ISSUE TITLE
libogg - what's the story, please? 

### ISSUE THREAD

**Issue by seamusdemora** [xiph/flac#367]
The README says: 

>To build FLAC with support for Ogg FLAC you must have built and installed libogg according to the specific instructions below. 

What instructions? Specifically, do I need to round up the libogg sources before - or are the pulled in during the build process?

**Comment by ktmf01** [comment]
It depends on what build system you're using.

If you use the autotools build system, it is expected you build and install libogg with its autotools build system as first and FLAC should find libogg without any problems. Otherwise, the README says, under `Building in a GNU environment`

```
--with-ogg=
--with-xmms-prefix=
--with-libiconv-prefix=
Use these if you have these packages but configure can't find them.
```

If you use the CMake build system, the instructions are
```
By default CMake will search for OGG. If CMake fails to find it you can help
   CMake by specifying the exact path:

   /path/to/flac-build$ cmake /path/to/flac-source -DOGG_ROOT=/path/to/ogg
   
   If you would like CMake to build OGG alongside FLAC, you can place the ogg
   sources directly in the flac source directory as a subdirectory with the name
   ogg, for example 
   
   /path/to/flac-source/ogg

   If you don't want to build flac with OGG support you can tell CMake not to
   look for OGG:
```

When building with CMake GUI
```
   CMake searches by default for OGG on your system and returns an error if it
   cannot find it. If you want to build OGG alongside FLAC, you can download the
   OGG sources and extract them in a subdirectory of the FLAC source directory 
   with the name ogg (i.e. /path/to/flac-source/ogg) before running CMake. If
   you don't want to build FLAC with OGG support, untick the box following
   WITH_OGG flag in the list of variables in cmake-gui window and run
   "Configure" again.
```

I agree the instructions for the autotools system are not clear enough, but I think the CMake part is quite clear.

**Comment by seamusdemora** [comment]
@ktmf01 :
> It depends on what build system you're using.
> 
> ... Otherwise, the README says, under `Building in a GNU environment`:
> ```
> --with-ogg=
> --with-xmms-prefix=
> --with-libiconv-prefix=
> Use these if you have these packages but configure can't find them.
> ```

I'm glad you mentioned that :)  I am building in the GNU environment, and on a old-ish lightweight Raspberry Pi. The README also says: "`./configure && make && make check && make install` _should work_". But there is no `configure` in the repo! I'm at a loss - if this is due to my inexperience, please forgive me.

**Comment by petterreinholdtsen** [comment]
[Seamus]
> I'm glad you mentioned that :)  I am building in the GNU environment,
> and on a old-ish lightweight Raspberry Pi. The README also says:
> "`./configure && make && make check && make install` _should
> work_". But there is no `configure` in the repo! I'm at a loss - if
> this is due to my inexperience, please forgive me.

The configure script is only present in the tarball, and is generated
when the tarball is created.

Try running autoreconf from the autoconf package to generate it.
-- 
Happy hacking
Petter Reinholdtsen

**Comment by ktmf01** [comment]
In that case, you can probably install libogg via your package manager. If you are using Raspbian (Raspberry Pi OS) than you can use `sudo apt install libogg-dev` to install the necessary dependencies. You can compile libogg from source of course.

As petterreinholdtsen mentions configure is only present in a release download. There is a script to generate configure, autogen.sh. So, to compile from git the complete command line is `./autogen.sh && ./configure && make && make check && make install`

**Comment by seamusdemora** [comment]
@petterreinholdtsen , @ktmf01 

Thanks for your help. When I described my target as `old-ish lightweight Raspberry Pi`, that wasn't the complete story. It is actually an `old-ish lightweight Raspberry Pi that is running *jessie*`. Consequently, getting `autotools` - or anything else via `apt` is not possible. 

`autogen`, being a component of `autotools` won't work in this instance - at least AFAIK. 

But you mentioned, *"The configure script is only present in the tarball, and is generated when the tarball is created."* 

Where do I get the tarball? I don't see it here.

**Comment by ktmf01** [comment]
You can get them through the website https://xiph.org/flac/download.html, at https://ftp.osuosl.org/pub/xiph/releases/flac/

**Comment by seamusdemora** [comment]
Danke!

**Comment by seamusdemora** [comment]
> Otherwise, the README says, under `Building in a GNU environment`
> 
> ```
> --with-ogg=
> --with-xmms-prefix=
> --with-libiconv-prefix=
> Use these if you have these packages but configure can't find them.
> ```

And now I'm afraid I must ask you for some clarification on these libogg instructions. I found a libogg tarball at https://www.xiph.org/downloads/. I built and installed it in `/usr/local/lib`. But trying `.configure` in the `flac` folder again yielded no improvement. Also I'll need more research to find tarballs for `xmms` and `libiconv` I guess?? Sorry to be a pest... would the `autotools` have done all of this grunt work for me?

**Comment by ktmf01** [comment]
It should work without any additions, so `./configure` should work. Otherwise try with `./configure --with-ogg=/usr/local`

flac needs the library files in /usr/local/lib but it also needs the header files in /usr/local/include. Therefore --with-ogg expects a prefix, usually this is /usr but in your case it is /usr/local

**Comment by seamusdemora** [comment]
@ktmf01 

I made 2 edits to my previous post that contained a lot of details. For some reason, those edits do not appear in the post, but I can see them by licking the 'drop-down' in the header above my post. Did you see those?? 

Anyway - I tried your suggestion just now using `./configure --with-ogg=/usr/local`, and I get the same error. The warning message in my terminal says - in part: 

>configure: WARNING: *** Ogg development environment not installed - Ogg support will not be built

The `development environment` not installed???  I found the header file for `ogg` in this location:

```bash
$ ls -l /usr/local/include/ogg | grep ogg
-rw-r--r-- 1 root root 8373 May 31 07:08 ogg.h
```

I tried this, but same result:

```
./configure --with-ogg=/usr/local/include
``` 

Following is a potentially useful portion of the output generated during the `make install` of libogg:
```
~/libogg-1.3.5 $ sudo make install
```
...
>Making install in src
make[1]: Entering directory '/home/pi/libogg-1.3.5/src'
make[2]: Entering directory '/home/pi/libogg-1.3.5/src'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool   --mode=install /usr/bin/install -c   libogg.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libogg.so.0.8.5 /usr/local/lib/libogg.so.0.8.5
libtool: install: (cd /usr/local/lib && { ln -s -f libogg.so.0.8.5 libogg.so.0 || { rm -f libogg.so.0 && ln -s libogg.so.0.8.5 libogg.so.0; }; })
libtool: install: (cd /usr/local/lib && { ln -s -f libogg.so.0.8.5 libogg.so || { rm -f libogg.so && ln -s libogg.so.0.8.5 libogg.so; }; })
libtool: install: /usr/bin/install -c .libs/libogg.lai /usr/local/lib/libogg.la
libtool: install: /usr/bin/install -c .libs/libogg.a /usr/local/lib/libogg.a
libtool: install: chmod 644 /usr/local/lib/libogg.a
libtool: install: ranlib /usr/local/lib/libogg.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
>Libraries have been installed in:
   /usr/local/lib

>If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

>See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
...

**Comment by ktmf01** [comment]
I don't know why it doesn't work in your case, and it is rather hard to troubleshoot from a distance.

If you follow [this guide](https://www.howtoforge.com/using-old-debian-versions-in-your-sources.list) you can get apt working again for Debian Jessie and simply do `sudo apt install libogg-dev` or even `sudo apt install flac`. I presume you have your reasons for not upgrading, if you don't, [consider upgrading](https://www.howtoforge.com/tutorial/how-to-upgrade-debian-8-jessie-to-9-stretch/)

**Comment by seamusdemora** [comment]
OK - thanks for the effort. 

It's not `armhf debian`, but I suspect that `Raspbian` (Raspberry Pi's OS) is a "close relative". I do appreciate [the guide](https://www.howtoforge.com/using-old-debian-versions-in-your-sources.list) you referenced, but the [Raspbian archives](https://archive.raspbian.org/raspbian/dists/) only go back as far as `stretch` (oldoldstable). 

Perhaps this method of building and installing has fallen into some disuse or disrepair? 

If it were my RPi, I would upgrade it, but I'm trying to help someone who's even less experienced than myself.  :)   They're reluctant to upgrade for reasons of their own.  

Also; I've followed your suggestion & installed the armhf debian versions of lobogg & libogg-dev using `dpkg-i`. They seemed to install just fine, but another run at `./configure` for `flac` failed in the same way as before. 

FWIW, I never installed XMMS as I assumed another player could be used. Now I wonder if there's a dependency between XMMS & libogg?? Not to worry - I know you've got better things to do, so please feel free to close this issue at your convenience.
