### ISSUE TITLE
[Customize] Requirements for compiling decoder only library

### ISSUE THREAD

**Issue by Demonese** [xiph/flac#374]
The encoding function is not necessary in common usage scenarios.
I manually disabled the encoder related source files in my own project, hoping that cmake option can provide a more convenient switch.
![image](https://user-images.githubusercontent.com/57629614/173117349-cb405d7c-9bc5-44c7-8563-60516a4820c7.png)

**Comment by ktmf01** [comment]
Did this create a properly working library for you? One difficulty in implementing this is that the test suite won't work when the encoder is disabled.

**Comment by Demonese** [comment]
> Did this create a properly working library for you? One difficulty in implementing this is that the test suite won't work when the encoder is disabled.

It still decodes flac audio files for me and lets me play music happily. 

Automated testing is really a problem, maybe automated testing can remove the encoder test part.

**Comment by ktmf01** [comment]
No, that is not possible. To test the decoder, one needs file to decode. The test suite generates these with the encoder part.

Anyway, I'll keep this in as a feature request. It probably won't happen anytime soon.

**Comment by ktmf01** [comment]
Note that there is no dependency on AVX, libFLAC has runtime selection of AVX functions when the CPU supports them WITH_AVX=OFF completely disabled AVX, but WITH_AVX=ON does NOT require CPUs to have AVX.

**Comment by Demonese** [comment]
> libFLAC has runtime selection of AVX functions

Thanks for your answer! I should have noticed this detail.
