### ISSUE TITLE
FLAC encoder adds spurious WAVEFORMATEXTENSIBLE_CHANNEL_MASK comment to non-WFE files

### ISSUE THREAD

**Issue by gdtrfb55** [xiph/flac#376]
I encountered this issue while encoding a set of WAVE files with mixed bit depths. In my case, it was a group of fifteen alphabetically-sorted WAVE files, all of which were 2-16-44100, except for a single 2-24-48000 file in the sixth position. I encoded the files using a simple ```flac *.wav``` command. Much to my surprise, every 2-16-44100 file processed _after_ the 2-24-48000 file had a spurious channel mask comment in it. Curiously, despite the channel mask comments, when the files containing the spurious comments were extracted back to WAVE, the format codes for the extracted WAVE files were ```0x0001```, not ```0xfffe```. So, the issue, whatever it is, seems to be related only to the insertion of the channel mask comment.

As a test, I renamed the 2-24-48000 file so that it would be processed first by ```flac *.wav```. As expected, this caused a channel mask comment to be generated for _every_ subsequent file.

This did not occur when I encoded each file separately, i.e., ```flac 01.wav```, ```flac 02.wav```, etc.

My guess is that some flag relating to the insertion of the channel mask comment isn't getting cleared between loops of the code that processes command-line arguments.

If you need additional information, just ask.

Thanks!

**Comment by ktmf01** [comment]
With which version of FLAC did you try this?

**Comment by gdtrfb55** [comment]
Forgot to mention that, didn’t I?

1.3.4, and it’s the first time I encountered the problem. Earlier versions
didn’t exhibit this anomalous behavior.

**Comment by gdtrfb55** [comment]
More accurately, 1.3.3 didn’t exhibit the problem. Versions before that
didn’t generate channel mask comments.

**Comment by ktmf01** [comment]
Are you sure about that? I just tried to bisect this and it seems this issue was already present in FLAC 1.2.1 (i.e. for 15 years already) Also, [according to the changelog](https://xiph.org/flac/changelog.html), mask comments were already written by FLAC 1.1.3

**Comment by ktmf01** [comment]
@gdtrfb55 If you are familiar with building FLAC from source, maybe you want to give the solution in #377 a try? Otherwise, I will consider it fixed with that PR, I was able to reproduce the problem and and my end #377 fixes it.

**Comment by gdtrfb55** [comment]
No worries. Patched clean against 1.3.4 release, and worked as expected
with respect to file sets containing mixed bit depths.

I believe this issue is closed.

Thanks, Martijn, for your prompt reply and fix!

**Comment by gdtrfb55** [comment]
The fix should patch clean against the 1.3.4 release code, correct?

**Comment by ktmf01** [comment]
You said yourself that it did, I haven't checked. Why do you ask?
