### ISSUE TITLE
"modified time" attribute not updated when overwriting files

### ISSUE THREAD

**Issue by vlakoff** [xiph/flac#39]
In a nutshell, I am reencoding files like so: `FOR %a IN (*.flac) DO flac -f --best "%a"`. This allows me to apply stronger compression settings, update the encoder, etc.

But I just noticed the "modified time" attribute is not updated (at least on Windows). This is problematic because e.g. most backup softwares use this attribute to determine what file have been modified.

**Comment by vlakoff** [comment]
To narrow it better, the attribute is not updated in all cases of overwriting an existing file,
e.g. `flac -f foobar.wav` (foobar.flac already existing).

**Comment by erikd** [comment]
When encoding to FLAC, the encoded file will get the same date stamp as the source file. This is a feature.

**Comment by lvqcl** [comment]
There's an option --no-preserve-modtime that was added in flac 1.3.0.

**Comment by vlakoff** [comment]
Mmmm, I disagree about the feature, the file *is* modified. But I guess BC also has to be considered.

Thank you @lvqcl for pointing out this option, this will achieve the desired result.

**Comment by vlakoff** [comment]
Any chance to consider disabling this behaviour in future versions?
i.e. applying proper modification timestamp, and adding an option `-preserve-modtime` for people who would want the feature.

I'm regularly shocked seeing newly created/modified files with old timestamps.
This is inconsistent with the expected behavior, and what all other programs do…
