### ISSUE TITLE
Debug builds built on Apple Silicon fail 24 bit predictor overflow check test

### ISSUE THREAD

**Issue by kode54** [xiph/flac#393]
Debug builds for aarch64 built on macOS targeting Apple Silicon fail to decode test file 63 in this set:

https://github.com/ietf-wg-cellar/flac-test-files

Release builds work just fine.

This affects current master (1.3.3-235-g772efde6) and also 1.3.4 release.

**Comment by ktmf01** [comment]
The problem is here:
https://github.com/xiph/flac/blob/1151c93e992bb8c7c6394e04aa880d711c531c7f/src/libFLAC/lpc.c#L1073

This needs to be
```
*(data++) = (FLAC__int32) (*(r++) + (sum >> lp_quantization));
```
Like the unrolled variant. Would you be able to test this fix?

**Comment by kode54** [comment]
It still spills this:

```
FLAC__lpc_restore_signal_wide: OVERFLOW, i=1373, sum=2208398161
FLAC__lpc_restore_signal_wide: OVERFLOW, i=0, sum=-3021934098
FLAC__lpc_restore_signal_wide: OVERFLOW, i=2714, sum=-2236475873
FLAC__lpc_restore_signal_wide: OVERFLOW, i=1335, sum=2237003072
FLAC__lpc_restore_signal_wide: OVERFLOW, i=4054, sum=-2207579620
FLAC__lpc_restore_signal_wide: OVERFLOW, i=2677, sum=2198875272
FLAC__lpc_restore_signal_wide: OVERFLOW, i=1296, sum=-2197219612
FLAC__lpc_restore_signal_wide: OVERFLOW, i=4018, sum=-2223688799
FLAC__lpc_restore_signal_wide: OVERFLOW, i=2635, sum=2298077876
FLAC__lpc_restore_signal_wide: OVERFLOW, i=1259, sum=2217551802
FLAC__lpc_restore_signal_wide: OVERFLOW, i=1220, sum=-2169435757
FLAC__lpc_restore_signal_wide: OVERFLOW, i=3937, sum=2180580338
FLAC__lpc_restore_signal_wide: OVERFLOW, i=2560, sum=-2231111067
FLAC__lpc_restore_signal_wide: OVERFLOW, i=3899, sum=2240648929
FLAC__lpc_restore_signal_wide: OVERFLOW, i=2522, sum=-2182584749
63 - predictor overflow check, 24-bit.flac: ERROR, MD5 signature mismatch
```

And the code appears to completely break out of the processing loop if the overflow check fails.

**Comment by ktmf01** [comment]
Okay, this is rather embarrassing. It seems the testbench file is invalid. It relies on wrap-around of the calculated sample value to decode properly. When I created the file I was under the impression no overflow had happened, but it seems I was wrong. I need to take a closer look though. Thanks for pointing this out.

**Comment by ktmf01** [comment]
There is a new version of file 63 in a PR that can be found here: https://github.com/ietf-wg-cellar/flac-test-files/pull/4 This should fix the issue, it does at my end at least.
