### ISSUE TITLE
"ERROR: got partial sample" with flac command line

### ISSUE THREAD

**Issue by dardoor** [xiph/flac#396]
I found some wav files which produce this error when I convert them to flac with flac.exe command line (1.3.4 and some older versions).

Foobar2000 converts these wav files to flac without errors and the resulting flac and wav are the same when I compare them.
Whereas if I use flac.exe from the command line, the resulting flac has a different length from the wav and opening that flac file causes one of my apps to crash.

(These wavs also contain loop points, which I want to keep, using --keep-foreign-metadata, but the error happens whether or not I use that command.)

Here's an example problematic wav: [file.zip](https://github.com/xiph/flac/files/9121939/file.zip)

**Comment by ktmf01** [comment]
Using `ffmpeg` on the sample also yield an error

```
[pcm_s24le @ 0x55833aad80] Invalid PCM packet, data has size 1 but at least a size of 3 was expected
Error while decoding stream #0:0: Invalid data found when processing input
```

So it seems this wav file is invalid. The output of `sndfile-info` is
```
File : file.wav
Length : 1791284
RIFF : 1791276
WAVE
JUNK : 28
fmt  : 18
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 1
  Sample Rate   : 48000
  Block Align   : 3
  Bit Width     : 24
  Bytes/sec     : 144000
data : 1790890
cue  : 52
  Count : 2
   Cue ID :  0  Pos :     0  Chunk : data  Chk Start : 0  Blk Start : 0  Offset :     0
   Cue ID :  1  Pos : 589029  Chunk : data  Chk Start : 0  Blk Start : 1767087  Offset : 589029
LIST : 108
  adtl
    ltxt : 42
smpl : 60
  Manufacturer : 6E656AD5
  Product      : 32758
  Period       : 20833 nsec
  Midi Note    : 69
  Pitch Fract. : 0
  SMPTE Format : 500
  SMPTE Offset : 40:44:90 64
  Loop Count   : 1
    Cue ID :  2  Type :  0  Start : 62615  End : 548759  Fraction :     0  Count :     0
  Sampler Data : 3316210593 (should be 0)
JUNK : 28
acid : 24
  Flags     : 0x0000 (Loop,RootNoteInvalid,StretchOff,RAMBased,??Off)
  Root note : 0x0
  ????      : 0x0000
  ????      : 0.000000
  Beats     : 0
  Meter     : 4/4
  Tempo     : 120.000000
End

----------------------------------------
Sample Rate : 48000
Frames      : 596963
Channels    : 1
Format      : 0x00010003
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:12.437
Signal Max  : 50531 (-44.40 dB)
```

The data chunk size is 1790890, and this is not divisible by 3, there is a remainder of 1 byte. This agrees with the `ffmpeg` warning.

So, it seems the WAV file is invalid. I'm sorry, FLAC won't process WAV files if it is not 100% sure it is read correctly, to remain lossless.

**Comment by dardoor** [comment]
Yeah, the wav file is broken.
But the fact that foobar2000 converts it without errors and outputs a valid flac file made me wonder if it's perhaps possible to do it with the command line too. Foobar2000 actually uses the same flac.exe, with these parameters: `-s --ignore-chunk-sizes -8 - -o %d`. (But IDK how exactly it all works, internally...)

I would just use foobar2000 for the conversion, but it doesn't work with --keep-foreign-metadata, so I can't.
