### ISSUE TITLE
Option to disable intro text in console output

### ISSUE THREAD

**Issue by vlakoff** [xiph/flac#40]
The following text is outputted at the beginning of each and every processing:

> flac 1.3.2
> Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
> flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
> welcome to redistribute it under certain conditions.  Type `flac' for details.

When working in batches, this text makes visually parsing the console output much more difficult.

Currently there is no way to disable this text, I think an option should be added to allow disabling it.

**Comment by erikd** [comment]
Have you tried the `--silent` command line option?

**Comment by vlakoff** [comment]
Yes, but it also hides the result messages (e.g. "File.flac: done", "File.wav: Verify OK, wrote 9689801 bytes, ratio=0,603")

To illustrate, it would be helpful to be able to avoid this output:
```
flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

01 - Track01.wav: Verify OK, wrote 36560678 bytes, ratio=0,679

flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

02 - Track02.wav: Verify OK, wrote 28492905 bytes, ratio=0,734

flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

03 - Track03.wav: Verify OK, wrote 52414381 bytes, ratio=0,581

flac 1.3.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2016  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

04 - Track04.wav: Verify OK, wrote 27267980 bytes, ratio=0,736
```

... to have this one instead:

```
01 - Track01.wav: Verify OK, wrote 36560678 bytes, ratio=0,679

02 - Track02.wav: Verify OK, wrote 28492905 bytes, ratio=0,734

03 - Track03.wav: Verify OK, wrote 52414381 bytes, ratio=0,581

04 - Track04.wav: Verify OK, wrote 27267980 bytes, ratio=0,736
```

Here it's a short example, but it gets significantly heavier when handling dozens of files.

**Comment by erikd** [comment]
I'm reluctant to add yet another command line flag, especially when this is so easy to solve with tools like `sed`.

**Comment by vlakoff** [comment]
Thanks for the fast reply, as always.

I just compared with the output of other encoders (lame, vorbis, musepack), and they are arguably more verbose. Though, much of the verbosity is technical info about the encoding, not "readme" stuff. It's interesting to note how the encoders have completely different console outputs.

I understand you're not willing to add another option. And considering there is no "perfect" output that would please everyone, I suppose we can just close this.

**Comment by vlakoff** [comment]
That's pretty neat :)

I was afraid I couldn't use this solution, as I'm actually using a batch file with a `FOR` loop:

    @FOR %%a IN (*.flac) DO @flac -d "%%a"

… but I found out the following:

    @flac -d *.flac

Thanks for putting me on the right track :)

**Comment by vlakoff** [comment]
Just to stress it out, the same trick obviously works for encoding/re-encoding commands :)
