### ISSUE TITLE
new release soon?

### ISSUE THREAD

**Issue by moralground** [xiph/flac#406]
Looking at the commits since 1.3.4, quite a few memory leaks, fuzzing bugs, and null pointer dereferences have been fixed. Would it be possible to cut a 1.3.5 release soon with all these fixes so downstreams don't have to keep up with lots of backports?

**Comment by ktmf01** [comment]
I hope to put out a release in a month or two.

**Comment by hyder365** [comment]
> I hope to put out a release in a month or two.

Well it's been about 1 month. Any chance of it now?

**Comment by ktmf01** [comment]
I don't have enough free time on my hands to expedite this.
