### ISSUE TITLE
Unsupported file format?

### ISSUE THREAD

**Issue by eblanca** [xiph/flac#42]
I'm trying to encode a wav file, which soxi reports to be a 32 bit floating point pcm (2 channels, 44100 Hz), and flac aborts encoding.

> ERROR: unsupported format type 3

So, is floating point in wave not supported?

[flac built using latest source code from master branch, btw]

**Comment by erikd** [comment]
Yes, that seems to be the case.

**Comment by eblanca** [comment]
Does the compression algorithm support 16 bit only ?

**Comment by erikd** [comment]
It supports 8, 16, 24 and 32 bit PCM, but not floating point.

**Comment by eblanca** [comment]
Thank you.
