### ISSUE TITLE
`metaflac --import-picture-from` for unsupported formats

### ISSUE THREAD

**Issue by eddiezato** [xiph/flac#423]
I'm trying to use `metaflac` to import an album cover in `jxl` format into a `flac` image. I specify dimensions, depth and colors, but `metaflac` still can't parse the file even though it shouldn't try to do it according to the documentation.

```
PS > $info = magick identify -verbose -format "%Gx%z/%k" c.jxl
PS > metaflac --import-picture-from="3|image/jxl||$info|c.jxl" c.flac
c.flac: ERROR: while parsing picture specification "3|image/jxl||1080x1080x8/192981|c.jxl": invalid picture specification: can't parse resolution/color part
```

https://xiph.org/flac/documentation_tools_flac.html#flac_options_picture
> When manually specified, it is not checked against the file for accuracy.

**Comment by ktmf01** [comment]
I'm pretty sure the problem is that the colors part is only supposed to be used for indexed pictures like GIF.

What happens if you try to embed with  `metaflac --import-picture-from="3|image/jxl||1080x1080x24/0|c.jxl" c.flac`

**Comment by eddiezato** [comment]
@ktmf01 thanks, it works!
