### ISSUE TITLE
Float32

### ISSUE THREAD

**Issue by StephenPerson** [xiph/flac#427]
There is now support for 32-bit integer samples in v1.4.0

Why not to add floating point 32 at the same time now when encoders and decoders will need an update anyway ?

Set FLAC header bits to e.g. 28, presentate 32-bit float in an 32-bit integer format that works best for compression  and use existing encoding and decoding methods

You

**Comment by ktmf01** [comment]
That would not work. If you treat floats as int in FLAC compression will be harmed to the point there is no compression at all.

**Comment by ktmf01** [comment]
Support for float samples is not planned. If you need this functionality now, consider using [WavPack](https://www.wavpack.com/)
