### ISSUE TITLE
md5 not set when writing to stdout

### ISSUE THREAD

**Issue by mahkitah** [xiph/flac#428]
When writing to stdout, the resulting flacs do not have the md5 checksum set in the streaminfo.

tested with flac 1.3.4 on Windows and flac 1.3.2 on Raspbian

**Comment by ktmf01** [comment]
The MD5 sum in FLAC files is written at the very beginning of the file. However, it known only when all blocks have been encoded. When writing to stdout, it is not possible to rewind the FLAC file to write the MD5sum at the beginning. This is something that cannot be solved.

Besides MD5 sum, there are other parameters not written, like min and max blocksize.

**Comment by mahkitah** [comment]
I thought that since the md5 is calculated from the raw audio not from the encoded blocks, it would be possible to calculate the md5 at the beginning of the encoding process. But that seems not to be the case.

Anyhow, it would be nice if this could be added to the warning about the seekpoints not being written.

**Comment by ktmf01** [comment]
It could be possible, but that would mean reading the entire file twice, with the first pass only to calculate the md5. This is not implemented as such.

I'll keep this open for the warning. It won't make it in the next release however.
