### ISSUE TITLE
Incorrect version for 1.3.4 win64 binary

### ISSUE THREAD

**Issue by moleonacid** [xiph/flac#430]
Hi All,

Given the level of detail that audiophiles go into with everything I can hardly believe I am right, but I'm decently sure I am.  The Windows zip for 1.3.4 is [here](https://ftp.osuosl.org/pub/xiph/releases/flac/flac-1.3.4-win.zip).  The win32 binary is correctly showing its self as 1.3.4, but the win64 binary is showing as 1.3.2

Hopefully an easy fix, and thanks for your continued efforts in making something as awesome as FLAC available to us all.

**Comment by ktmf01** [comment]
I can't seem to reproduce this. Please state exactly what you did and where 1.3.2 was shown.

**Comment by moleonacid** [comment]
Thanks for getting back to me.  I noticed it when upgrading the flac.exe used by EAC didn't cause the metadata in the FLACs it was outputting to show the newer version.  I thought it might just be an environment thing, so I ran the following at the command prompt:

C:\Users\moleo\Desktop\flac-1.3.4-win\win64>"C:\Users\moleo\Desktop\flac-1.3.4-win\win64\flac.exe"

which gives me:

flac - Command-line FLAC encoder/decoder version 1.3.2
Copyright (C) 2000-2009  Josh Coalson
Copyright (C) 2011-2016  Xiph.Org Foundation

**Comment by ktmf01** [comment]
Are you sure you didn't accidentally swapped files at some point? Have you tried removing that directory, downloading and extracting the file again, making sure you don't use anything that is already on your computer?

**Comment by moleonacid** [comment]
How horrendously embarrassing!  I have of course moved the binary the wrong way at some point.  Thank you for patiently doing my thinking for me!
