### ISSUE TITLE
Unit tests using CMake fails on FreeBSD 13

### ISSUE THREAD

**Issue by diizzyy** [xiph/flac#437]
Tests libFLAC, libFLAC++ and flac fails
This is also seems incorrect as amd64/x86-64 is little endian, ```++ libFLAC unit test: endswap (big endian host)``` and GNU Autotools gets this right.

The specific test that libFLAC units fails passes using GNU Autotools

I've attached a log of tests (I've disabled streams as it takes a long time to run)
[flac-ctest-log.zip](https://github.com/xiph/flac/files/9545983/flac-ctest-log.zip)

OS: FreeBSD 13.1-STABLE (amd64)
FLAC: 1.4.0 Release
CMake: 3.23.3

**Comment by ktmf01** [comment]
Could you also supply a log of the CMake configuration? Furthermore, what happens if you build for release instead of debug? There is an issue with running the tests on a debug buil, see #436

**Comment by diizzyy** [comment]
Hi,

Build type is Release,

Arguments passed to CMake:

```-DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -march=ivybridge  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -march=ivybridge  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -march=ivybridge  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -march=ivybridge -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -DLIBICONV_PLUG "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -march=ivybridge -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -DLIBICONV_PLUG "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -march=ivybridge -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -DLIBICONV_PLUG "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -GNinja -DICONV_INCLUDE_DIR=/usr/include  -DICONV_LIBRARIES=/usr/lib/libc.so  -DICONV_LIBRARY=/usr/lib/libc.so  -DLIBICONV_INCLUDE_DIR=/usr/include  -DLIBICONV_LIBRARIES=/usr/lib/libc.so  -DLIBICONV_LIBRARY=/usr/lib/libc.so``` 

Attached build log and CMake cache file
[cmake-flac.zip](https://github.com/xiph/flac/files/9548952/cmake-flac.zip)

**Comment by ktmf01** [comment]
That doesn't add up. The test log you supplied is from a debug build: the output contains assert failures and CPU info, that is only done for a debug build.

I'm unfamiliar with the way you're using CMake. Can you elaborate? It seems to be wrapped by something, automating downloading, checksumming, configuring etc.

**Comment by diizzyy** [comment]
Yes, you're on to something...
It does seem like you need to define it manually https://github.com/NASA-SW-VnV/ikos/issues/36

**Comment by ktmf01** [comment]
That doesn't make any sense.

CMake sets a default for the release flags, which includes NDEBUG. If someones has a need to overwrite that default, why should FLAC override that again? Perhaps someone has a good reason to not set NDEBUG in a Release target. That I can't think of any good use doesn't mean there isn't.

It seems to me the user overriding CMake defaults should know what they're doing. Could you perhaps take this up with FreeBSD ports? Perhaps I'm missing something.

**Comment by diizzyy** [comment]
To be fair FLAC already does this https://github.com/xiph/flac/blob/master/CMakeLists.txt#L87 but I agree with Yuri that this should be supplied by the project but there's need to pursue it any further if you're strongly against it.

**Comment by ktmf01** [comment]
You're right, it should probably be set in such a way that it can be overridden, just like the autotools build system. I'll see what I can do.

**Comment by diizzyy** [comment]
fwiw, doing some quick test runs on my box shows that -O2 and LTO (-flto) perfoms marginally better than current default settings (-O3 -funroll-loops) on my i7-3770 using llvm/clang 14.0.5

**Comment by ktmf01** [comment]
I've prepared a change in the vein of this discussion in #442. Feel free to comment.
