### ISSUE TITLE
Conflicting types in source and header files

### ISSUE THREAD

**Issue by razed11** [xiph/flac#44]
I posted this last night to the mailing list. Reposting here:

I'd like to compress a 32 kHz 16-bit mono using an STM32F4 microcontroller (RTOS not Linux). My plan is to capture from 500-1000 ms of data, compress, and send the result over a UART.

I have the arm-none-eabi tools installed on MacOS. I used homebrew to install autoconf, automake, and libtool. autogen.sh succeeded and I was able to create my makefiles using the following:

```
./configure --build=x86_64-apple-darwin16.7.0 --host=arm-none-eabi --prefix=$PWD/export CFLAGS="-O3 -mthumb -mcpu=cortex-m4 -lc -lrdimon -specs=rdimon.specs" --disable-cpplibs --disable-ogg --disable-oggtest --disable-examples --disable-xmms-plugin
```

```
  Configuration summary :

    FLAC version : ........................ 1.3.2

    Host CPU : ............................ arm
    Host Vendor : ......................... none
    Host OS : ............................. eabi

    Compiler is GCC : ..................... yes
    GCC version : ......................... 5.4.1
    Compiler is Clang : ................... no
    SSE optimizations : ................... yes
    Asm optimizations : ................... no
    Ogg/FLAC support : .................... no
```

I'm getting some errors around type mismatches between the declarations and definitions for example:

```
grabbag/cuesheet.c:32:10: error: conflicting types for 'grabbag__cuesheet_msf_to_frame'
 uint32_t grabbag__cuesheet_msf_to_frame(uint32_t minutes, uint32_t seconds, uint32_t frames)
          ^
In file included from ../../include/share/grabbag.h:24:0,
                 from grabbag/cuesheet.c:29:
../../include/share/grabbag/cuesheet.h:32:10: note: previous declaration of 'grabbag__cuesheet_msf_to_frame' was here
 unsigned grabbag__cuesheet_msf_to_frame(unsigned minutes, unsigned seconds, unsigned frames);
```

I can see that the variables in the header are not declared using the <stdint.h> values.

More broadly though: Assuming I can sort out these errors, am I on the right track/ My experiments have shown that a compression level of zero will meet my needs and I have read that encoding is faster than real-time. Once I have the library built I plan to measure things. But I'm seeing calls to fprintf etc that I don't need. If I just want encodying functions but not the general purpose flac tool is there any advice as to how to pare this back further so I'm only building what I need. I'm not too concerned about library size as the linker should just pull in what is needed. It's more that I would like fewer things to debug in the build.

Is it possible to encode on-the-fly? I have 192 KB of RAM. It'd be nice if I could compress straight to a buffer.

**Comment by razed11** [comment]
I used the following combination of ack/grep/sed to replace `unsigned` in the files with `uint32_t`:

`grep -l "\sunsigned\s" $(ack --cc -f) | xargs sed -e 's/[[:<:]]unsigned[[:>:]]/uint32_t/g' -i .original`

**Comment by erikd** [comment]
What you see is a result of FLAC starting development in the late 1990s when C99 compilers were still not widely available, resulting in the use of `unsigned`. There has been some work to modernize the internals resulting in the internals using `uint32_t`. The difficulty is at the API level. The API need to remain unchanged so that ABI compatibility can be maintained.

Since this particular instance is for an internal library (grabbag), its probably safe to change it to use `uint32_t` as you suggest. This however cannot just be done with grep/ack/sed like you suggest, because only internal interfaces can be changed.

**Comment by Oreo639** [comment]
I can also reproduce this using devkitARM when compiling for a 3ds.
This doesn't just occur in grabbag.
Patching it in grabbag continues with this
```
CC       grabbag/seektable.lo
  CC       grabbag/snprintf.lo
  CCLD     grabbag/libgrabbag.la
  CC       utf8/charset.lo
  CC       utf8/iconvert.lo
  CC       utf8/utf8.lo
  CCLD     utf8/libutf8.la
  CC       replaygain_analysis/replaygain_analysis.lo
  CCLD     replaygain_analysis/libreplaygain_analysis.la
  CC       replaygain_synthesis/libreplaygain_synthesis_la-replaygain_synthesis.lo
replaygain_synthesis/replaygain_synthesis.c:301:8: error: conflicting types for 'FLAC__replaygain_synthesis__apply_gain'
  301 | size_t FLAC__replaygain_synthesis__apply_gain(FLAC__byte *data_out, FLAC__bool little_endian_data_out, FLAC__bool uint32_t_data_out, const FLAC__int32 * const input[], uint32_t wide_samples, uint32_t channels, const uint32_t source_bps, const uint32_t target_bps, const double scale, const FLAC__bool hard_limit, FLAC__bool do_dithering, DitherContext *dither_context)
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from replaygain_synthesis/replaygain_synthesis.c:45:
../../include/share/replaygain_synthesis.h:50:8: note: previous declaration of 'FLAC__replaygain_synthesis__apply_gain' was here
   50 | size_t FLAC__replaygain_synthesis__apply_gain(FLAC__byte *data_out, FLAC__bool little_endian_data_out, FLAC__bool unsigned_data_out, const FLAC__int32 * const input[], unsigned wide_samples, unsigned channels, const unsigned source_bps, const unsigned target_bps, const double scale, const FLAC__bool hard_limit, FLAC__bool do_dithering, DitherContext *dither_context);
```

**Comment by neheb** [comment]
What's the difference between unsigned and uint32_t? unsigned defaults to an int, no?

**Comment by erikd** [comment]
Well, `unsigned` is shorthand for `unsigned int`, but not all C(( compliant compilers have 32 bit `int` and therefore `unsigned int` ins not always synonymous with `uint32_t`.

**Comment by erikd** [comment]
@Oreo639 Would you be able to turn that patch into a PR? PRs are much easier to keep track of that patches attached to issues.

**Comment by Oreo639** [comment]
Sure.
