### ISSUE TITLE
Version string gets botched (by git) on release archives using CMake

### ISSUE THREAD

**Issue by diizzyy** [xiph/flac#443]
There should be a toggle or possibly check for .git directory in source dir as build script assumes that as long as your host has git the sources of flac is from a git repo

https://github.com/xiph/flac/blob/master/CMakeLists.txt#L54

**Comment by ktmf01** [comment]
It works fine at my end. Please show such a botched version string, that might narrow things down a little further.

**Comment by alexey-lysiuk** [comment]
I guess, it's about building from sources copied into another Git repository. Commit hash and tag will be fetched from that repository instead of FLAC's one.

**Comment by diizzyy** [comment]
Yes, @alexey-lysiuk you're correct this only occurs within another git repo
I forgot to mention that

**Comment by ktmf01** [comment]
Perhaps adding ` --git-dir=.git` to all three commands is sufficient to prevent this from happening? That seems a rather simple way to make sure git doesn't try to search.
