### ISSUE TITLE
Documentation for FLAC__MAX_SAMPLE_RATE  is no longer accurate

### ISSUE THREAD

**Issue by sagamusix** [xiph/flac#448]
As of FLAC 1.4.0, `FLAC__MAX_SAMPLE_RATE ` is 1048575. But the docstring still says:

```
/** The maximum sample rate permitted by the format.  The value is
 *  ((2 ^ 16) - 1) * 10; see <A HREF="../format.html">FLAC format</A>
 *  as to why.
 */
```

Furthermore, I think the linked format.html also needs to be updated, at least the copy on xiph.org still reads:

```
Sample rate in Hz. Though 20 bits are available, the maximum sample rate is limited by the structure of frame headers to 655350Hz. Also, a value of 0 is invalid. 
```

**Comment by ktmf01** [comment]
Thanks for reporting, I'll change that bit in the headers.

The format.html page won't be updated anymore. It is maintained as a 'historic reference', but as stated at the very top of the document, it is replaced by the current IETF draft here: https://datatracker.ietf.org/doc/draft-ietf-cellar-flac/
