### ISSUE TITLE
CMake build should have switches for CPU optimization

### ISSUE THREAD

**Issue by diizzyy** [xiph/flac#449]
Please correct me if I'm wrong but from what I can gather flac doesn't support runtime detection of CPU instructions which leads into issue if you're packaging. There should be corresponding switches available for CMake as when using Autotools (SSE, AVX/AVX2, altivec, vsx) to avoid issues with incompatible/broken binaries.

Edit: Some functionality seems to be in https://github.com/xiph/flac/blob/master/src/libFLAC/CMakeLists.txt

**Comment by ktmf01** [comment]
FLAC does runtime detection of SSE2, SSSE3, SSE4.1, AVX2 and FMA and VSX. Additionally, compilers are instructed to output SSE2 by default. 

In CMake, WITH_SSE sets that compiler instruction. This is marked, see

https://github.com/xiph/flac/blob/229f4f45df72ac1fc8a2f7749043223d745c8e27/src/libFLAC/CMakeLists.txt#L59

In CMake, WITH_AVX turns off compilation of AVX2 and FMA enhancements

https://github.com/xiph/flac/blob/229f4f45df72ac1fc8a2f7749043223d745c8e27/src/libFLAC/CMakeLists.txt#L22

Note that runtime detection is specifically mentioned

**Comment by diizzyy** [comment]
Great, I was a bit unsure about AVX/AVX2 if that meant globally or just between those two.
