### ISSUE TITLE
Issue when cross compiling with flac-1.4.1

### ISSUE THREAD

**Issue by heitbaum** [xiph/flac#463]
Two of the recent commits do not allow for cross compilation:

```
checking for /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/flac-1.4.1/doc/FLAC.tag... configure: error: cannot check for file existence when cross compiling
checking for /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/flac-1.4.1/man/flac.1... configure: error: cannot check for file existence when cross compiling
```

Reverting:
- https://github.com/xiph/flac/commit/b175971f8087d38c003bac67bbd2c535e807d415
- https://github.com/xiph/flac/commit/71c3c55dba5ce201c365558ede00caf99d145ea8

allowed the build to succeed.

**Comment by ktmf01** [comment]
So much for using native autoconf macro's instead of simple `test`. Didn't notice that part of the documentation about cross-compiling. I'll probably fix this by replacing AC_CHECK_FILE with `test`

**Comment by heitbaum** [comment]
> So much for using native autoconf macro's instead of simple `test`. Didn't notice that part of the documentation about cross-compiling. I'll probably fix this by replacing AC_CHECK_FILE with `test`

Thanks. Happy to test.
