### ISSUE TITLE
Feature request: 32 bit floating point support

### ISSUE THREAD

**Issue by mstgrv** [xiph/flac#468]
I was excited to see FLAC 1.4.0 included 32 bit PCM support, but disappointed that this is fixed point only. 32 bit floating point support would be an amazing addition to FLAC - the use case is mainly for DAWs and other audio apps, where 32 bit floating point files are very often created in the course of working on projects. The majority of DAWs only support uncompressed WAV / AIFF at this resolution. 

32 bit floating point support in FLAC would allow DAWs to use less space when producing these high-resolution files, and would allow existing projects which use 32 bit floating point WAV / AIFF files to be archived more space-efficiently.

**Comment by ktmf01** [comment]
This is not possible without changing the FLAC format, breaking backward compatibility. For storing float32 data losslessly, I recommend using [WavPack](https://github.com/dbry/WavPack/)
