### ISSUE TITLE
Static build for Windows

### ISSUE THREAD

**Issue by 237dmitry** [xiph/flac#470]
Build without `LibFlac.dll` and `LibFlac++.dll`

For working symlinked `flac.exe` and `metaflac.exe` from custom directory in `$env:PATH`.

**Comment by ktmf01** [comment]
I don't understand your issue. Please explain what your problem is.

**Comment by 237dmitry** [comment]
> Please explain what your problem is

`flac.exe ` and `metaflac.exe ` do not work if they are not in the directory where `libFLAC*.dll` are. I don't want to make a garbage in the PATH - too large a list of directories or too many auxiliary files in the directory where symbolic links to executable files are located.

It would be better to build executables without external libraries.

![ss-20220928100743](https://user-images.githubusercontent.com/78153320/192711999-b5ddfb92-2ac4-4192-9956-93e054b7c915.png)

**Comment by 237dmitry** [comment]
> Then also copy libFLAC.dll to that directory?

I found build without extra libraries. [flac-1.4.1-x64.zip](https://codecsdownload.com/download_70e0e175f02f24a6565c1f7210995bea/flac-1.4.1-x64.zip)

**Comment by vrubleg** [comment]
If somebody comes here from Google as I did, fresh static builds without external libraries are available from here: https://www.rarewares.org/lossless.php
