### ISSUE TITLE
Clarify `--replay-gain` requirements in man pages and help prints

### ISSUE THREAD

**Issue by markgras** [xiph/flac#495]
I find the man pages and help text for the `flac` and `metaflac` commands to be both confusing and misleading when it comes to `--replay-gain` options. The `flac` command's man page states the following about its `--replay-gain` encoding option:
> "Only mono and stereo files are allowed, and the sample rate must be one of 8, 11.025, 12, 16, 22.05, 24, 32, 44.1, or 48 kHz."

The `metaflac` command's man page says this about its `--replay-gain` shorthand operation:
> All FLAC files specified must have the same resolution, sample rate, and number of channels. The sample rate must be one of 8, 11.025, 12, 16, 18.9, 22.05, 24, 28, 32, 37.8, 44.1, 48, 56, 64, 88.2, 96, 112, 128, 144, 176.4, or 192kHz.

`flac -H` states:
> All input files must have the same resolution, sample rate, and number of channels. The sample rate must be one of 8, 11.025, 12, 16, 22.05, 24, 32, 44.1, or 48 kHz.

`metaflac --help` states:
> All FLAC files specified must have the same resolution, sample rate, and number of channels. The sample rate must be one of 8, 11.025, 12, 16, 22.05, 24, 32, 44.1, or 48 kHz.

Looking through the code, it appears that both commands share the same code for checking sample rate requirements (src/share/replaygain_analysis/replaygain_analysis.c), and both have the same 1 or 2 channel requirements (though these are defined in different places). Therefore, only one of the four outputs correctly states the channel count limit, and none of them list all accepted sample rates (they all omit 36 kHz, which has its own settings in replaygain_analysis.c).

To address this issue, I believe that all of these sources should state the same channel number and sample rate restrictions. As for what to specifically state regarding sample rate restrictions, that is debatable. Any rate that is a multiple of 8, 11.025, 12, 18.9, or 28 kHz is technically acceptable. This doesn't explicitly state common sample rates like 44.1 kHz, however. Stating any rate that is a multiple of the frequencies specifically listed in replaygain_analysis.c (8, 11.025, 12, 16, 18.9, 22.05, 24, 28, 32, 36, 37.8, 44.1, and 48 kHz) avoids this problem.

Thoughts? I would happily contribute a PR for this.

**Comment by ktmf01** [comment]
Documentation is generally out-of-date, so it would indeed be great if you can find out what the current status is and update this.

**Comment by markgras** [comment]
Excellent. For posterity, I would like to identify two mistakes in what I previously said:
1) Although `flac`'s option is named `--replay-gain`, metaflac's option is actually named `--add-replay-gain`.
2) I erroneously stated, "Any rate that is a multiple of 8, 11.025, 12, 18.9, or 28 kHz is technically acceptable." This is not true. Firstly, [there is an upper sample rate cap of 655,350 Hz](https://xiph.org/flac/format.html). Secondly, I misread src/share/replaygain_analysis/replaygain_analysis.c. In actuality, any rate that is a positive _power-of-two_ multiple of 8, 11.025, 12, 16, 18.9, 22.05, 24, 28, 32, 36, 37.8, 44.1, or 48 kHz is accepted by that code. There is redundancy in this list; e.g. you could remove 16 kHz because it's equivalent to 8 kHz * 2^1. The fully-reduced list is consequently 8, 11.025, 12, 18.9, 28, and 36 kHz.

Therefore, an exhaustive list of all accepted ReplayGain sample rates is 8, 11.025, 12, 16, 18.9, 22.05, 24, 28, 32, 36, 37.8, 44.1, 48, 56, 64, 72, 75.6, 88.2, 96, 112, 128, 144, 151.2, 176.4, 192, 224, 256, 288, 302.4, 352.8, 384, 448, 512, 576, and 604.8 kHz. It's my opinion that explicitly stating each of these frequencies is more user-friendly than stating "the sample rate must be a positive power-of-two multiple of 8, 11.025, 12, 18.9, 28, or 36 kHz that is also less than or equal to 655.35 kHz". Reading a few extra characters is easier for a user than doing mental math, so I will explicitly state all frequencies.
