### ISSUE TITLE
ICC compiler warnings: conversion from 'const __int64' to 'uint32_t', possible loss of data

### ISSUE THREAD

**Issue by kitzik** [xiph/flac#50]
Intel C Compiler produces a lot of warnings about type conversion during x64 build process. Here's output log:

1>------ Rebuild All started: Project: libFLAC_static, Configuration: Release x64 ------
2>------ Rebuild All started: Project: replaygain_analysis_static, Configuration: Release x64 ------
3>------ Rebuild All started: Project: getopt_static, Configuration: Release x64 ------
4>------ Rebuild All started: Project: replaygain_synthesis_static, Configuration: Release x64 ------
4>replaygain_synthesis.c
4>replaygain_synthesis_static.vcxproj -> C:\__WORKDIR\projects\flac-master\objs\x64\Release\lib\replaygain_synthesis_static.lib
5>------ Rebuild All started: Project: utf8_static, Configuration: Release x64 ------
2>replaygain_analysis.c
5>utf8.c
2>replaygain_analysis_static.vcxproj -> C:\__WORKDIR\projects\flac-master\objs\x64\Release\lib\replaygain_analysis_static.lib
6>------ Rebuild All started: Project: win_utf8_io_static, Configuration: Release x64 ------
5>utf8_static.vcxproj -> C:\__WORKDIR\projects\flac-master\objs\x64\Release\lib\utf8_static.lib
6>win_utf8_io.c
6>win_utf8_io_static.vcxproj -> C:\__WORKDIR\projects\flac-master\objs\x64\Release\lib\win_utf8_io_static.lib
1>bitmath.c
1>bitreader.c
1>bitwriter.c
1>cpu.c
1>crc.c
1>fixed.c
1>fixed_intrin_sse2.c
1>fixed_intrin_ssse3.c
1>float.c
1>format.c
1>format.c(580): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>format.c(582): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
3>getopt.c
3>getopt1.c
1>format.c(584): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>lpc.c
3>getopt_static.vcxproj -> C:\__WORKDIR\projects\flac-master\objs\x64\Release\lib\getopt_static.lib
1>lpc_intrin_sse.c
1>lpc_intrin_sse2.c
1>lpc_intrin_sse41.c
1>md5.c
1>memory.c
1>metadata_iterators.c
1>metadata_iterators.c(579): warning C4244: 'return': conversion from 'const __int64' to 'off_t', possible loss of data
1>metadata_iterators.c(1117): warning C4244: '+=': conversion from 'const __int64' to 'uint32_t', possible loss of data
1>metadata_iterators.c(1129): warning C4244: '=': conversion from '__int64' to 'uint32_t', possible loss of data
1>metadata_iterators.c(1152): warning C4244: '-=': conversion from 'const __int64' to 'uint32_t', possible loss of data
1>metadata_iterators.c(1647): warning C4244: '=': conversion from '__int64' to 'uint32_t', possible loss of data
1>metadata_iterators.c(1652): warning C4244: '=': conversion from '__int64' to 'uint32_t', possible loss of data
1>metadata_iterators.c(1666): warning C4244: '=': conversion from 'const __int64' to 'uint32_t', possible loss of data
1>metadata_object.c
1>metadata_object.c(1127): warning C4244: '=': conversion from 'FLAC__uint64' to 'uint32_t', possible loss of data
1>ogg_decoder_aspect.c
1>ogg_encoder_aspect.c
1>Compiling...
1>ogg_helper.c
1>ogg_mapping.c
1>stream_decoder.c
1>stream_encoder.c
1>stream_encoder.c(3942): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>stream_encoder.c(3944): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>stream_encoder_framing.c
1>stream_encoder_intrin_sse2.c
1>stream_encoder_intrin_ssse3.c
1>window.c
1>windows_unicode_filenames.c
1>lpc_intrin_avx2.c
1>stream_encoder_intrin_avx2.c
1>libFLAC_static.vcxproj -> C:\__WORKDIR\projects\flac-master\objs\x64\Release\lib\libFLAC_static.lib
1>Done building project "libFLAC_static.vcxproj".
7>------ Rebuild All started: Project: grabbag_static, Configuration: Release x64 ------
7>alloc.c
7>cuesheet.c
7>file.c
7>picture.c
7>picture.c(290): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
7>picture.c(308): warning C4244: 'function': conversion from 'const __int64' to 'FLAC__uint32', possible loss of data
7>replaygain.c
7>seektable.c
7>snprintf.c
7>grabbag_static.vcxproj -> C:\__WORKDIR\projects\flac-master\objs\x64\Release\lib\grabbag_static.lib
7>Done building project "grabbag_static.vcxproj".
8>------ Rebuild All started: Project: flac, Configuration: Release x64 ------
8>analyze.c
8>decode.c
8>encode.c
8>encode.c(2859): warning #1786: function "fileno" (declared at line 2457 of "C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\stdio.h") was declared deprecated ("The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details.")
8>  	if(flac_fstat(fileno(f), &stb) == 0 && (stb.st_mode & S_IFMT) == S_IFREG)
8>  	              ^
8>
8>foreign_metadata.c
8>local_string_utils.c
8>main.c
8>main.c(2254): warning #1786: function "strdup" (declared at line 538 of "C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\string.h") was declared deprecated ("The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.")
8>  	if(0 == (ret = strdup(source)))
8>  	               ^
8>
8>utils.c
8>vorbiscomment.c
8>vorbiscomment.c(61): warning #1786: function "strdup" (declared at line 538 of "C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\ucrt\string.h") was declared deprecated ("The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.")
8>  	if(0 == (ret = strdup(source)))
8>  	               ^
8>
8>libFLAC_static.lib(format.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
8>Generating code
8>Finished generating code
8>flac.vcxproj -> C:\__WORKDIR\projects\flac-master\objs\x64\Release\bin\flac.exe
8>Done building project "flac.vcxproj".
========== Rebuild All: 8 succeeded, 0 failed, 0 skipped ==========

**Comment by erikd** [comment]
Can you please clean up that error output so that only the *actual* warnings are present.

Also, what version of ICC? Is this on 32 or 64 bit windows? Compiiing for 32 or 64 bit windows?

**Comment by kitzik** [comment]
Intel C++ 18.0 on Win10 x64 build using Release x64 config

Here are only warning messages:
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4334	'<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\format.c	580	
Warning	C4334	'<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\format.c	582	
Warning	C4334	'<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\format.c	584	
Warning	C4244	'return': conversion from 'const __int64' to 'off_t', possible loss of data	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\metadata_iterators.c	579	
Warning	C4244	'+=': conversion from 'const __int64' to 'uint32_t', possible loss of data	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\metadata_iterators.c	1117	
Warning	C4244	'=': conversion from '__int64' to 'uint32_t', possible loss of data	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\metadata_iterators.c	1129	
Warning	C4244	'-=': conversion from 'const __int64' to 'uint32_t', possible loss of data	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\metadata_iterators.c	1152	
Warning	C4244	'=': conversion from '__int64' to 'uint32_t', possible loss of data	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\metadata_iterators.c	1647	
Warning	C4244	'=': conversion from '__int64' to 'uint32_t', possible loss of data	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\metadata_iterators.c	1652	
Warning	C4244	'=': conversion from 'const __int64' to 'uint32_t', possible loss of data	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\metadata_iterators.c	1666	
Warning	C4244	'=': conversion from 'FLAC__uint64' to 'uint32_t', possible loss of data	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\metadata_object.c	1127	
Warning	C4334	'<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\stream_encoder.c	3942	
Warning	C4334	'<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)	libFLAC_static	c:\__WORKDIR\projects\flac-master\src\libFLAC\stream_encoder.c	3944	
Warning	C4334	'<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)	grabbag_static	c:\__WORKDIR\projects\flac-master\src\share\grabbag\picture.c	290	
Warning	C4244	'function': conversion from 'const __int64' to 'FLAC__uint32', possible loss of data	grabbag_static	c:\__WORKDIR\projects\flac-master\src\share\grabbag\picture.c	308

**Comment by ktmf01** [comment]
These warnings were suppressed with #321, closing this issue
