### ISSUE TITLE
Latest FLAC libs for Windows contain no/wrong version info

### ISSUE THREAD

**Issue by Eagle3386** [xiph/flac#502]
Even the libs of the latest release (1.4.2 as of today) are missing version info (please excuse my localized German UI):

`libFLAC.dll`:
![image](https://user-images.githubusercontent.com/5111490/199231335-60a913fa-0a70-42ae-a0a4-e48165093d70.png)

`libFLAC++.dll`:
![image](https://user-images.githubusercontent.com/5111490/199231538-31fe3bc2-89ae-42ca-9a80-50308b94826d.png)
(This one even hardcoded "1, 0, 0, 0" as product version which is completely wrong, because even in German the version numbers are written as "1.0.0.0" - yet it used the correct, dotted format just 3 lines above as file version (`Dateiversion`)…)

Please, don't fix just the version info, but instead fill all relevant fields with correct data, e. g. copyright, description, (original) name, etc.

**Comment by ktmf01** [comment]
Thanks for reporting, I wasn't aware there are such properties on Windows.

Are these properties being used somewhere, or is this only something that doesn't look nice?

The DLL exports version information through the FLAC__VENDOR_STRING and FLAC__VERSION_STRING symbols.

**Comment by Eagle3386** [comment]
> Thanks for reporting, I wasn't aware there are such properties on Windows.

You're welcome! :)

> Are these properties being used somewhere, or is this only something that doesn't look nice?

It's actually used at a couple of locations:
1. Windows Explorer's file tooltip:
![image](https://user-images.githubusercontent.com/5111490/199240988-dece7310-0562-41fd-a189-0214aa9e211d.png)

2. Don't have Visual Studio installed on the machine I'm writing from right now, but when adding library references to a project, VS explicitly shows that version information inside that dialog.

3. There's a `Properties` tool window inside Visual Studio which shows further properties for such libraries.

> The DLL exports version information through the FLAC__VENDOR_STRING and FLAC__VERSION_STRING symbols.

Yes, but
a) maybe `FLAC_API_SUPPORTS_OGG_FLAC` can be exported as file description, e. g. `Ogg FLAC support: [yes|no]` instead of `POSIX WinThreads for Windows`?
b) while the API docs for `FLAC_API_VERSION_CURRENT` link to [Libtool’s versioning system](https://www.gnu.org/software/libtool/manual/libtool.html#Libtool-versioning), the information over at the linked location doesn't seem to apply regarding the `1,0,0,0 instead of 1.0.0.0` issue I was referring to!?
c) the API docs for `FLAC__VERSION_STRING` note that:
> This does not correspond to the shared library version number, which is used to determine binary compatibility. 

Either way, Windows will only show versions if they're based on the "dotted scheme", i. e. no commas allowed.

Lastly, that copyright line should state FLAC's not MingW's and preferably prefixed with a `©` instead of that "space hogging" `Copyright (C)`

**Comment by ktmf01** [comment]
With #594 I get the following:

**libflac.dll**
![libFLAC](https://user-images.githubusercontent.com/64039749/234245890-b93916a9-e237-45d1-9a81-3ba4441946db.PNG)
**libflac++.dll**
![libFLAC++](https://user-images.githubusercontent.com/64039749/234245923-434d072c-c16f-4bfc-837c-069d30aea288.PNG)
**flac.exe**
![flac](https://user-images.githubusercontent.com/64039749/234245920-07967cda-787b-4d69-a5b8-6f769c75bfa1.PNG)
**metaflac.exe**
![metaflac](https://user-images.githubusercontent.com/64039749/234245925-9669af9c-028b-4cd3-bebf-6324b2afdc1e.PNG)

The line that now shows git-45052204 will show the version number (1.4.3 for example) for a release.

**Comment by Eagle3386** [comment]
While that's great to year, there's still 1 issue left:
Multiple occasions in Windows, e. g. the setup file's tooltip (see my comment above), *_only_* show the _file_ version, not the _product_ version you're now setting correctly.

In other words: can you make it so that file version gets set to whatever is assigned to product version as well?

**Comment by ktmf01** [comment]
The problem here is that `flac` and `metaflac` aren't versioned. The while product, FLAC, is versioned, and the libraries libFLAC and libFLAC++ have a version, but not the tools. So there isn't really anything I can put in there.

**Comment by Eagle3386** [comment]
What's standing against versionung both programs with the same version as the library since they're not versioned at all as of now?

**Comment by ktmf01** [comment]
libFLAC is now at version 12 and libFLAC++ is version 10. Those version numbers change if the interface changes in an incompatible way. This has no relation to the command line interfaces, which might also change from time to time. Also, it is probably confusing to users. I expect developers to understand the difference between a library interface version number and a product version number, but having a command line tool with a different version seems too much.

If I could use the product version number as the file version number, I would. But I can't. The product version number seems free form (I can but git-45052204 in there, no problem) but the file version number HAS to be 4 digits it seems, no more, no less.

**Comment by Eagle3386** [comment]
Yes, absolutely! Nonetheless, thanks for taking the time to explain, really appreciated!

Also, thanks a lot for fixing all the other details to such an extend. Eagerly forward to the next release, now! 😉
