### ISSUE TITLE
FLAC should not unconditionally add to CFLAGS

### ISSUE THREAD

**Issue by hbent** [xiph/flac#508]
ad9618c54d88534a714d2c61923c3e700615b20a changed behavior to unconditionally add "-O3 -funroll-loops" to CFLAGS (and -O3 to CXXFLAGS).  This really isn't a good idea - users could be setting any number of different CFLAGS for any number of different reasons, and there's not even a guarantee that everyone is using a compiler that understands these flags.  Setting defaults is fine, but unconditionally adding CFLAGS is very non-portable.

**Comment by ktmf01** [comment]
Could you supply an example where this is a problem? As far as I know, these flags can easily be overridden as they are prepended, so that leaves compilers that don't understand these options.

**Comment by hbent** [comment]
Yes, there are compilers that can compile FLAC that don't understand these options.  Oracle Developer Studio and IBM XL C come to mind immediately but I am sure that there are others.

**Comment by ktmf01** [comment]
Does #509 seem like a proper fix?

**Comment by hbent** [comment]
Yes, that seems like a very reasonable fix.  Thank you!
