### ISSUE TITLE
flac.exe compiled using MSVC 2017 produces zero-size files

### ISSUE THREAD

**Issue by kitzik** [xiph/flac#51]
it seems that the issue resides within this part of code in "windows_unicode_filenames.c":

#if _MSC_VER > 1900 && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
	wchar_t *wname;
	HANDLE handle = INVALID_HANDLE_VALUE;

	if ((wname = wchar_from_utf8(lpFileName)) != NULL) {

		handle = CreateFile2(wname, dwDesiredAccess, dwShareMode, CREATE_ALWAYS, NULL);
		free(wname);
	}
#else

it causes these warnings:

8>c:\__workdir\projects\flac-master\src\libflac\windows_unicode_filenames.c(212) : : warning C4716: 'flac_internal_CreateFile_utf8': must return a value
8>c:\__workdir\projects\flac-master\src\share\grabbag\file.c(133) : : warning C4700: uninitialized local variable 'h1' used
8>c:\__workdir\projects\flac-master\src\share\grabbag\file.c(133) : : warning C4700: uninitialized local variable 'h2' used

**Comment by erikd** [comment]
This was fixed in commit 45f7d41a8a87a743e7 .
