### ISSUE TITLE
Raw input: "default" for --sign

### ISSUE THREAD

**Issue by H2Swine** [xiph/flac#520]
Either a documentation issue or a feature wishlist. According to https://xiph.org/flac/documentation_tools_flac.html
```
--sign={signed|unsigned}
    Set the sign of samples (the default is signed).
```
... however, --sign MUST be specified when encoding raw: omitting it will throw an error.

Suggested would be to 
- either delete the " (the default is signed)" string
- or default everything to little-endian CDDA and if anything is omitted, throw a warning.

**Comment by ktmf01** [comment]
I'll just remove the mention of a default, I think it is unwise to assume any default for raw input.
