### ISSUE TITLE
version miss-match 

### ISSUE THREAD

**Issue by fpefpe** [xiph/flac#523]
I create a flac file using eac --- with version 1.3.2 (64bit) flac   I then tried to convert it back to wav user flac version 1.4.2 and it failed 
here is the  info on that 

flac 1.4.2
Copyright (C) 2000-2009  Josh Coalson, 2011-2022  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

01 wabash cannonball.flac: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

01 wabash cannonball.flac: ERROR during decoding
                           state = FLAC__STREAM_DECODER_END_OF_STREAM
flac2mp3 -> rcode: '1' time: (0d 0h 0m 1s 243f)
flac2mp3 +++ can't convert 'h:\__flac__\arlo guthrie & pete seeger\precious friend\01 wabash cannonball.flac' to wave

**Comment by ktmf01** [comment]
This is because EAC adds an ID3v1 tag to the file when requested. This strictly speaking invalidates the file. See for example https://hydrogenaud.io/index.php/topic,123259.msg1018464.html#msg1018464

I consider this a bug in EAC, not in FLAC.

**Comment by ktmf01** [comment]
I don't what software can correctly read an ID3 tag on a FLAC file, as it is non-standard.

If you just want to get rid of these ID3 tags, you can simply re-encode the files with the flac command line program. It will rewrite the file, ignoring the ID3 tags.

**Comment by fpefpe** [comment]
this command will fix the file of ID3 tags 

ffmpeg -i input.m4a -c copy output.m4a
