### ISSUE TITLE
The error message on too long filename/path (Windows)

### ISSUE THREAD

**Issue by H2Swine** [xiph/flac#528]
Windows has kept compatibility with its old sins, so several applications run into trouble on too long path. I guess circumventing it would be a bit of a job, but the error reporting could give a better hint.  This part is likely OK: 
```
ERROR initializing encoder
init_status = FLAC__STREAM_ENCODER_INIT_STATUS_ENCODER_ERROR
state = FLAC__STREAM_ENCODER_IO_ERROR
```
but in this explanation to humans could be improved:
```
An error occurred opening the output file; it is likely that the output
directory does not exist or is not writable, the output file already exists and
is not writable, or the disk is full.
```
Indeed, the user could want the information that even if everything was fine upon encoding (when a .flac file was written), re-encoding may trigger this error because the .flac.tmp,fl-ac+en'c file hs a longer name.

**Comment by WookieeNo1** [comment]
I hope I'm not getting this suggestion in the wrong place, or committing some faux pas, but attempting to read files whose full path and name exceed the old MAX_PATH length generates FLAC__METADATA_CHAIN_STATUS_ERROR_OPENING_FILE. 

From Windows 10, version 1607, it is possible to circumvent this limitation, requiring both a registry hack and a manifest entry to enable Long Path support. More details here:
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

**Comment by emalizia** [comment]
Hi. In the comments above, people were referring to the error encountered when trying to *write* to a file with long path name. I've found out that this can be circumvented by using the "\\?\" trick (see https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) with the "-o" option in the flac command line.

However, the flac command line has issues while *opening* files with long path names, and this apparently cannot be solved by using the same "\\?\" trick: the tool simply returns that the source file does not exist if the prefix "\\?\" is used.
