### ISSUE TITLE
flac failed to setup due to CMake Error with MSVC on windows

### ISSUE THREAD

**Issue by fangzhouxia** [xiph/flac#529]
**Description:**
flac failed to setup due to CMake Error with MSVC on windows. Could you please help look at this issue or provide some workarounds? Thanks in advance.

**For Error Reports:**
1. open VS2019 x86 tools command.
2. git clone https://github.com/Microsoft/vcpkg F:\gitP\Microsoft\vcpkg
3. git clone https://github.com/xiph/flac F:\gitP\xiph\flac
4. git clone https://github.com/xiph/ogg F:\gitP\xiph\ogg
5. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=x86 -arch=x86
6. cd F:\gitP\Microsoft\vcpkg
7. bootstrap-vcpkg.bat
8. vcpkg.exe install --recurse libogg --triplet x86-windows --clean-after-build
9. cd F:\gitP\xiph\flac & mkdir build_x86 & cd F:\gitP\xiph\flac\build_x86
10. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows .. 

**Actual behavior:**
[configure.log](https://github.com/xiph/flac/files/10215735/configure.log)
-- Looking for string.h - found
-- Looking for sys/ioctl.h
-- Looking for sys/ioctl.h - not found
-- Looking for termios.h
-- Looking for termios.h - not found
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find busybox, only basic tests are enabled
CMake Error at CMakeLists.txt:283 (message):
  Pandoc nor prebuild manpages are found.  Cannot install manpages.  Set
  INSTALL_MANPAGES to OFF to build without man pages
-- Configuring incomplete, errors occurred!
See also "F:/gitP/xiph/flac/build_x86/CMakeFiles/CMakeOutput.log".
See also "F:/gitP/xiph/flac/build_x86/CMakeFiles/CMakeError.log".

**Configuration:**
VS version: VS2019(16.11.20)
Operating system: windows server 2019

**Comment by ktmf01** [comment]
Well, the error message says it all right? Set INSTALL_MANPAGES to OFF to continue.

That means you need to add `-DINSTALL_MANPAGES=OFF` to the command in step 10
