### ISSUE TITLE
external CFLAGS make ./configure fail

### ISSUE THREAD

**Issue by klslz** [xiph/flac#535]
COMMIT: fe0bf2309a2ac6435615f0ed25009ef6bb8de855

If running

```export CFLAGS="-O3 --march=native"
./autogen.sh
./configure --prefix=/usr 
```

./configure fails with

```
 checking whether make supports nested variables... (cached) yes
checking whether to enable debugging... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/flac':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

But there are more fatal errors in the config.log, even without defining external CFLAGS.
However. Without external CFLAGS ./configure won't fail.

Attached the config.log

[config.log](https://github.com/xiph/flac/files/10390360/config.log)

**Comment by ktmf01** [comment]
Have you checked whether the CFLAGS you're setting are correct? It seems they are not, in which case this isn't really a FLAC problem.

**Comment by ktmf01** [comment]
I'm pretty sure you only need a single dash before march. So, that would make it `export CFLAGS="-O3 -march=native"`

config.log says 
```
gcc: error: unrecognized command-line option '--march="native"'
```

It seems you also used double quotes around native, as far as I know that isn't correct either.

**Comment by klslz** [comment]
```
thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
configure:3842: $? = 0
configure:3831: gcc -V >&5
gcc: error: unrecognized command-line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3842: $? = 1
configure:3831: gcc -qversion >&5
gcc: error: unrecognized command-line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:3842: $? = 1
configure:3862: checking whether the C compiler works
configure:3884: gcc -O3 --march=native   conftest.c  >&5
gcc: error: unrecognized command-line option '--march=native'
configure:3888: $? = 1
configure:3926: result: no
configure: failed program was:
| /* confdefs.h */
```
That's the config.log output after I running my compilation script (the one that's been working for years) 
Obviously the trouble starts already  earlier see: "-V" "qversion". And no, I do not use double quotes
in my script. It seems the gcc commandline gets not generated properly.

**Comment by ktmf01** [comment]
But it is still wrong. Replace `--march=native` with `-march=native` and see whether that helps.

**Comment by klslz** [comment]
Just figured it out. See my edited post earlier.

**Comment by ktmf01** [comment]
Considering the other errors you mention, I think these are intentional, as part of determining which compiler is being used. That is not something FLAC invented though, but part of configure, as generated by autotools.

**Comment by klslz** [comment]
"Fatal error" messages just never look that trustworthy.

Anyhow have a good one. 

BTW: Great job you're doing lately. Good to see that the project got reanimated.
