### ISSUE TITLE
metaflac --scan-replay-gain precision

### ISSUE THREAD

**Issue by joshstoik1** [xiph/flac#536]
Hi there!

It would be helpful if `metaflac --scan-replay-gain` formatted its values to the same precision as `--add-replay-gain`, i.e. [`%1.8f`](https://github.com/xiph/flac/blob/master/src/share/grabbag/replaygain.c#L58) rather than just [`%f`](https://github.com/xiph/flac/blob/master/src/metaflac/operations.c#L482).

The more decimal places the merrier, I always say…

Thanks!

**Comment by ktmf01** [comment]
If I run `flac -f --replay-gain somefile.flac` and then run `metaflac --list somefile.flac` I get

```
    comment[0]: REPLAYGAIN_REFERENCE_LOUDNESS=89.0 dB
    comment[1]: REPLAYGAIN_TRACK_GAIN=-3.85 dB
    comment[2]: REPLAYGAIN_TRACK_PEAK=0.86211973
    comment[3]: REPLAYGAIN_ALBUM_GAIN=-3.85 dB
    comment[4]: REPLAYGAIN_ALBUM_PEAK=0.86211973
```

If I then run `metaflac --remove-all-tags somefile.flac`, then `metaflac --add-replay-gain somefile.flac` and finally  `metaflac --list somefile.flac` again, I get the exact same values.

So I don't seem to be able to reproduce the issue.

The %1.8f is only used for the peaks, not for the gain. Also, I think having dB gain values with more than one than one decimal place is already pretty pointless, let alone 8.

**Comment by ktmf01** [comment]
Okay, I misunderstood the question. I was under the impression you were comparing `metaflac` and `flac`, I wasn't aware of the function `--scan-replay-gain`. If I run `metaflac --scan-replay-gain somefile.flac` I indeed get a different precision `05 - 32bps audio.flac: -3,849998 0,862120 -3,849998 0,862120`.

So, you would like more decimal places for the peak value? Why do you think these extra decimal places make sense? For 16 bit audio, the difference for one quantization step is only 0,000030, so adding more decimal places only makes sense for 24-bit audio.

**Comment by joshstoik1** [comment]
Thanks for the quick response, @ktmf01!

My motivation for the request is to make it easier/faster to apply replaygain data to files _conditionally_, primarily to avoid writing any changes to the master files unless there are actual changes worth writing. (For me, this helps prevent lots of backup-related I/O for silly things like arbitrary changes to tag ordering.)

At the moment, I copy the files from an album, run `metaflac --add-replay-gain` against those copies, parse the results from their metadata, remove the copies, compare the values with those in the original files, and apply them if different.

If `metaflac --scan-replay-gain` could give me the same peak values, I could avoid a lot of that runaround. :wink:

**Comment by ktmf01** [comment]
The problem is that other applications might rely on the precision as it is right now.

Also, I don't know what your primary use is here, but the algorithms `metaflac` uses are considered outdated by many. See for example https://github.com/xiph/flac/issues/96. You might be better off using some tool other than `metaflac` to calculate replaygain values altogether.

**Comment by joshstoik1** [comment]
Thanks @ktmf01, that makes sense. I'll take a look at some of the newer tools instead.
