### ISSUE TITLE
metaflac --with-filename not working as expected

### ISSUE THREAD

**Issue by andrew-strong** [xiph/flac#537]
I am attempting to use the `--with-filename` option of metaflac 1.4.2 to export tags from appropriately tagged flac files to an external file. Using Slackware 64bit Linux.

Sample command below:

`metaflac --with-filename --export-tags-to=audio_tags.csv test1.flac test2.flac`

The output in audio_tags.csv is then as follows:

```
encoder=Lavf59.34.102
REPLAYGAIN_TRACK_PEAK=0.97720337
REPLAYGAIN_TRACK_GAIN=-4.19 dB
REPLAYGAIN_ALBUM_PEAK=0.97720337
REPLAYGAIN_ALBUM_GAIN=-4.19 dB
ALBUM=Treasure Quest Soundtrack
ARTIST=Jody Marie Gnant
DATE=1995
GENRE=Soundtrack
Comment=1-minute song sample demonstrating FLAC compression
TITLE=Lucky Night
TRACKNUMBER=9
REPLAYGAIN_TRACK_PEAK=0.97720337
REPLAYGAIN_TRACK_GAIN=-4.19 dB
REPLAYGAIN_ALBUM_PEAK=0.97720337
REPLAYGAIN_ALBUM_GAIN=-4.19 dB
ALBUM=Treasure Quest Soundtrack
ARTIST=Jody Marie Gnant
DATE=1995
GENRE=Soundtrack
Comment=1-minute song sample demonstrating FLAC compression
TITLE=Lucky Night
TRACKNUMBER=9
```

Either I am not using the option correctly (ready to acknowledge this) or the option is being ignored.

**Comment by ktmf01** [comment]
It seems metaflac applies that option only very selectively, for example when using `metaflac --list`. It seems it does this only for options that always output to stdout. For example `metaflac --export-tags-to=- file1.flac file2.flac` doesn't prepend filenames either.

Of course I don't know your usecase for such a file. If it is not meant to be machine-readable, perhaps using ` metaflac --list --block-type=VORBIS_COMMENT file1.flac file2.flac` works for you?
