### ISSUE TITLE
How can I convert buffer(from flac file) to pcm samples directly without  saving flac file? 

### ISSUE THREAD

**Issue by woong97** [xiph/flac#538]
In examples/cpp/decode/file/main.cpp, I can understand "read flac file and convert to wav file",

But I want to change std::streambuf of flac file to pcm samples(e.g. vector<float>). 
I have unefficient solution. 
"Save std::streambuf buffer to sample.flac file. Then use FLAC::Decoder::File in example code and collect pcm samples"
But I want to skip "saving file process", I want to convert std::streambuf buffer to pcm samples directly

So I try to use FLAC::Decoder::Stream, but I cannot find method init() with buffer parameter. Only FLAC::Decoder::File have init() method with parameters( File *file or const char *filename or const std::string &filename) 

How can I convert buffer(std::streambuf<char>) from flac file to pcm wav samples(std::vector<float>) ?

**Comment by ktmf01** [comment]
Please read the documentation on FLAC::Decoder::Stream here: https://xiph.org/flac/api/classFLAC_1_1Decoder_1_1Stream.html

It says:
> The usage of this class is similar to [FLAC__StreamDecoder](https://xiph.org/flac/api/structFLAC____StreamDecoder.html), except instead of providing callbacks to FLAC__stream_decoder_init*_stream(), you will inherit from this class and override the virtual callback functions with your own implementations, then call [init()](https://xiph.org/flac/api/classFLAC_1_1Decoder_1_1Stream.html#a33169215b21ff3582c0c1f5fef6dda47) or [init_ogg()](https://xiph.org/flac/api/classFLAC_1_1Decoder_1_1Stream.html#adb52518fda2e3e544f4c8807f4227ba7). The rest of the calls work the same as in the C layer.
>
> Only the read, write, and error callbacks are mandatory. The others are optional; this class provides default implementations that do nothing. In order for seeking to work you must override [seek_callback()](https://xiph.org/flac/api/classFLAC_1_1Decoder_1_1Stream.html#af6f7e0811f34837752fbe20f3348f895), [tell_callback()](https://xiph.org/flac/api/classFLAC_1_1Decoder_1_1Stream.html#a0075cb08ab7bf5230ec0360ae3065a50), [length_callback()](https://xiph.org/flac/api/classFLAC_1_1Decoder_1_1Stream.html#a6a9af9305783c4af4b93698293dcdf84), and [eof_callback()](https://xiph.org/flac/api/classFLAC_1_1Decoder_1_1Stream.html#ac06aa682efc2e819624e78a3e6b4bd7b).

So, you'll have to provide callbacks that feed the bytes to libFLAC.

**Comment by ktmf01** [comment]
Did this answer your question? Can I close this issue?
