### ISSUE TITLE
Examples don't seem to support signed 32bit PCM encoding (1.4.0+)

### ISSUE THREAD

**Issue by jcurtis-cc** [xiph/flac#539]
I've been trying to test signed 32bit PCM wav encoding to FLAC using the `flac` CLI. 

Steps to repro:

1. built repo via CMake on MacOS 12.6.1 arm64
2. Generate a tone/noise/rhythm track in audacity
3. Export as Signed 32bit PCM WAV
4. `$ ./flac test32s.wav`

> test32s.wav: WARNING: legacy WAVE file has format type 1 but bits-per-sample=32
> test32s.wav: wrote 297701 bytes, ratio=0.517

File writes out, but is unplayable. Opens in audacity, no sample data is visible.

I had similar results building libFLAC and libFLAC++ and attempting to encode a buffer of signed 32bit PCM samples to FLAC.

Any tips to get 32bit encoding working with 1.4.0+?

**Comment by jcurtis-cc** [comment]
Similar results when attempting to encode a 32bit PCM RAW exported from audacity and specifying the required params 

``` bash
$ ./flac test32s.raw -f --endian=little --sign=signed --sample-rate 48000 --channels 2 --bps 32
```

**Comment by ktmf01** [comment]
What application are you trying to play these files with? Support for 32-bit integer PCM was only very recently merged in libFLAC, so many decoding applications do not yet support it.

**Comment by jcurtis-cc** [comment]
Ah - yes of course, Audacity probably doesn't support it yet
