### ISSUE TITLE
Is Padding with length = 0 allowed? 

### ISSUE THREAD

**Issue by Mravojad** [xiph/flac#544]
Hi everyone,
I have some files with many Padding Blocks.
Some of this blocks have length = 0
My player crashes by trying to play this files.

Please help me to find the problem. I have questions:
Are many separate Padding Blocks allowed? (My opinion is YES)
Must the padding lenght be a multiple of 8? I find it in the documentation, but I have a lot of files of padding lengh with odd numbers.
Is allowed to have padding blocks with length = 0? If not - should the payer skip it or crash is also a valid reaction?

Thank you veery much in advance for your kind support!
Mravojad

**Comment by ktmf01** [comment]
> Are many separate Padding Blocks allowed? (My opinion is YES)

Yes, that is allowed.

> Must the padding lenght be a multiple of 8? I find it in the documentation, but I have a lot of files of padding lengh with odd numbers.

The length in **bits** must be a multiple of 8, meaning it must be a whole number of bytes. I guess you're seeing files with an odd number of bytes.

> Is allowed to have padding blocks with length = 0?

Yes, that is allowed

> If not - should the payer skip it or crash is also a valid reaction?

A player should never crash, not even on invalid files. Maybe these files will help you: https://github.com/ietf-wg-cellar/flac-test-files

**Comment by Mravojad** [comment]
Thank you Martijn for the quick and informative answer.
Couldd you tell me please where can I find an information that is allowed to have padding blocks with length = 0?
I try to get repaired my hardware by the vendor, but the vendor tells me, that is not allowed to have padding blocks with length = 0 and this is my problem and not problem of the player.
How can I bring an evidence, that this is an issue of the hardware and notr of my files?
Thank you in advance!
Mraivojad

**Comment by ktmf01** [comment]
It is not specifically mentioned in the docs, but it is not excluded either. Maybe I'll add a note to the FLAC specification document to clarify.

You can get the official flac tools to produce a file quite easily, which I think is proof in itself.

Take a (copy of a) FLAC file, and do the following two steps

```
metaflac --remove-all --dont-use-padding
metaflac --add-padding=0
```

The first step ensures all existing padding is removed, the second step adds a padding block with length 0. I think this is ample proof this is 'legal'.

**Comment by Mravojad** [comment]
Hi Martijn,
thank you again for the quick response.
I would appreciate very much if you could extend the documentation regarding padding length = 0.
This will help me very much in my discussion with the vendor. 
Now the vendor states that my flac files are wrong (because of padding length = 0) and refuse to update his software.
If I can show him that padding length = 0 is valid, I would have a strong arguments to update his software.
The vendors states now, that padding length = 0 is not explicitly allowed and his software doesn't need to support it.
I thank you for your efforts in advance and wish you a nice weekend.
kind regrads
Mravojad

**Comment by ktmf01** [comment]
There is now some clarification in the latest IETF draft: https://datatracker.ietf.org/doc/draft-ietf-cellar-flac/

It now says
> n '0' bits (n MUST be a multiple of 8, i.e. a whole number of bytes, and MAY be zero)

**Comment by Mravojad** [comment]
Hello Martijn,

 

thank you very much for the  clarification you made!

 

And thank you  very much that you didn’t forget my issue and considered in the latest IETF draft 😉

 

I wish you a nice weekend!

 

Kind regards

 

Genadiev

 

 

Von: Martijn van Beurden ***@***.***> 
Gesendet: Freitag, 14. April 2023 08:54
An: xiph/flac ***@***.***>
Cc: Mravojad ***@***.***>; Author ***@***.***>
Betreff: Re: [xiph/flac] Is Padding with length = 0 allowed? (Issue #544)

 

There is now some clarification in the latest IETF draft: https://datatracker.ietf.org/doc/draft-ietf-cellar-flac/

It now says

n '0' bits (n MUST be a multiple of 8, i.e. a whole number of bytes, and MAY be zero)
