### ISSUE TITLE
flac shows FLAC__STREAM_DECODER_ERROR_STATUS_xxx since version 1.4.0 for some files

### ISSUE THREAD

**Issue by toto263** [xiph/flac#562]
After upgrading from version 1.3.4 to version 1.4.x, some files failed to decode/test with FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC, FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER errors.
They were OK with <= 1.3.4.
Only a few files are affected. Most of them are OK.

Attached first 5MB of one file. 

[Forever_FLAC_96Hz_24bit.001.zip](https://github.com/xiph/flac/files/10886120/Forever_FLAC_96Hz_24bit.001.zip)

**Comment by ktmf01** [comment]
Hi,

FLAC 1.4.0 became a lot more strict at parsing FLAC files, for various reasons, most of them security related.

This file has been created by a program sending libFLAC invalid data. As you can imagine, supplying invalid data results in invalid files. Starting with FLAC 1.4.0, both the encoder and the decoder do extra checks for this.

As it not possible for libFLAC to determine what is the best way to decode and fix such an invalid file, it will simply throw an error. If you are OK with the way FLAC 1.3.4 decodes them, the best way to fix these files is decoding them to WAV or AIFF with FLAC 1.3.4 and then encode them again with any version of your choosing. Re-encoding the file with FLAC without first explicitly decoding to WAV/AIFF will not work.

**Comment by toto263** [comment]
I understand.
But I just want to decode the files even if they are invalid.
As a developer of music player, I don't want my users to complain that some files not playing after update.
Isn't it possible to add a flag (ignore invalid data) that makes the 1.4.x work like 1.3.x?

**Comment by ktmf01** [comment]
> But I just want to decode the files even if they are invalid

There is no way to determine how these files should be played back correctly. It could be the behaviour of libFLAC 1.3.4 was correct, but there are also broken files out there of which that behaviour certainly wasn't correct. As FLAC is a lossless codec, it will not make a decision in these matters. The way libFLAC 1.3.4 played back these files was unintentional and potentially not lossless.

**Comment by GK-774** [comment]
"Not planned" - that are very unfortunate news for anyone having an archive of flac files. Breaking backwards compatibility is an abslolutely no go for an archiving tool, what played yesterday has to play tomorrow as well, no excuses.
So the message here basically is: If you want archive your music use something you can rely on. As an archiving tool flac 1.4 and later is broken.

**Comment by m-stefanski** [comment]
This is quite a headache for me as I now try to repair my broken library that also contains some incomplete downloads with zero-padding - and it seems that I am getting both errors from incomplete but also encoded by earlier versions.

But, maybe there is no difference after all:

Do I understand correctly that files generate by older FLAC version are beyond repair?

**Comment by ktmf01** [comment]
> Do I understand correctly that files generate by older FLAC version are beyond repair?

That statement is way too broad. Almost all FLAC files are fine. There is, as far as I know, just one DAW that generated faulty FLAC files by feeding invalid data to libFLAC.

> and it seems that I am getting both errors from incomplete but also encoded by earlier versions.

FLAC 1.5.0 has differentiated error messages: FLAC__STREAM_DECODER_ERROR_STATUS_OUT_OF_BOUNDS
