### ISSUE TITLE
Can't get Alac to Flac to work with the latest version

### ISSUE THREAD

**Issue by Hamybal** [xiph/flac#571]
Before i was able to use this line and it automatically kept all values the same and converted the alac to flac.
    "D:\test\flac.exe" -8 input.m4a -o output.flac

with the latest flac 1.4.2 you get an error showing:
    ERROR: for encoding a raw file you must specify a value for --endian, --sign, --channels, --bps, and --sample-rate

Using this line as example,
    flac --endian=big --sign=signed --channels=2 --bps=16 --sample-rate=44100 -o output.flac input.m4a
I've tried some lines with these values but always get an error like for example.
    input.m4a: 92% complete, ratio=1,001input.m4a: ERROR: got partial sample
so i'm not sure how to convert at the moment with libflac, and also really want to know if it's still somehow possible to have these values automatically set again with out changing anything in the conversion besides alac to flac?

Hopefully you guys know what might be the reason?
Furthermore have a good one!

**Comment by ktmf01** [comment]
> Before i was able to use this line and it automatically kept all values the same and converted the alac to flac. "D:\test\flac.exe" -8 input.m4a -o output.flac

That was never possible. The flac command line encoder has no ALAC decoder, so what you're trying to do is not possible and never has been possible.

Please consider using appropriate tools like fre:ac, ffmpeg, foobar2000 or dBpoweramp.
