### ISSUE TITLE
renaming flac_assert.h into assert.h causes issues

### ISSUE THREAD

**Issue by philippe44** [xiph/flac#577]
It should probably have stayed as "flac_assert.h" because renaming it "assert.h" causes issues with files that use "include_next" option where the flac's "assert.h" takes precedence over the real system's one.

**Comment by ktmf01** [comment]
When was this file ever named flac_assert.h? It seems it has been called assert.h since 2001?

Also, it is to be included as `#include "FLAC/assert.h"`, which means it has already got FLAC/ as prefix. Does this still cause problems with include_next?

**Comment by philippe44** [comment]
oooh, my bad. I probably have renamed it flac_assert years ago for that project and forgot about it. It hit me again when I updated to the latest flac. All my codecs's headers are under inc/xxx and I just realized that my Cmake file had an include for inc/FLAC and of course it should not. 

As for the vast majority of the cases, problem is between the chair and the keyboard.

Sorry for the noise and thanks a lot for the super quick answer!
