### ISSUE TITLE
empty seektable might fail on some libc

### ISSUE THREAD

**Issue by philippe44** [xiph/flac#579]
in stream_decoder.c, ther is the following.
```
FLAC__bool read_metadata_seektable_(FLAC__StreamDecoder *decoder, FLAC__bool is_last, uint32_t length)
{
       ...
       ...
	/* use realloc since we may pass through here several times (e.g. after seeking) */
	if (0 == (decoder->private_->seek_table.data.seek_table.points = safe_realloc_mul_2op_(decoder->private_->seek_table.data.seek_table.points, decoder->private_->seek_table.data.seek_table.num_points, /*times*/sizeof(FLAC__StreamMetadata_SeekPoint)))) {
		decoder->protected_->state = FLAC__STREAM_DECODER_MEMORY_ALLOCATION_ERROR;
		return false;
	}
```
The problem is that when there is no point in the seektable, then we try to realloc(NULL, 0) which according to standard should behave like malloc(0) but it seems to me that malloc(0) can return either a "freeable" pointer or NULL, there is no rule and it's platform dependent.

Of course, that makes the reading of the seektable fails and the whole decoding. I think, unless you disagree with my understanding that malloc(0) is not properly defined, we should test for non-zero * decoder->private_->seek_table.data.seek_table.num_points" before trying to call *safe_realloc_mul_2op_". The rest of the code is safe

**Comment by ktmf01** [comment]
Strange that this issue has not been reported earlier. The code hasn't been touched for 11 years, and this behaviour has been in there for much longer, it seems at least 21 years. I presume libc's that return NULL in the case of malloc(0) are quite rare? Do you have an example? I presume you found this by using such a libc?

**Comment by philippe44** [comment]
Indeed - it's on the esp32 platform, using espressif's esp/idf. I checked at least on Win32 and malloc(0) indeed returns non NULL and it returns NULL on esp32

**Comment by ktmf01** [comment]
I think the best way to handle this is by adding a check for an empty seektable, like there is a check that the seektable length makes sense. That way the rest of the code doesn't have to deal with it. I'll have to check whether this causes any problems elsewhere.

**Comment by philippe44** [comment]
I agree 100% and that what I did for my case. It would just return and empty table because the code below does not build anything are the index is 0. Seems risk-free to me. I can a PR if you want but that's just half a line
