### ISSUE TITLE
FLAC__stream_decoder_seek_absolute occasionally fails, even if the file is sound

### ISSUE THREAD

**Issue by sudo-rm-rf-oops** [xiph/flac#580]
The following statement in `FLAC__bitreader_read_rice_signed_block` is causing trouble, in that it can cause `FLAC__stream_decoder_seek_absolute ` to fail when it shouldn't:
```
if(x > limit)
    return false;
```
The problem is that `return false;` is occasionally executed while seeking (I think `frame_sync` has been fooled by something that 'looks like' a frame header but isn't) and this bubbles up the stack and ultimately causes the seek to fail.

I can provide a test program and test file if that helps.  Let me know.

-----

Edit:  The following statement in `read_subframe_` is also having the same effect:
```
if (decoder->private_->frame.subframes[channel].wasted_bits >= bps)
    return false;
```
I'd be surprised if there weren't more examples of this.  The solution is probably to make `frame_sync` bulletproof, but I haven't looked into that.

**Comment by ktmf01** [comment]
Note to self, TODO: extend the seek tests to cover this first, then fix.

**Comment by ktmf01** [comment]
> Edit: The following statement in `read_subframe_` is also having the same effect:
> 
> ```
> if (decoder->private_->frame.subframes[channel].wasted_bits >= bps)
>     return false;
> ```
> 
> I'd be surprised if there weren't more examples of this. The solution is probably to make `frame_sync` bulletproof, but I haven't looked into that.

The statement you're quoting doesn't exist. I think you're referring to this:

https://github.com/xiph/flac/blob/147cfc8df424b3b4fe6cc15a37d8ab9f3320dcd6/src/libFLAC/stream_decoder.c#L2613-L2617

But clearly, that says return true.

Anyway, I'm working on a fix for the first case.

**Comment by sudo-rm-rf-oops** [comment]
> The statement you're quoting doesn't seem to exist.

OK, things have clearly move on since I took a copy of the code, see:

https://github.com/xiph/flac/commit/46bf04d0d74440a12be9508af508b4d373d696cf

There is also at least one, relevant, later commit.  Anyway, thanks for taking a look.  I currently have some defensive code that seeks from further back and then reads forward to the location required, if a seek should fail.

**Comment by ktmf01** [comment]
Aha, forgot about that one already.

Anyway, I was wondering, do you think libFLAC should even further harden seeking code, even if the worst possible latency greatly increases? Currently, FLAC tries to seek, but there are a number of conditions in which seeking fails. Of course, one can always seek by simply starting at the beginning of a file and decoding all the way up to the point the seek is requested. This is very reliable, but very slow. I could implement a new function (FLAC__stream_decoder_seek_absolute_thorough or something like that) or simply add it to the current function.

What do you think?

**Comment by sudo-rm-rf-oops** [comment]
> What do you think?

Well, if the current implementation can't be made to work reliably (and I can see that might be difficult to achieve, and indeed be certain of) then clearly some alternative is needed.  Seeking from the beginning of the file doesn't sound particularly useful to me, but the extra layer I added looks like this (in pseudo code) and maybe you'd consider adding something similar to your sources:

```
reliable_seek (FLAC__uint64 offset)
{
    FLAC__uint64 seek_offset = offset;
    while (!unreliable_seek (seek_offset))
        seek_offset -= 2048;                                   // heuristic, seems to be about right
    if (seek_offset < offset)
        read_and_discard_data (offset - seek_offset);
}
```

Of course, there are corner cases (such as not seeking back before 0 and giving up after a certain number of retries), but it's the best idea I have.  I'm not sure how best to handle malformed files, but maybe `read_and_discard_data` could detect this (it probably would anyway) and return a suitable error to the caller of `reliable_seek`.
