### ISSUE TITLE
Multiple errors when building DLL with Visual Studio 2017

### ISSUE THREAD

**Issue by evpobr** [xiph/flac#59]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2491	'FLAC__stream_decoder_get_channels': definition of dllimport function not allowed	C:\Windows\system32\CMakeLists.txt	C:\Users\user\Source\Repos\flac\src\libFLAC\stream_decoder.c	861	
Error	C2491	'FLAC__stream_decoder_get_channel_assignment': definition of dllimport function not allowed	C:\Windows\system32\CMakeLists.txt	C:\Users\user\Source\Repos\flac\src\libFLAC\stream_decoder.c	868	
Error	C2491	'FLAC__stream_decoder_get_decode_position': definition of dllimport function not allowed	C:\Windows\system32\CMakeLists.txt	C:\Users\user\Source\Repos\flac\src\libFLAC\stream_decoder.c	896	

```

This happens because public API symbols are marked as  `__declspec(dllimport)` with `FLAC_API` in both definition (header) and declaration (source) files. Visual Studio wants [only definition](https://msdn.microsoft.com/en-us/library/62688esh.aspx) to be marked.

The solution is to mark public symbols as `FLAC_API` in headers only. `GCC` and compatible compilers are not affected by this change, they allow `visibility` attribute on definition and declaration or even on both.

**Comment by erikd** [comment]
Looking forward to a PR fixing this.

**Comment by evpobr** [comment]
I'll do that.

**Comment by evpobr** [comment]
Sorry, that was wrong definitions set when upgrading projects. I close this.
