### ISSUE TITLE
Unable to write a FLAC file for some specific sample rates

### ISSUE THREAD

**Issue by nvishnoiMW** [xiph/flac#603]
Hello,

I am using libsndfile 1.1.0 for writing flac files. However, I found that for certain sample rates (65536 and 197368), sf_writef_double does not write any frames to the file. I have attached a sample C++ program demonstrating the issue. There might be other sample rates for which it fails, but through my experiments, I have been able to confirm these two values so far.
Can someone please confirm if this is a bug or am I doing something wrong?

I initially posted this issue on the libsndfile forum but was recommended to post it in the flac forum: https://github.com/libsndfile/libsndfile/issues/931

Thanks,
Nalini

[data_original.txt](https://github.com/xiph/flac/files/11424541/data_original.txt)

[main.txt](https://github.com/xiph/flac/files/11424542/main.txt)

**Comment by nvishnoiMW** [comment]
Hi @ktmf01, 

Thank you so much for this information. 
Just to understand clearly, from 1.4.0 onward, this behavior has been fixed meaning that we should be able to write FLAC files using those odd sample rates as well?

Thanks,
Nalini

**Comment by ktmf01** [comment]
Yes, this behaviour has been fixed, and libFLAC can be used to write all samplerates up to 1’048’575Hz from libFLAC 1.4.0 forward. However, the library user must set FLAC__stream_encoder_set_streamable_subset to do so, and it seems libsndfile doesn't set it. Therefore, I don't think you will be able to use libFLAC through libsndfile for writing these sample rates.

**Comment by nvishnoiMW** [comment]
Thank you, @ktmf01! 
We build flac separately before it is used by libsndfile so hopefully we can set the required flag in the flac library appropriately to let it write any sample rate up to 1’048’575Hz.
