### ISSUE TITLE
--keep-foreign-metadata discards WAV cue markers

### ISSUE THREAD

**Issue by josephernest** [xiph/flac#61]
I noticed that option `--keep-foreign-metadata` discards WAV cue markers. Here is how to reproduce the bug:

1) Create a 24-bit 96khz in SoundForge8, add 20 seconds of silence, and add two markers with "m" key shortcut
2) Save it, compress it with `flac --keep-foreign-metadata testmarkers.wav`
3) Decompress it with `flac -d testmarkers.flac`
4) Open the decompressed WAV in SoundForge: the markers have disappeared.

Here is a WAV containing markers:  http://gget.it/q4uh4/testmarkers.zip if you want to test it.

**Comment by lvqcl** [comment]
You need  `--keep-foreign-metadata` on decompression as well.
Try `flac -d --keep-foreign-metadata testmarkers.flac`.

**Comment by josephernest** [comment]
Thank you @lvqcl.

Sidenote: I noticed `flac -d --keep-foreign-metadata testmarkers.flac --stdout | md5sum` doesn't work, do you see an easy way to "decompress into memory and compute the MD5 sum", rather than having to output into a file `temp.wav`, and md5 this file?

**Comment by josephernest** [comment]
Suggestion for devs:

1) If a file has been compressed with  `--keep-foreign-metadata`, then make `flac -d` decompress the file with metadata *by default*, without having to also do `--keep-foreign-metadata` during decompression. It makes sense that, if we compressed with this option enabled, the file should keep the metadata, also during decompression.

2) Could we enable `--stdout` also when using `flac -d  --keep-foreign-metadata`? It would be useful for this purpose:

    md5sum myfile.wav
    flac -d --keep-foreign-metadata myfile.flac --stdout | md5sum

This would allow to compare the original file (including the markers and metadata) and the result of the decompression of the flac, to be 100% sure that the metadata are kept in the compressed file.

**Comment by lvqcl** [comment]
2a. You can send a patch or create pull request, otherwise it probably won't happen.

2b. Decompressed file can be different from a source file anyway - see [I compressed a WAVE file to FLAC, then decompressed to WAVE, and the two weren't identical. Why?](https://xiph.org/flac/faq.html#tools__wave_flac_wave)

In your case, original testmarkers.wav is 11520224 bytes long, and decompressed (with `--keep-foreign-metadata`) file is 11520248 bytes long. md5sum won't help you here.

**Comment by josephernest** [comment]
@lvqcl Yes for me (with 1.3.2) the original WAV and flac-compressed-decompressed WAV were bit-identical (I checked using md5sum).

This is great, but do you mean this interesting feature (bit-identical) will disappear in future releases? :

> I use flac binary based on current unreleased code, and it decodes your file differently.

**Comment by erikd** [comment]
@josephernest The problem is that some 24 bit WAV files are contained within the WAV container format in a way that is consider obsolete. This means that when one of these files is encoded from the old WAV format it will decode to the new WAV format. The audio will be bit identical, but the WAV container will be different.

**Comment by josephernest** [comment]
@erikd Does this file http://gget.it/q4uh4/testmarkers.zip use an old container type or new container type (btw, what's the specification name for old/new container types?)

**Comment by erikd** [comment]
Using the `sndfile-info` from the https://github.com/erikd/libsndfile on the file I get:
```
File : testmarkers.wav
Length : 11520224
RIFF : 11520216
WAVE
fmt  : 16
  Format        : 0x1 => WAVE_FORMAT_PCM
  Channels      : 2
  Sample Rate   : 96000
  Block Align   : 6
  Bit Width     : 24
  Bytes/sec     : 576000
data : 11520000
...
```
The `Format        : 0x1 => WAVE_FORMAT_PCM` part means its the old format. The new format would have `WAVE_FORMAT_EXTENSIBLE` or similar in that field.

**Comment by josephernest** [comment]
@erikd Thank you. With the current version (flac-1.3.2-win), I compared:

* an original WAV file using "old" format
* flac-compressed-decompressed WAV 

and they were bit-identical (I checked using md5sum), i.e. after flac decompression, it stayed old format since the original input was old format.

I think this is very good. Do you think this feature (old WAV format => old WAV format after flac compression/decompression) will be deprecated in future versions since you mentioned this @lvqcl? :

>FLAC 1.3.2 decodes your file bit-identically to original wav. But I use flac 
> binary based on current unreleased code, and it decodes your file differently.

**Comment by erikd** [comment]
@josephernest Please check what Git head does now. That is the best indication of what future releases will do :).
