### ISSUE TITLE
FLAC in MP4 and Ogg specs: how to signal custom channel layout

### ISSUE THREAD

**Issue by jprjr** [xiph/flac#636]
Hi there, I had two questions around specifications.

The [IETF FLAC draft](https://datatracker.ietf.org/doc/draft-ietf-cellar-flac/) defines how the `WAVEFORMATEXTENSIBLE_CHANNEL_MASK` Vorbis Comment is to be interpreted for a native FLAC file.

## For Ogg:

I noticed the reference FLAC encoder will set `WAVEFORMATEXTENSIBLE_CHANNEL_MASK` when encoding to an Ogg file, and honor the field when decoding from an Ogg file. The [Ogg Mapping](https://xiph.org/flac/ogg_mapping.html) doesn't directly mention handling `WAVEFORMATEXTENSIBLE_CHANNEL_MASK`, and when referring to the FLAC specification, it links to ["FLAC - Format"](https://xiph.org/flac/format.html), which also doesn't mention `WAVEFORMATEXTENSIBLE_CHANNEL_MASK` (though it does provide a link to the IETF draft).

I just wanted to verify, should FLAC decoders honor the `WAVEFORMATEXTENSIBLE_CHANNEL_MASK` comment in Ogg files?

## For MP4 / ISO BMFF

The [Encapsulation of FLAC in ISO Base Media File Format document](https://raw.githubusercontent.com/xiph/flac/master/doc/isoflac.txt) provides ["FLAC - Format"](https://xiph.org/flac/format.html) as a normative reference to the FLAC format, so like Ogg, there's an additional "hop" between the ISO BMFF spec and the definition of `WAVEFORMATEXTENSIBLE_CHANNEL_MASK`, as opposed to a direct link. Additionally, MP4 has a box (`chnl`) available for specifying a channel layout.

How should custom channel layouts for FLAC streams in MP4 files be signaled? The spec allows for multiple FLAC metadata blocks to be in the FLAC Specific Box, should decoders look for a Vorbis Comment block and parse the `WAVEFORMATEXTENSIBLE_CHANNEL_MASK` comment? Or should the channels be signaled via a `chnl` box? Or something else entirely?

**Comment by ktmf01** [comment]
This is the wrong place for this issue. https://github.com/ietf-wg-cellar/flac-specification/issues would be more appropriate. I am unable to transfer it however.

> The [IETF FLAC draft](https://datatracker.ietf.org/doc/draft-ietf-cellar-flac/) defines how the `WAVEFORMATEXTENSIBLE_CHANNEL_MASK` Vorbis Comment is to be interpreted for a native FLAC file.

The document says nowhere that this part of the specification is specific to non-encapsulated FLAC. All other parts of the specification are valid in a container, so why wouldn't this bit be too?

**Comment by jprjr** [comment]
For background: the reason I'm asking this is I opened a bugs with ffmpeg about not honoring the `WAVEFORMATEXTENSIBLE_CHANNEL_MASK` Vorbis Comment (one for Ogg, one for MP4). There's no response on the Ogg bug, and the MP4 bug got a response of "this isn't a bug."

I read through the documentation and I think where I got hung up with the IETF FLAC draft is in the opening abstract (emphasis mine):

> This document defines the Free Lossless Audio Codec (FLAC) **format** and its streamable subset.

I interpreted that to mean it's defining the native FLAC file format. That might be from me coming from the background of usually interpreting "format" to mean "encapsulation" (like Ogg, MP4, MKV, etc), and codec to mean encoded packetized audio (like Vorbis, Opus, etc).

Just to be completely honest, the thing I'm more interested in is getting the clarification that yes - to be compliant with the specs means parsing and honoring the `WAVEFORMATEXTENSIBLE_CHANNEL_MASK` comment when encapsulated in Ogg and MP4 files (and presumably, any other current or future encapsulation that allows Vorbis Comment blocks), so I can take that back to the ffmpeg bugs.

**Comment by ktmf01** [comment]
The document defines the FLAC format and some encapsulations. The encapsulations work by just taking parts of the FLAC stream and encapsulating them. Some parts are duplicated (like coded number and granule position in Ogg) and then they should be the same. In Ogg there is no way to specifically signal channel ordering, so channel mask in vorbis comments should be honoured

I have next to no knowlegde of MP4. I tried to understand how FLAC-in-MP4 works and summarized https://github.com/xiph/flac/blob/master/doc/isoflac.txt The ffmpeg people have much more knowledge of MP4 than I do. I'd say, if MP4 indeed has something that conveys the same information as WAVEFORMAT_CHANNEL_MASK, than that MP4-specific way has priority but WAVEFORMAT_CHANNEL_MASK should agree with it.

**Comment by jprjr** [comment]
Great! Thank you for taking the time, I'll close this issue out.
