### ISSUE TITLE
Cannot empty or delete VORBIS_COMMENT vendor string

### ISSUE THREAD

**Issue by x0tester0x** [xiph/flac#640]
How can I empty or delete VORBIS_COMMENT vendor string while keeping the comments?
```
METADATA block #1
  type: 4 (VORBIS_COMMENT)
  is last: true
  length: 83
  vendor string: reference libFLAC 1.4.3 20230623
  comments: 1
    comment[0]:
```

**Comment by x0tester0x** [comment]
I want to remove it, because i do not want that, when I give files to other persons, that they can see which tool I used to create the FLAC. So for example if I rip a bluray with MakeMKV, I want to remove, that in the vendor string they can see MakeMKV.

Can you implement the feature to delete or empty the vendor string?

**Comment by x0tester0x** [comment]
This feature is really important for me and I think taht this is not a big change and so not much work to implement.
When will this feature be implemented?

**Comment by ktmf01** [comment]
If you contribute a PR, it could be implemented next week. If not, I won't make any promises. As you can see from the issues list, there are open issues already 5 years old.

**Comment by H2Swine** [comment]
> How can I empty or delete VORBIS_COMMENT vendor string while keeping the comments?

From your question I take it that you know how to remove the VORBIS_COMMENT block entire, so here is a work-around. It will leave a vendor string, but not the right one:

Dump the file(s) into Mp3tag
Ctrl-x the tags away 
metaflac --remove --block-type VORBIS_COMMENT
In Mp3tag, hit Ctrl-z to undo. 

Mp3tag will write back the tags, but not the correct vendor string - it will it will fill in a vendor string of some reference libflac version.

**Comment by x0tester0x** [comment]
> If you contribute a PR, it could be implemented next week. If not, I won't make any promises. As you can see from the issues list, there are open issues already 5 years old.

I am not very good at C programming... so I think I can only wait until this feature will be implemented

**Comment by x0tester0x** [comment]
> > How can I empty or delete VORBIS_COMMENT vendor string while keeping the comments?
> 
> From your question I take it that you know how to remove the VORBIS_COMMENT block entire, so here is a work-around. It will leave a vendor string, but not the right one:
> 
> Dump the file(s) into Mp3tag Ctrl-x the tags away metaflac --remove --block-type VORBIS_COMMENT In Mp3tag, hit Ctrl-z to undo.
> 
> Mp3tag will write back the tags, but not the correct vendor string - it will it will fill in a vendor string of some reference libflac version.

That is not what I want... I want a empty string or delete the vendor string completely

**Comment by H2Swine** [comment]
Sure I read that. But it will serve this purpose: 

> that they can see which tool I used to create the FLAC. 

If anonymity is what you seek, then replacing it by something common is more efficient than the empty string.

**Comment by x0tester0x** [comment]
I cannot find in the code where it will write "vendor string: reference libFLAC 1.4.3 20230623". 
Can someone show me?

**Comment by x0tester0x** [comment]
Ok and where in the metaflac code gets this called?

**Comment by ktmf01** [comment]
That depends on what action metaflac does, specifically. Taking adding a vorbis comment block when there is none as an example, that would be.

Here:
https://github.com/xiph/flac/blob/31ccd3df31f912bac76e669c2fbf347adf2bf235/src/metaflac/operations_shorthand_vorbiscomment.c#L63

Then here:
https://github.com/xiph/flac/blob/31ccd3df31f912bac76e669c2fbf347adf2bf235/src/libFLAC/metadata_object.c#L468

**Comment by x0tester0x** [comment]
As workaround I changed the variable **FLAC__VENDOR_STRING** in the code to an empty string and rebuild the metaflac.exe.
