### ISSUE TITLE
FLAC in XILINX SDK

### ISSUE THREAD

**Issue by Pavansai07784** [xiph/flac#641]
How to configure FLAC with Xilinx SDK??

I have tried to add it in libraries but that doesn't work

**Comment by ktmf01** [comment]
I have no clue. Have you tried with libraries other than FLAC? Can you be more specific as to what you did exactly, and what didn't work?

**Comment by Pavansai07784** [comment]
I am trying to use FLAC for my project, For that I need to include FLAC in my libraries at SDK side but I can't mention the DLL files that I get when I extract the zip Is there any way that I can get pre-compiled flac files (flac.a)

**Comment by ktmf01** [comment]
It seems to me you'll have to compile it specifically for the hardware you're targetting. That means I cannot supply a precompiled one, at least not if you're not giving more details about what platform this is supposed to work on.

**Comment by Pavansai07784** [comment]
I'm working on KRM module zynq 7000soc and will be using ssm2603 audio codec in vivado tool

**Comment by Pavansai07784** [comment]
![Screenshot 2023-07-29 022925](https://github.com/xiph/flac/assets/79378585/1fcb84cb-dbc6-4a0b-bb83-13b05d95acf3)
![Screenshot 2023-07-29 023022](https://github.com/xiph/flac/assets/79378585/0494d592-dac4-472e-87ae-43bc7a6947d0)

**Comment by ktmf01** [comment]
What do you want to do, exactly? Do you only need FLAC decoding, or is encoding also necessary?

**Comment by Pavansai07784** [comment]
Actually I am getting wav files from the audio codec, So I need to convert those to flac, So for this I need both encoding and decoding files

**Comment by ktmf01** [comment]
That is unfortunate. For decoding, there is a header-only library available called [dr_flac](https://github.com/mackron/dr_libs/blob/master/dr_flac.h) that you can simply drop in as a header file and compile along with your project. For libFLAC however, you'll need to cross-compile to the zynq 7000 arch. I have tried to look up how that works, but I can't seem to find out how.

I could try to cross-compile on my own system (not with any Xilinx specific tools) in a few days, but I don't know whether that will 'just work'.

**Comment by ktmf01** [comment]
Nevermind, if I would provide you with a binary libFLAC it probably wouldn't work. I don't know what libc this SDK is using anyway.

You'll have to find out how to cross-compile software with this SDK. I don't know.

**Comment by ktmf01** [comment]
Have you found a way to compile FLAC for your project? Could you share what you learned?
