### ISSUE TITLE
Assessment of the difficulty in porting CPU architecture for flac

### ISSUE THREAD

**Issue by wangyuliu** [xiph/flac#646]
Hello everyone! I am working on implementing a tool to assess the complexity of CPU architecture porting. It primarily focuses on RISC-V architecture porting.In fact, it can be estimated on average across various architectures. As part of my dataset, I have collected the flac 
 project. **I would like to gather community opinions to support my assessment. I appreciate your help and response!** Based on scanning tools, the porting complexity is determined to be simple, with a small amount of code related to the CPU architecture in the project. (referring to the overall workload from adapting the project to a specific architecture to achieving full functionality on that architecture). Is this assessment accurate? I look forward to your help and response.

**Comment by ktmf01** [comment]
Maybe you can be a little more specific in what you mean?

The code of the FLAC project is written to be very portable, as is with many open-source projects that are shipped as core packages of most linux distributions. I'd say the effort of 'porting' is zero: the code just compiles on RISC-V (or any other system for with GCC/LLVM has been ported).

However, there are some CPU specific optimizations (currently for x86, x86_64 and ARM64 only) that are then lost, but those are nice to have, not strictly necessary.

**Comment by wangyuliu** [comment]
You have answered my question, thank you very much

**Comment by ktmf01** [comment]
Take a look at this: https://packages.debian.org/unstable/libflac12 There are 17 architectures listed. libFLAC was written with access to only a few (mostly x86, some ARM) but still the code compiles fine on other architectures without any changes.

Porting to bare-metal implementations is also possible, and requires more work, but is possible. See for example https://github.com/earlephilhower/ESP8266Audio
