### ISSUE TITLE
metaflac ERROR: writing FLAC file, status = "FLAC__METADATA_CHAIN_STATUS_ERROR_OPENING_FILE"

### ISSUE THREAD

**Issue by PacoH** [xiph/flac#647]
`metaflac --import-picture-from="$i" "$of"`
`ERROR: writing FLAC file, status = "FLAC__METADATA_CHAIN_STATUS_ERROR_OPENING_FILE"`
I got this error because the filename was 243 characters long (248 with flac extension), less than 255 character maximum for OS X. When I shortened it, I got no error.

**Comment by H2Swine** [comment]
The reason is that metaflac will write a temporary file with an extra extension (so, in case it cannot rename it back, then you can remove the extension manually). That extra extension, ".metadata_edit", makes the filename longer. 

Recompression using the flac executable does something similar.

**Comment by PacoH** [comment]
Oh, I see.
