### ISSUE TITLE
metaflac - Remove all tags and artwork (except vendor tag)

### ISSUE THREAD

**Issue by Perplexer1** [xiph/flac#651]
This will be a feature request I guess:

I would like to have metaflac.exe remove all tags and the picture / artwork, except the vendor tag, from my FLAC files. As flexible as the tool is, it apparently can't do this in a single command, so I am currently having to run it twice to accomplish this:

metaflac.exe" --remove-all-tags song.flac
metaflac.exe" --remove --block-type=PICTURE song.flac

Or alternatively: metaflac.exe --remove-all-tags song.flac && metaflac.exe --remove --block-type=PICTURE song.flac

"metaflac.exe --remove-all" comes close, since it removes all the tags and images in one go, but unfortunately also the vendor tag (and other blocks). If only there was a --keep_vendor option available.

The Mp3Tag program does what I want but that is GUI and I'd like to use metaflac.exe since I'm using it in a script.

**Comment by ktmf01** [comment]
So, you want to do something rather specific. What is the problem with running the command twice? The `metaflac` tool would become very complicated if it would allow for all possible transformations in a single pass.

**Comment by Perplexer1** [comment]
I configured a right-click context menu option to "Remove tags" from a FLAC file. I can't call metaflac directly and pass the file name as an argument because that would be just one call. Instead I am having to call a CMD script which then calls metaflac.exe twice. It complicates the situation on my end but it does work. So it's not anything that stops me from achieving the goal. I just thought it would make it simpler for me as the user. If it complicates things on metaflac's side then I guess it can be left as it is.
