### ISSUE TITLE
Confusion about libFLAC version number

### ISSUE THREAD

**Issue by nvishnoiMW** [xiph/flac#652]
Hi all, 

I see in flac/CHANGELOG.md (1.4.3) file: 
https://github.com/xiph/flac/blob/master/CHANGELOG.md#:~:text=As%20there%20have%20been%20additions%20to%20the%20libFLAC%20interfaces%2C%20the%20libFLAC%20version%20number%20is%20incremented%20to%2013.%20The%20libFLAC%2B%2B%20version%20number%20stays%20at%2010:
_As there have been additions to the libFLAC interfaces, the libFLAC version number is incremented to 13. The libFLAC++ version number stays at 10._

However, when I tried to build libFLAC on macOS, the version number is 12 - am I missing something or is this a bug?

Thanks,
Nalini

**Comment by ktmf01** [comment]
Perhaps you're confusing the version number with the so number? Where are you seeing this number 12 exactly?

**Comment by nvishnoiMW** [comment]
The libraries that are generated after the build step are named as follows: 
libFLAC.12.dylib
libFLAC++.10.dylib

Shouldn't their extension match the version number?

**Comment by ktmf01** [comment]
No, that is the soname not the version number. The soname uses the lowest version number with which the library is fully compatible.

So, as the changelog notes, there have only been additions to the libFLAC interface, no removals and no changes to existing elements. That means, version 13 is fully compatible with version 12, and thus the soname uses number 12. This is common practice as far as I know, see https://www.gnu.org/software/libtool/manual/html_node/Libtool-versioning.html

**Comment by nvishnoiMW** [comment]
Hi @ktmf01, 
This is great, thank you for your response. I am marking this issue resolved with your helpful comment. 
Thanks again,
Nalini
