### ISSUE TITLE
Testing file encoded with FLAC 1.3.2 fails when tested with flac.exe 1.4.3

### ISSUE THREAD

**Issue by TT10** [xiph/flac#653]
I was batch-testing thousands of FLAC files using flac.exe 1.4.3 and some were reported as corrupted.

After some testing with 1.3.2 (which is the oldest version currently on my computer) and 1.4.3 (latest...), I noticed the follow results:

- File encoded with flac.exe 1.4.3, tested with 1.4.3 -> OK
- File encoded with flac.exe 1.4.3, tested with 1.3.2 -> OK
- File encoded with flac.exe 1.3.2, tested with 1.3.2 -> OK
- File encoded with flac.exe 1.3.2, tested with 1.4.3 -> Fails: "state = FLAC__STREAM_DECODER_END_OF_STREAM"

Please find some test files here attached.
[20231029-FLAC_testing_possible_bug-Test_files_exept_FLAC_executable_without_wav.zip](https://github.com/xiph/flac/files/13198862/20231029-FLAC_testing_possible_bug-Test_files_exept_FLAC_executable_without_wav.zip)
This sample .zip does NOT include:

- flac.exe 1.3.2 and 1.4.3, since I guess it would make cleaner testing on your side if you redownload them from source.
- My original test .wav file (because GitHub doesn't allow files larger than 25 MB nor .rar nor .7z archives.)

This .zip does include:

- Two .flac files, "Sound1-1.3.2.flac", encoded with flac.exe 1.3.2 and "Sound1-1.4.3.flac", encoded with flac.exe 1.4.3
- Batch files containing the command lines I used to encode and test.

My first thought is that this may be a bug in 1.4.3 testing functions. I am aware that this may be a result a bug from 1.3.2 that would have got corrected later, but I don't follow FLAC's bug tracking so I would like to know... And if it is a 1.4.3 bug, I hope it will get corrected.

**Comment by TT10** [comment]
Sorry, just after posting, I realise that this is the same issue as https://github.com/xiph/flac/issues/487

**Comment by ktmf01** [comment]
Could you check again, both files test 'ok' at my end.

**Comment by TT10** [comment]
I confirm that when running the command in "Test_1.3.2_with_flac_exe_1.4.3.bat"

Copyright (C) 2000-2009  Josh Coalson, 2011-2023  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

Test_1.3.2_with_flac_exe_1.3.2.bat: *** Got error code 0:FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC

> The input file is either not a FLAC file or is corrupted.  If you are
> convinced it is a FLAC file, you can rerun the same command and add the
> -F parameter to try and recover as much as possible from the file.
> 
> 
> Test_1.3.2_with_flac_exe_1.3.2.bat: ERROR while decoding metadata
>                                     state = FLAC__STREAM_DECODER_END_OF_STREAM

**Comment by H2Swine** [comment]
EAC has a checkbox to add ID3, and if you selected that, you would likely trigger a #487 situation.

**Comment by TT10** [comment]
Thank you, this it right. I compared using files that pass testing and files that don't. Those that pass testing only have "FLAC" metatags, while those that don't have "FLAC ID3v2 ID3v1".

Is there a way I can remove "ID3v2 ID3v1" with removing "FLAC" meta data?

**Comment by TT10** [comment]
Just thought about this right now: I'm still thinking that this is a "bug"... As I read in 1.4.2 changelog, I think, that -t now warns if ID3 tags are present. There is indeed a warning. But if we get a warning for one thing, the testing of the audio part should still pass. Also because, if I simply remove the ID3 tags (as mentioned in my previous reply), the file then passes testing.

**Comment by JohnLGalt** [comment]
Might look into MetaBrainz' Picard. I've stopped using any other tagging solution, as it just works and works correctly.

However, I'd also need to run your verification analysis on my FLAC files made via EAC, both prior to tagging as well as after tagging (and renaming and moving to my defined folder structure).

I'll grab your test file from the OP and see what comes out on my end.

**Comment by ktmf01** [comment]
> Just thought about this right now: I'm still thinking that this is a "bug"...

Yes, that is why #478 is still open

> As I read in 1.4.2 changelog, I think, that -t now warns if ID3 tags are present.

It says a warning is added for ID3v2. But it seems your files have ID3v1 tags, which are currently not detected. FLAC versions prior to 1.4.0 would just stop decoding if the number of samples specified in the streaminfo block was reached, but this resulted in a number of problems. In FLAC 1.4.0 and above, the FLAC decoder keeps decoding. It then stumbles on an ID3v1 block because it doesn't recognize it and tries to decode it as if it were audio.

**Comment by JohnLGalt** [comment]
> The files in the OP won't help you as they are not EAC files. They are generated sounds encoded directly through flac.exe. I may try ripping some more test files from some copyright-free music CD, when I find time.

No need (for me) - I have _**tons**_ of files (hundreds of GB worth) that I can test myself, plus I have both EAC and CUERipper, so I can test with both, and see if it is worth going back to CUERipper or stick with EAC. I also have tons of discs I can RIP or reRIP as needed.

I just wanted your scripts themselves for testing, not the files you tested with, in order to keep the testing consistent.
