### ISSUE TITLE
how is libFLAC cross compiled?

### ISSUE THREAD

**Issue by rew1ndustry** [xiph/flac#660]
need to build flac for multiple different arm devices.

cmake is not producing the standard cross compiler macros in the generated makefiles.

all i can find is some sort of automagic that appears to be guessing the host compiler.

can this be told what compiler to use?

or how do i resolve this?

**Comment by ktmf01** [comment]
I usually cross-compile through the autotools build system, see https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html

I have no experience cross-compiling with CMake.

**Comment by rew1ndustry** [comment]
flac requires cmake, according to the README.

cannot find any "configure" for autotools anywhere in the flac project, although there is a configure.ac in the root folder, and i presume cmake must interface with this somehow.

unfortunately, i have very little experience of cmake also, and i do not understand how this is done.

**Comment by ktmf01** [comment]
Please read this part: https://github.com/xiph/flac#building-with-gnu-autotools

**Comment by rew1ndustry** [comment]
haie, thank you very much for your patience, sorry to have wasted your time - i really should have noticed that part.

and thank you very much for flac - words fail - it is so very useful.
