### ISSUE TITLE
Documentation at xiph.org has en dashes – where there should be double dash --

### ISSUE THREAD

**Issue by H2Swine** [xiph/flac#671]
Probably auto-formatted from a tool that converts -- to –
That could confuse people into using single dashes where they should use double. Anyway, I ran a replace on
https://xiph.org/flac/documentation_tools_flac.html and https://xiph.org/flac/documentation_tools_metaflac.html and attached them.

[documentation_tools.zip](https://github.com/xiph/flac/files/14379224/documentation_tools.zip)

**Comment by ktmf01** [comment]
Actually, it is the web server software that makes this conversion. The file that is being served is here: https://github.com/xiph/flac-website/blob/main/documentation_tools_flac.md

The easiest way to fix this is probably by wrapping those options with backticks, so they are rendered with monospace fonts.
