### ISSUE TITLE
Doxygen is unable to build documentation from git

### ISSUE THREAD

**Issue by jonathan-alvaro** [xiph/flac#679]
Hi, I built libFlac from source and I would also like to generate the documentation for reference. But, whenever I run doxygen, I get the following error:
```
error: tag HTML_FOOTER: footer file '@top_srcdir@/doc/doxygen.footer.html' does not exist
```
I tried to find information on why doxygen is unable to find this file (even though it exists). But, I'm unable to find an explanation on what `@top_srcdir@` is. Is this an issue with the Doxyfile? Or am I running doxygen wrong?

Command used to invoke doxygen:
`doxygen doc/Doxyfile.in`

**Comment by ktmf01** [comment]
First run `./autogen.sh`,  then `./configure`. Configure will at some point output the following:

```
config.status: creating doc/Doxyfile
```

It creates Doxyfile from Doxyfile.in. Doxygen is normally also run during building with make or CMake

**Comment by jonathan-alvaro** [comment]
Ah, I see. I tried redoing the `make` step. It seems that I did not have doxygen when I ran `cmake` for the first time, leading to the generated make command not generating the docs.
