### ISSUE TITLE
CRC update performance gain ?

### ISSUE THREAD

**Issue by soundchekk** [xiph/flac#69]
According to
https://www.phoronix.com/scan.php?page=news_item&px=Faster-FLAC-Ogg-CRC-Performance

5% performance gain should be expected on flacs. 
I've seen that the patch has been integrated and committed into the master branch

I did some performance tests on Ubuntu (18.04/gcc 7.3.0/Broadwell NUC) and couldn't get more then 2% gain out of the change. 

OK. It's better then nothing. Still it's not 5% as suggested.

Keep up your great work.

Encoding test:

*****************************
*** DURATION:00:06:28.93
*** SAMPLERATE:44100
*** BITRATE:24
*** COMPRESSION:5

****************************
Binary = /tmp/flac-ubuntu-10-2017

real	0m1,259s
user	0m1,210s
sys	0m0,049s

****************************
Binary = /tmp/flac-newcrc-git-master-05-2018

real	0m1,244s
user	0m1,187s
sys	0m0,057s
**********************************

All files located on tmpfs.

**Comment by soundchekk** [comment]
My post is not a complaint. It's a feedback! 

It seems that the author of the patch has been in close contact to Phoronix about it. That's why I 
linked the article. 

I was just wondering if something went wrong with that patch - or on my side compiling the source or running the app - just to make sure there is no issue!

I'm running an i5 Broadwell.

**Comment by erikd** [comment]
Since you are running on i5 i would suspect that benchmarking was done on the i7.

**Comment by soundchekk** [comment]
I just ran the test on a PI3 running ALARM. 
Same audio file and conversion parameters. 
gcc is 8.1.0

I ran the test 3 times. Below results are reflecting the trend. 

Result:
****************************
Binary = /tmp/flac-alarm

real	0m25.707s
user	0m25.233s
sys	0m0.430s

****************************
Binary = /tmp/flac-newcrc-alarm

real	0m25.204s
user	0m24.816s
sys	0m0.350s


It's basically again around 2% on a factor 20 slower machine.  
On the first glance that rules out CPU related differences.

**Comment by enzo1982** [comment]
The relative performance gains with the new CRC method are bigger, the faster the FLAC encoder already is. So you need to enable nasm and intrinsics optimizations when compiling FLAC to observe the advertised or even higher speed gains.

I compiled FLAC with nasm and SSE2 optimizations enabled for my tests. If you compiled it without the -msse2 flag and/or without nasm installed, you will observer much lower relative gains. On the other hand, compiling with AVX2 optimizations (and nasm) might get you even higher relative gains.

**Comment by soundchekk** [comment]
While compiling -- NASM MSSE2 even march=BROADWELL were assigned.
flac source is taken from git again.


Below you'll find a new benchmark now using "perf" executing the same tasks 10 times.

Result: No differences at all.

Perhaps you can outline somewhere what you've been doing.

*******************************************

Binary = /tmp/flac-ubu

 Performance counter stats for '/tmp/flac-ubu --totally-silent --compression-level-5 -f -o /tmp/test.flac.flac-ubu /tmp/test.wav' (10 runs):

       1242,199775      task-clock (msec)         #    1,000 CPUs utilized            ( +-  0,23% )
                 7      context-switches          #    0,006 K/sec                    ( +- 18,12% )
                 0      cpu-migrations            #    0,000 K/sec                    ( +- 66,67% )
               195      page-faults               #    0,157 K/sec                    ( +-  0,43% )
     3.316.402.438      cycles                    #    2,670 GHz                      ( +-  0,10% )
     7.192.078.879      instructions              #    2,17  insn per cycle           ( +-  0,02% )
       542.494.396      branches                  #  436,721 M/sec                    ( +-  0,05% )
        11.927.365      branch-misses             #    2,20% of all branches          ( +-  0,03% )

       1,242543408 seconds time elapsed                                          ( +-  0,23% )


****************************
Binary = /tmp/flac-newcrc-opt

 Performance counter stats for '/tmp/flac-newcrc-opt --totally-silent --compression-level-5 -f -o /tmp/test.flac.flac-newcrc-opt /tmp/test.wav' (10 runs):

       1247,733832      task-clock (msec)         #    1,000 CPUs utilized            ( +-  0,34% )
                 6      context-switches          #    0,005 K/sec                    ( +- 14,18% )
                 1      cpu-migrations            #    0,000 K/sec                    ( +- 56,66% )
               196      page-faults               #    0,157 K/sec                    ( +-  0,41% )
     3.333.416.025      cycles                    #    2,672 GHz                      ( +-  0,08% )
     7.193.209.501      instructions              #    2,16  insn per cycle           ( +-  0,02% )
       542.743.930      branches                  #  434,984 M/sec                    ( +-  0,05% )
        11.932.164      branch-misses             #    2,20% of all branches          ( +-  0,02% )

       1,248098808 seconds time elapsed                                          ( +-  0,34% )


****************************
Binary = /tmp/flac-newcrc-march-nasm

 Performance counter stats for '/tmp/flac-newcrc-march-nasm --totally-silent --compression-level-5 -f -o /tmp/test.flac.flac-newcrc-march-nasm /tmp/test.wav' (10 runs):

       1245,408687      task-clock (msec)         #    1,000 CPUs utilized            ( +-  0,50% )
                 7      context-switches          #    0,005 K/sec                    ( +- 16,66% )
                 1      cpu-migrations            #    0,000 K/sec                    ( +- 36,85% )
               196      page-faults               #    0,157 K/sec                    ( +-  0,33% )
     3.312.628.162      cycles                    #    2,660 GHz                      ( +-  0,08% )
     7.194.298.720      instructions              #    2,17  insn per cycle           ( +-  0,02% )
       543.000.350      branches                  #  436,002 M/sec                    ( +-  0,05% )
        11.948.669      branch-misses             #    2,20% of all branches          ( +-  0,06% )

       1,245746599 seconds time elapsed                                          ( +-  0,49% )

####################################################################


Here is my script:

IF="/tmp/test.wav"
OF="/tmp/test.flac"

DURATION="$(soxi -d $IF)"
BITRATE="$(soxi -b $IF)"
SAMPLERATE="$(soxi -r $IF)"

COMPRESSIONLEVEL="5"

echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

echo "****************************"
echo "*** DURATION:	$DURATION"
echo "*** SAMPLERATE:	$SAMPLERATE"
echo "*** BITRATE:	$BITRATE"
echo "*** COMPRESSION:	$COMPRESSIONLEVEL"

rm $OF.* 2>/dev/null

for i in flac-ubu flac-newcrc-opt flac-newcrc-march-nasm ; do
   BIN="/tmp/$i"
   echo "****************************"
   echo "Binary = $BIN"
   perf stat -r 10 -B $BIN --totally-silent --compression-level-$COMPRESSIONLEVEL -f -o $OF.$i $IF
   sleep 3
   sync
   echo 
done

**Comment by lvqcl** [comment]
> *** BITRATE:24

BTW, it's bit depth, not bitrate.

Also, 24-bit en- and decoding is noticeably slower than 16-bit, so maybe that's why you don't see 5% speed gain. Try with 16-bit input file.

**Comment by soundchekk** [comment]
I really appreciate your input and suggestions. ;)

NASM etc was installed. I already did set the CFLAGS to march=BROADWELL
I did try 24 vs 16bit. And yep -- I'm not that st... ;)

I wasn't aware though that my new flac binary requires it's own libflac!?!? 

However....

... I followed latest suggestions and...

...here comes the result comprising of everything that's been suggested.

****************************
24BIT
****************************
Binary = /tmp/flac-ubu

 Performance counter stats for '/tmp/flac-ubu --totally-silent --compression-level-5 -f -o /tmp/test.flac.flac-ubu /tmp/test.wav' (10 runs):

       1129,350100      task-clock:u (msec)       #    1,000 CPUs utilized            ( +-  0,19% )
                 0      context-switches:u        #    0,000 K/sec                  
                 0      cpu-migrations:u          #    0,000 K/sec                  
               181      page-faults:u             #    0,161 K/sec                    ( +-  0,29% )
     2.872.273.887      cycles:u                  #    2,543 GHz                      ( +-  0,07% )
     5.867.677.270      instructions:u            #    2,04  insn per cycle           ( +-  0,00% )
       510.348.578      branches:u                #  451,896 M/sec                    ( +-  0,00% )
        11.421.073      branch-misses:u           #    2,24% of all branches          ( +-  0,08% )

       1,129767628 seconds time elapsed                                          ( +-  0,19% )


****************************
Binary = /tmp/flac-static-broadwell

 Performance counter stats for '/tmp/flac-static-broadwell --totally-silent --compression-level-5 -f -o /tmp/test.flac.flac-static-broadwell /tmp/test.wav' (10 runs):

       1136,531976      task-clock:u (msec)       #    1,000 CPUs utilized            ( +-  0,17% )
                 0      context-switches:u        #    0,000 K/sec                  
                 0      cpu-migrations:u          #    0,000 K/sec                  
               176      page-faults:u             #    0,155 K/sec                    ( +-  0,21% )
     2.890.457.628      cycles:u                  #    2,543 GHz                      ( +-  0,07% )
     6.621.484.817      instructions:u            #    2,29  insn per cycle           ( +-  0,00% )
       719.932.976      branches:u                #  633,447 M/sec                    ( +-  0,00% )
        11.334.851      branch-misses:u           #    1,57% of all branches          ( +-  0,04% )

       1,136866434 seconds time elapsed                                          ( +-  0,17% )

**************************************
16BIT
**************************************
Binary = /tmp/flac-ubu

 Performance counter stats for '/tmp/flac-ubu --totally-silent --compression-level-5 -f -o /tmp/test.flac.flac-ubu /tmp/test.wav' (10 runs):

        924,723388      task-clock:u (msec)       #    1,000 CPUs utilized            ( +-  0,12% )
                 0      context-switches:u        #    0,000 K/sec                  
                 0      cpu-migrations:u          #    0,000 K/sec                  
               179      page-faults:u             #    0,193 K/sec                    ( +-  0,26% )
     2.341.469.136      cycles:u                  #    2,532 GHz                      ( +-  0,07% )
     4.489.843.618      instructions:u            #    1,92  insn per cycle           ( +-  0,00% )
       384.003.193      branches:u                #  415,263 M/sec                    ( +-  0,00% )
        11.348.270      branch-misses:u           #    2,96% of all branches          ( +-  0,06% )

       0,925034917 seconds time elapsed                                          ( +-  0,12% )


****************************
Binary = /tmp/flac-static-broadwell

 Performance counter stats for '/tmp/flac-static-broadwell --totally-silent --compression-level-5 -f -o /tmp/test.flac.flac-static-broadwell /tmp/test.wav' (10 runs):

        925,155059      task-clock:u (msec)       #    1,000 CPUs utilized            ( +-  0,22% )
                 0      context-switches:u        #    0,000 K/sec                  
                 0      cpu-migrations:u          #    0,000 K/sec                  
               176      page-faults:u             #    0,190 K/sec                    ( +-  0,22% )
     2.339.510.467      cycles:u                  #    2,529 GHz                      ( +-  0,09% )
     5.001.072.397      instructions:u            #    2,14  insn per cycle           ( +-  0,00% )
       522.205.698      branches:u                #  564,452 M/sec                    ( +-  0,00% )
        11.272.718      branch-misses:u           #    2,16% of all branches          ( +-  0,06% )

       0,925409636 seconds time elapsed                                          ( +-  0,22% )

****************************

As you can see nothing changed with the static binary. ( Actually it's been even slower in one case!)
As you can also see nothing changes on 16 vs. 24bit. Except for a longer conversion time for that
obviously bigger file.

Am I still missing something here?

One thing I could still try is to compile an older commit - the last one without the CRC optimizations - instead of the Ubuntu binary. 

However. I still havn't seen anybody - from the developer side - posting a benchmarking setup showing and proving the promised performance gain.

**Comment by enzo1982** [comment]
I think you might still be comparing the fast CRC version to itself.

If you've built and installed the dynamic library version before, you will have a libFLAC.so built with the CRC patches in your library path. The Ubuntu flac binary is built with dynamic linkage too, so it will use a libFLAC.so from your library path, possibly the one you built before.

So yes, please do not compare against your flac-ubu binary, but against a version without the CRC patches built the same way as the flac-static-broadwell binary.

**Comment by soundchekk** [comment]
enzo1982 - I think you got a point. ;)

1. I today reinstalled the Ubuntu flac and libs
2. I then downloaded the Ubuntu sources and did a static compilation
3. And I fetched the flac git once more and compiled that statically
4. I ran the encode and decode benchmarks

And here comes the result:
****************************
Binary = /tmp/flac-1.3.2-ubu

 Performance counter stats for '/tmp/flac-1.3.2-ubu --totally-silent --compression-level-5 -f -o /tmp/test16.flac.flac-1.3.2-ubu /tmp/test16.wav' (10 runs):

       1031,998175      task-clock (msec)         #    1,000 CPUs utilized            ( +-  0,07% )
                 6      context-switches          #    0,006 K/sec                    ( +- 16,01% )
                 1      cpu-migrations            #    0,001 K/sec                    ( +- 36,85% )
               192      page-faults               #    0,186 K/sec                    ( +-  0,41% )
     2.757.615.568      cycles                    #    2,672 GHz                      ( +-  0,07% )
     5.792.144.336      instructions              #    2,10  insn per cycle           ( +-  0,03% )
       423.397.735      branches                  #  410,270 M/sec                    ( +-  0,06% )
        11.845.109      branch-misses             #    2,80% of all branches          ( +-  0,03% )

       1,032314326 seconds time elapsed                                          ( +-  0,07% )


****************************
Binary = /tmp/flac-1.3.2-ubu-static

 Performance counter stats for '/tmp/flac-1.3.2-ubu-static --totally-silent --compression-level-5 -f -o /tmp/test16.flac.flac-1.3.2-ubu-static /tmp/test16.wav' (10 runs):

       1046,480818      task-clock (msec)         #    1,000 CPUs utilized            ( +-  0,07% )
                 5      context-switches          #    0,005 K/sec                    ( +- 14,30% )
                 0      cpu-migrations            #    0,000 K/sec                    ( +- 44,72% )
               184      page-faults               #    0,176 K/sec                    ( +-  0,24% )
     2.801.189.305      cycles                    #    2,677 GHz                      ( +-  0,07% )
     4.776.156.386      instructions              #    1,71  insn per cycle           ( +-  0,03% )
       403.541.845      branches                  #  385,618 M/sec                    ( +-  0,06% )
        11.491.004      branch-misses             #    2,85% of all branches          ( +-  0,05% )

       1,046770327 seconds time elapsed                                          ( +-  0,07% )


****************************
Binary = /tmp/flac-git-static

 Performance counter stats for '/tmp/flac-git-static --totally-silent --compression-level-5 -f -o /tmp/test16.flac.flac-git-static /tmp/test16.wav' (10 runs):

        923,622729      task-clock (msec)         #    1,000 CPUs utilized            ( +-  0,09% )
                 4      context-switches          #    0,005 K/sec                    ( +- 18,62% )
                 0      cpu-migrations            #    0,001 K/sec                    ( +- 33,33% )
               180      page-faults               #    0,195 K/sec                    ( +-  0,21% )
     2.472.003.020      cycles                    #    2,676 GHz                      ( +-  0,07% )
     5.108.543.740      instructions              #    2,07  insn per cycle           ( +-  0,03% )
       541.381.977      branches                  #  586,151 M/sec                    ( +-  0,05% )
        11.537.502      branch-misses             #    2,13% of all branches          ( +-  0,03% )

       0,923934894 seconds time elapsed      

****************************************************************************

Finally. The results show an around 11% increase on the encode - against both Ubuntu versions

****************************
And I also did the decode test:

****************************
Binary = /tmp/flac-1.3.2-ubu

 Performance counter stats for '/tmp/flac-1.3.2-ubu --totally-silent -d -f -o /tmp/test16.wav.flac-1.3.2-ubu /tmp/test16.flac' (10 runs):

        566,553464      task-clock (msec)         #    0,999 CPUs utilized            ( +-  0,24% )
                 4      context-switches          #    0,007 K/sec                    ( +- 15,09% )
                 0      cpu-migrations            #    0,000 K/sec                    ( +- 66,67% )
               128      page-faults               #    0,225 K/sec                    ( +-  0,50% )
     1.511.998.785      cycles                    #    2,669 GHz                      ( +-  0,16% )
     3.580.347.563      instructions              #    2,37  insn per cycle           ( +-  0,07% )
       214.363.822      branches                  #  378,365 M/sec                    ( +-  0,20% )
         5.272.298      branch-misses             #    2,46% of all branches          ( +-  0,05% )

       0,566851320 seconds time elapsed                                          ( +-  0,24% )


****************************
Binary = /tmp/flac-1.3.2-ubu-static

 Performance counter stats for '/tmp/flac-1.3.2-ubu-static --totally-silent -d -f -o /tmp/test16.wav.flac-1.3.2-ubu-static /tmp/test16.flac' (10 runs):

        516,027060      task-clock (msec)         #    0,999 CPUs utilized            ( +-  0,97% )
                 3      context-switches          #    0,006 K/sec                    ( +- 13,13% )
                 0      cpu-migrations            #    0,000 K/sec                    ( +-100,00% )
               119      page-faults               #    0,231 K/sec                    ( +-  0,37% )
     1.363.596.089      cycles                    #    2,642 GHz                      ( +-  0,15% )
     3.378.787.107      instructions              #    2,48  insn per cycle           ( +-  0,08% )
       213.400.313      branches                  #  413,545 M/sec                    ( +-  0,21% )
         5.093.116      branch-misses             #    2,39% of all branches          ( +-  0,03% )

       0,516293944 seconds time elapsed                                          ( +-  0,97% )


****************************
Binary = /tmp/flac-git-static

 Performance counter stats for '/tmp/flac-git-static --totally-silent -d -f -o /tmp/test16.wav.flac-git-static /tmp/test16.flac' (10 runs):

        488,574913      task-clock (msec)         #    0,999 CPUs utilized            ( +-  0,37% )
                 2      context-switches          #    0,005 K/sec                    ( +- 20,10% )
                 0      cpu-migrations            #    0,000 K/sec                  
               118      page-faults               #    0,241 K/sec                    ( +-  0,31% )
     1.297.780.573      cycles                    #    2,656 GHz                      ( +-  0,16% )
     3.044.344.214      instructions              #    2,35  insn per cycle           ( +-  0,09% )
       180.420.141      branches                  #  369,278 M/sec                    ( +-  0,24% )
         5.077.955      branch-misses             #    2,81% of all branches          ( +-  0,16% )

       0,488829035 seconds time elapsed                                          ( +-  0,37% )

*********************************************

And on the decode a 14% gain against the stock dynamic linked Ubuntu was found 
And now it comes: 

A "5%" increase  against the Ubuntu sources compiled with "-O3 -march=broadwell"  
And this seems to prove that just the different sources compiled under the same conditions
do show a 5% gain - on the decode part. The gain most probably will even increase further
if you compare against a less optimized binary.

Thx to all of you supporting me on that exercise. And of course thx to the designer(s) for 
introducing this enhancement.

And sorry for the confusion.

**Comment by enzo1982** [comment]
Glad you were able to verify my results in the end. :)

Please close this issue if it is solved for you now.

**Comment by soundchekk** [comment]
Done!
