### ISSUE TITLE
FLAC conversion utility not available 

### ISSUE THREAD

**Issue by 16bitOni** [xiph/flac#701]
While trying to work with speech recognition the error was showing ."[FLAC conversion utility not available - consider installing the FLAC command line application](https://stackoverflow.com/questions/49737909/flac-conversion-utility-not-available-consider-installing-the-flac-command-lin)"
Even after installing Flac in windows and added to the path

**Comment by ktmf01** [comment]
What happens when you open a plain command line, type `flac` and press enter?
