### ISSUE TITLE
Consider providing official statically linked builds for Windows

### ISSUE THREAD

**Issue by fgimian** [xiph/flac#703]
Hey there, thanks so much for your work on FLAC.

I'm aware that various people have created static builds of FLAC (e.g. RareWares), but in my testing, I have found the official builds to be faster than the most standard 3rd party builds (e.g. without AVX2 enabled).

I'd like to package FLAC for winget (I recently packaged LAME), but currently winget only supports statically linked binaries.

Would you consider making an official statically linked binary download available as an option please?

Thanks a lot
Fotis

**Comment by ktmf01** [comment]
> I'm aware that various people have created static builds of FLAC (e.g. RareWares), but in my testing, I have found the official builds to be faster than the most standard 3rd party builds (e.g. without AVX2 enabled).

I have seen a lot of testing, and in most such static builds are on par or faster. Maybe you could share some results?

> but currently winget only supports statically linked binaries.

That seems like an odd design choice?

> Would you consider making an official statically linked binary download available as an option please?

I'd prefer not to, to be honest. That way I can test four executables (32-bit and 64-bit flac and metaflac) and provide binaries and DLLs. If I would also release static binaries, that would amount to double the amount of testing.

**Comment by ktmf01** [comment]
Maybe using an executable packer would be a good idea here?

**Comment by fgimian** [comment]
Apologies for the late reply.

> I have seen a lot of comparisons, and in most such static builds are on par or faster. Maybe you could share some results?

Since posting this issue, I have been in touch with John Edwards of RareWares and done several benchmarks. The reason his older builds were slower was that they were compiled with the Intel 19.0 compiler instead of GCC. John has since posted GCC builds which are on par with the official builds in terms of performance.

> > but currently winget only supports statically linked binaries.
> 
> That seems like an odd design choice?

I completely agree with you 😢

> > Would you consider making an official statically linked binary download available as an option please?
> 
> I'd prefer not to, to be honest. That way I can test four executables (32-bit and 64-bit flac and metaflac) and provide binaries and DLLs. If I would also release static binaries, that would amount to double the amount of testing.

I completely understand.

> Maybe using an executable packer would be a good idea here?

That could work yeah. Otherwise we could wait for the following winget issue to be solved https://github.com/microsoft/winget-cli/issues/2711

Huge thanks
Fotis

**Comment by fgimian** [comment]
Just an FYI that winget has now added support for executable that link to a DLL at runtime so no longer think this is necessary, closing.

**Comment by fgimian** [comment]
@ktmf01 Just an FYI that the official FLAC builds are now in WinGet! Check out my PR which was accepted here: https://github.com/microsoft/winget-pkgs/pull/194574

You may install it via:

```
winget install Xiph.FLAC
```

It would be awesome if we could keep that up to date with new releases. 😄 

Cheers
Fotis

**Comment by ktmf01** [comment]
Thanks! Looking at that PR, it seems it took a lot of effort 😅

**Comment by fgimian** [comment]
> Thanks! Looking at that PR, it seems it took a lot of effort 😅

Just a little extra persistence yeah, but we got there in the end. One of the things that made it a bit more challenging is the fact that the download URL is on a different domain to the main website.

I'm hoping it will be trivial to keep updated now that it's in. 😊

Cheers
Fotis
