### ISSUE TITLE
On Windows, none-ascii input filename will cause the filename to be truncated in log output if stderr is not tty

### ISSUE THREAD

**Issue by sagan** [xiph/flac#713]
## Environment:

flac-1.4.3 + Windows 10 / 11.

## Description

If the input filename contains non-ASCII character, the stderr output of flac.exe will have the filename truncated before first non-ASCII character, if stderr is not tty (cmd / powershell terminal).

For example, set a wav filename to `01-声.wav`, the `声` (A Kanji which means "sound") is a non-ASCII character.

Use flac.exe to convert this file to flac:

```
flac --force "01-声.wav"
```

If the command was executed in cmd / powershell, the output will be ok:

```
C:\tmp\a>flac --force "01-声.wav"

flac 1.4.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2023  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

01-声.wav: wrote 98413 bytes, ratio=0.744
```

However, if the stderr was piped to file, or the flac.exe process is executed by other program, the output will have wrong filename:

```
flac --force "01-声.wav" 2>stderr.txt
```

stderr.txt:

```

flac 1.4.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2023  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

01-wrote 98413 bytes, ratio=0.744
```

## Futher more

If flac failed to process the input file, the whole error message will be lost in this case.

E.g. trying to convert a 32 float wav to flac:

```
flac --force "01 注意事項.wav"
```

Normal stderr output in cmd:

```
flac 1.4.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2023  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

01 注意事項.wav: ERROR: unsupported format type 3
```

Output if stderr was piped to file

```

flac 1.4.3
Copyright (C) 2000-2009  Josh Coalson, 2011-2023  Xiph.Org Foundation
flac comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions.  Type `flac' for details.

01 
```

**Comment by ktmf01** [comment]
Thanks for reporting, I will try to fix this.

**Comment by petterreinholdtsen** [comment]
[Martijn van Beurden]
> Thanks for reporting, I will try to fix this.

Sound like the output is in UTF-16 or UTF-32, causing null bytes to show
up in the string.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by ktmf01** [comment]
@sagan, are you able to compile the changes in #714 or would you like me to provide a compile? It would be great if you could check whether that fix works.

**Comment by sagan** [comment]
I tried to compile https://github.com/ktmf01/flac/tree/fix-utf8-output-redirection on Windows 11 using cmake + Visual Studio Community 2022

The code failed to comiple with an 'identifier "options" is undefined' error in [flac/src/metaflac/operations.c](https://github.com/ktmf01/flac/blob/db662c3fd44da840a7c7b1dfa9b5808c54b2e317/src/metaflac/operations.c#L829). This can be fixed by change the signature of write_metadata_binary to pass utf8_convert to it as a arg, after which the build successes.

However, the generated flac.exe fails to process any input file with an assert error:


<img width="324" alt="Untitled" src="https://github.com/xiph/flac/assets/1836852/d203c3c7-d975-4719-9090-a8fa95781f12">

**Comment by ktmf01** [comment]
> The code failed to comiple with an 'identifier "options" is undefined' error in [flac/src/metaflac/operations.c](https://github.com/ktmf01/flac/blob/db662c3fd44da840a7c7b1dfa9b5808c54b2e317/src/metaflac/operations.c#L829). This can be fixed by change the signature of write_metadata_binary to pass utf8_convert to it as a arg, after which the build successes.

Oops. Apparently I didn't check that last change.


> However, the generated flac.exe fails to process any input file with an assert error:
> <img alt="Untitled" width="324" src="https://private-user-images.githubusercontent.com/1836852/342175041-d203c3c7-d975-4719-9090-a8fa95781f12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMDg0MTksIm5iZiI6MTcxOTIwODExOSwicGF0aCI6Ii8xODM2ODUyLzM0MjE3NTA0MS1kMjAzYzNjNy1kOTc1LTQ3MTktOTA5MC1hOGZhOTU3ODFmMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMDU0ODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjIxZmNjMmZlMTNhZDllZWU5MjM1OWIxN2FhNTZmNmFhMGQ3ZTMyYTVlMWE1ZWM4N2NlYmNkODgzMWQzZmQ0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3Ts24WvHfWJocc9mJ8-Y4ITLMyVzo5qz_rdfhulDrlw">

This seems linked, I will investigate: https://stackoverflow.com/questions/45575863/how-to-print-utf-8-strings-to-stdcout-on-windows

**Comment by ktmf01** [comment]
It was a little more difficult than I had anticipated, but I think #714 should now work properly. @sagan, could you test again for me?

**Comment by sagan** [comment]
I just compiled https://github.com/ktmf01/flac/tree/fix-utf8-output-redirection on Windows. It seems it's working properly now. The output file of redirected stderr is UTF-8 encoding and have non-ASCII characters stored correctly.

Thank you!
