### ISSUE TITLE
Compression level - "No compression"

### ISSUE THREAD

**Issue by soundchekk** [xiph/flac#73]
The dbPoweramp designer desgined a compression level "no compression" for flac some time ago.
There seem to be people around appreciating this feature. It also shouldn't be too difficult
to make it happen inside flac. 

dbPoweramp is offering this feature exclusive as it seems.

As we all know the known flac compression level "0" is not "0". That might be a bit misleading for some people.
But that's not the issue here.

It would be nice to have a compression level "no compression".
Basically an umcompressed PCM track (.wav) in a flac container.

* .wav files could potentially be neglected altogether
* tagging features, replaygain etc. of flac could be used  throughout the lossless PCM collection
* postprocessing could be more generalized (less filetypes) in some cases
* some might use it for this or test purpose 

I read somewhere that "no compression" can be accomplished by using certain options of
the flac binary. I didn't manage to come up with a positive result on that one. 

My questions:

1. Is there a set of options to flac which let me generate an uncompressed flac data file with just a 
PCM block and the tags inside.

2. Would you guys consider it doable to introduce a single option to flac to accomplish a "no compression" file. I'd appreciate it.

SC

**Comment by lvqcl** [comment]
Honestly, I can't see any reason why "uncompressed" flac is better than "compressed".

> .wav files could potentially be neglected altogether

Already possible with usual, "compressed" flac.
> tagging features, replaygain etc. of flac could be used throughout the lossless PCM collection

The same.
> postprocessing could be more generalized (less filetypes) in some cases

What postprocessing? and why it's only applicable to "uncompressed" flacs?


> 1. Is there a set of options to flac which let me generate an uncompressed flac data file with just a
PCM block and the tags inside.

`-l 0 --disable-constant-subframes --disable-fixed-subframes`  will create uncompressed flac (most of the time).

> 2. Would you guys consider it doable to introduce a single option to flac to accomplish a "no compression" file. I'd appreciate it.

I hope that FLAC development won't be driven by audiophoolery. After all, encoding and decoding speed of "uncompressed" files are comparable to files created by flac -0, but the former are noticeably bigger. Hardly an improvement.

**Comment by soundchekk** [comment]
I came across the solution you're outlining before. And also tested it.

Here's what I just did again:

flac -f --compression-level-0 -o test24-l0.flac test24.wav 
flac -f --compression-level-0 --disable-constant-subframes --disable-fixed-subframes -o test24-nocomp.flac test24.wav 

test24.wav		= 99MB
test24-l0.flac		= 40MB
test24-nocomp.flac	= 66MB

"nocomp" !?!? reflects your suggestion. 
By looking at the filesize, I'm wondering if that can be accomplished without compression!?!?

I'd actually be expecting the same of even bigger sizer on the resulting flac!?!?


And. I did also the test on my 16 bit testfile. That one failed:

************************************
test16.wav: wrote 68793322 bytes, ratio=1,003
FAILURE: Compression failed (ratio 1,003, should be < 1.0).
This happens for some files for one or more of the following reasons:
 * Recompressing an existing FLAC from a higher to a lower compression setting.
 * Insufficient input data  (e.g. very short files, < 10000 frames).
 * The audio data is not compressible (e.g. a full range white noise signal).
**************************************
I'm wondering of any of above reasons actually apply here.

**Comment by lvqcl** [comment]
My settings also have `-l 0 ` aka `--max-lpc-order=0` . But it seems that you didn't forget to add it.

> I'd actually be expecting the same or even larger size on the resulting flac with just PCM inside!?!?

I suspect that you took 16-bit file and upconverted it to 24-bit (so lower 8 bits are zeroes). In this case FLAC automatically discovers this and converts the input audio back to 16 bit.

> And. I did also the test on my 16 bit testfile. That one failed:

It's just a warning that resulting file is slightly bigger than the original. But the flac file itself should be ok.

**Comment by lvqcl** [comment]
I decided to test decoding speed of 16-bit flac files, compressed with --compression-level-N presets and uncompressed. (I use foobar2000 and foo_benchmark plugin)

encoding preset / bitrate / decoding speed (rounded to 10x):
```
flac -8:       895 kbps,  510x realtime
flac -7:       896 kbps,  510x realtime
flac -6:       898 kbps,  550x realtime
flac -5:       901 kbps,  550x realtime
flac -4:       903 kbps,  550x realtime
flac -3:       939 kbps,  600x realtime
flac -2:       948 kbps,  610x realtime
flac -1:       952 kbps,  620x realtime
flac -0:       987 kbps,  680x realtime
uncompressed: 1415 kbps,  620x realtime
source WAV:   1411 kbps, 9700x realtime
```
So:
* flac decoding is very fast already
* uncompressed mode won't improve decoding speed

**Comment by soundchekk** [comment]
Your hint on the 24bit 0-padding handling by the flac binary pretty much solved the issue.

I then redid my tests, which I would like to share.

First I generated several flacs from my new 16bit test16.wav.

flac -f --compression-level-0 -o test16-cl0.flac test16.wav 
flac -f --compression-level-5 -o test16-cl5.flac test16.wav 

flac -f --compression-level-0 --disable-constant-subframes --disable-fixed-subframes -o test16-nocomp-cl0.flac test16.wav 
flac -f -l 0 --disable-constant-subframes --disable-fixed-subframes -o test16-nocomp-l0.flac test16.wav 
flac -f -0 --disable-constant-subframes --disable-fixed-subframes -o test16-nocomp-0.flac test16.wav
(same filesize for all 3 above!)

Filesizes:

test16.wav					= 103887884
test16-cl0.flac				=  41017617
test16-cl5.flac				=  39387134

test16-nocomp-l0.flac		= 104165565


As expected the NoCompression file slightly exceeds the .wav original. 

I then executed a perfomance testing. I ran the tests several times.
I used the new CRC optimzed flac build from git sources with gcc opts set to "-O3 -march=broadwell". 

########################################################################
BIN=/tmp/flac-git-opt

echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
sleep 2

for i in test16-cl0.flac test16-cl5.flac test16-nocomp-cl0.flac ; do
   echo "****************************"
   echo "****$i"
   perf stat -r 10 -B $BIN --totally-silent -f -d /tmp/$i
   sleep 3
   sync
   echo 
done

########################################################################

****************************
****test16-cl0.flac

 Performance counter stats for '/tmp/flac-git-opt --totally-silent -f -d /tmp/test16-cl0.flac' (10 runs):

        620,669145      task-clock (msec)         #    0,999 CPUs utilized            ( +-  0,36% )
                 4      context-switches          #    0,007 K/sec                    ( +- 12,77% )
                 0      cpu-migrations            #    0,000 K/sec                  
               102      page-faults               #    0,164 K/sec                    ( +-  0,31% )
     1.659.587.593      cycles                    #    2,674 GHz                      ( +-  0,21% )
     3.544.392.275      instructions              #    2,14  insn per cycle           ( +-  0,00% )
       265.420.089      branches                  #  427,635 M/sec                    ( +-  0,01% )
         7.799.719      branch-misses             #    2,94% of all branches          ( +-  0,12% )

       0,620986301 seconds time elapsed                                          ( +-  0,37% )


****************************
****test16-cl5.flac

 Performance counter stats for '/tmp/flac-git-opt --totally-silent -f -d /tmp/test16-cl5.flac' (10 runs):

        702,953210      task-clock (msec)         #    1,000 CPUs utilized            ( +-  0,28% )
                 5      context-switches          #    0,007 K/sec                    ( +- 14,89% )
                 0      cpu-migrations            #    0,000 K/sec                    ( +- 50,92% )
               120      page-faults               #    0,171 K/sec                    ( +-  0,33% )
     1.879.136.299      cycles                    #    2,673 GHz                      ( +-  0,15% )
     4.430.605.638      instructions              #    2,36  insn per cycle           ( +-  0,00% )
       264.470.255      branches                  #  376,227 M/sec                    ( +-  0,00% )
         7.447.174      branch-misses             #    2,82% of all branches          ( +-  0,07% )

       0,703254931 seconds time elapsed                                          ( +-  0,28% )


****************************
****test16-nocomp-cl0.flac

 Performance counter stats for '/tmp/flac-git-opt --totally-silent -f -d /tmp/test16-nocomp-cl0.flac' (10 runs):

        993,153306      task-clock (msec)         #    1,000 CPUs utilized            ( +-  0,27% )
                 4      context-switches          #    0,005 K/sec                    ( +- 12,06% )
                 0      cpu-migrations            #    0,000 K/sec                    ( +- 55,28% )
               102      page-faults               #    0,103 K/sec                    ( +-  0,32% )
     2.658.086.321      cycles                    #    2,676 GHz                      ( +-  0,25% )
     7.457.070.868      instructions              #    2,81  insn per cycle           ( +-  0,00% )
       920.078.916      branches                  #  926,422 M/sec                    ( +-  0,00% )
         1.298.655      branch-misses             #    0,14% of all branches          ( +-  0,87% )

       0,993540048 seconds time elapsed                                          ( +-  0,27% )


Result:

CL0=0.620986301
CL5=0.703254931   +13.2% 
CLN=0.993540048   +60%


Wow. That's a surprise.  
+60% on the non-compressed flac. It seems that flac is still running a "decode" on a much larger PCM file now.
That's pretty much killing the "nocomp" case... 
...unless something can be done about it. ;) 

Another conclusion. Using CL5 is 13.2% slower than CL0 on the decode. 

If many of us appreciate a 5% performance increase by a new CRC algorithm, choosing the right compression level will have a more then relevant impact on the overall decoding performance.

**Comment by lvqcl** [comment]
> (same filesize for all 3 above!)

Ah, yes. I forgot that `--compression-level-0` includes `-l 0`.

**Comment by soundchekk** [comment]
"...FLAC file cannot store PCM information 'as is'..."
OK. Now we're getting there. And are back to square one.

"...has a downside of increased file size..."
You gotta be kidding!?!? 

"...I don't know FLAC algorithms very well..."
 Perhaps somebody with more in-depth knowledge will join the discussion.

"...most FLAC users don't care about it ..."
Most users would still live in caves if there wouldn't be some geeks out there pushing it.

I do face lots of performance issues on e.g. RPI. Many people use these low steam 
ARM boards for audio nowadays. And to them everything matters.

**Comment by lvqcl** [comment]
> You gotta be kidding!?!?

No. flac level 0 is bigger than level 5 (which is in turn bigger than e.g. level 8).

> Most users would still live in caves if there wouldn't be some geeks out there pushing it.

Doubt it.

> I do face lots of performance issues on e.g. RPI.

Also doubt it. FLAC decoding speed should be much faster than realtime on such CPUs.

**Comment by erikd** [comment]
> "...I don't know FLAC algorithms very well..."
> Perhaps somebody with more in-depth knowledge will join the discussion.

The original author of the FLAC algorithm left the project almost 10 years ago. Those of use who like @lvqcl maintain this code the best we can. @lvqcl in particular has  done a lot of work to optimize the FLAC code for recent Intel CPUs and helped with Windows support.

**Comment by soundchekk** [comment]
Good to get to know about the flac Who'sWho.

Your efforts are highly appreciated.

Since we have the core dev-team around.
 
If any of you wouldn't be interested to look further into this subject we can close the issue. 

At least from my perspective, considering the benchmark results and the knowledge that there's still a lot going on,  running flac with No Compression options doesn't make any sense the way it'd be currently accomplished.

**Comment by erikd** [comment]
I agree. FLAC in "no compression" mode makes no sense at all.

Closing this.
