### ISSUE TITLE
No CMake option to disable building microbenchmark

### ISSUE THREAD

**Issue by dakrk** [xiph/flac#732]
I'm using libFLAC as a Git submodule in a project, and I've noticed that it's building a benchmark_residual binary with no way to disable that. I would like it if there was, as it's pointless for everything to always build it.

(I would've done it but I wasn't sure if it should just follow the `BUILD_TESTING` option because it's outside of the test directory and it's just a benchmark, or if there would be a `BUILD_BENCHMARK` option instead)

**Comment by ktmf01** [comment]
I don't think that benchmark is being used anymore, perhaps best to simply remove it.
