### ISSUE TITLE
Please restart FLAC Internet Draft in IETF

### ISSUE THREAD

**Issue by liyuxi** [xiph/flac#74]
Hi!
Please restart FLAC Internet-Draft,Because
1.FLAC has already widely applied (Microsoft Windows,Google Chrome,Mozilla Firefox and Google Android)
2.FLAC has implemented by libFLAC FFmpeg and more(some DAW software like Adobe Audition)
3.FLAC is a polpular and de-facro,widely applied in lossless
music sevices and lossless audio preservation
4.opus is a standardized audio codec in IETF, its wiki recommend high sampling rate user to use FLAC

**Comment by erikd** [comment]
I do my best to maintain the code, fix bugs and vete and apply PRs. I do not have time to work on the IETF draft. Anyone who does have time is free to do so.

**Comment by ktmf01** [comment]
As the specification is already well underway at https://github.com/ietf-wg-cellar/flac-specification, I'm closing this issue (as the process has clearly been 'restart')
