### ISSUE TITLE
I want `FLAC.so.12`, where can I get it?

### ISSUE THREAD

**Issue by Mq-b** [xiph/flac#742]
I want `FLAC.so.12`, where can I get it?

Because SFML depends on it.

**Comment by petterreinholdtsen** [comment]
[mq白]
> I want `FLAC.so.12`, where can I get it?
>
> Because SFML depends on it.

This sound like a question for people who know the Linux distribution
you use, and not for the flac developers.  Good luck. :)

-- 
Happy hacking,
Petter Reinholdtsen

**Comment by ktmf01** [comment]
Please tell me what kind of operating system you are using.

**Comment by Mq-b** [comment]
> Please tell me what kind of operating system you are using.请告诉我您使用的是哪种操作系统。

Thank you for being: Ubuntu22.04

**Comment by Mq-b** [comment]
This is the SFML version I use: https://github.com/SFML/SFML/releases/tag/2.6.1

**Comment by ktmf01** [comment]
Please follow the tutorial here: https://www.sfml-dev.org/tutorials/2.6/start-linux.php

It proposes to run the command `sudo apt-get install libsfml-dev` on your machine.

**Comment by Mq-b** [comment]
The sudo apt-get install libsfml-dev command gets the version too low.

**Comment by ktmf01** [comment]
You can consider upgrading to Ubuntu 24.04

**Comment by Mq-b** [comment]
The company is currently unable to upgrade the project, sorry. I'll work tomorrow and think of something else, or compile it myself.
