### ISSUE TITLE
size_t used but stddef.h not included in compat.h

### ISSUE THREAD

**Issue by Clownacy** [xiph/flac#76]
I noticed [this commit](https://github.com/ekeeke/Genesis-Plus-GX/commit/12fde25a68fb04460345da97b10127c3d6b8c534) on another project, and figured it'd be worth fixing upstream too.

**Comment by neheb** [comment]
I don't know that this is useful. I checked the musl libc and size_t gets defines in the first header included (unistd.h).

There have been changes since that commit that may have fixed the issue.

**Comment by Clownacy** [comment]
At the time that I opened this issue, this library was used by [the libchdr library](https://github.com/rtissera/libchdr), which in turn was used by various video game console emulators such as [Genesis Plus GX](https://github.com/ekeeke/Genesis-Plus-GX/tree/master/core/cd_hw/libchdr) and [DuckStation](https://github.com/stenzek/duckstation/tree/master/dep/libchdr). Notably, these emulators (or their derivates) are part of the RetroArch project, which provides ports of these emulators to [various platforms](https://retroarch.com/?page=platforms), including legacy ones which are only supported by outdated toolchains.

Though, technically, the change in the commit is less about specifically adding support for an EoL compiler and more about fixing a bug to make the code properly follow the C standard: `size_t` is only guaranteed to be defined by `stddef.h`, `stdio.h`, `stdlib.h`, `string.h`, and `time.h`. This change doesn't just improve compatibility with one decrepit old compiler, but any build environment - old or modern - that doesn't incidentally define `size_t` in the same header file that has allowed this bug to go unnoticed up to this point.

**Comment by Clownacy** [comment]
There shouldn't be any problems involving `stddef.h` not existing on certain platforms: it's been a part of the C standard since at least ANSI C. On platforms that don't conform to the C standard, I'd argue that it's more likely for `stdarg.h` to not exist than `stddef.h`, since `stddef.h` apparently exists solely to provide fundamental definitions like `NULL`, `offsetof`, and `size_t`, whereas `stdarg.h` provides the comparatively niche variadic functions.

**Comment by neheb** [comment]
stddef.h is definitely standard. C++11 has cstddef after all.

**Comment by petterreinholdtsen** [comment]
[Martijn van Beurden]
> The reason I'm hesitant is that I'm not too familiar with specifics of
> the C language like what you just mention, and I was afraid this
> addition might break something else.

Perhaps fall back to the basics as described in
<URL: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_types.h.html >,
and include <sys/types.h> directly instead?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by neheb** [comment]
sys/types.h is POSIX only.
