### ISSUE TITLE
Wave64 metadata application ID should be 0x77363420

### ISSUE THREAD

**Issue by madah81pnz1** [xiph/flac#761]
Wave64 metadata application ID should be 0x77363420, instead of 0x773634C0. The last character is a space, thus has the value 0x20.

The source has always used a space:

https://github.com/xiph/flac/blob/master/src/flac/foreign_metadata.c#L38

`src/flac/foreign_metadata.c:38:const char *FLAC__FOREIGN_METADATA_APPLICATION_ID[FLAC__FOREIGN_METADATA_NUMBER_OF_RECOGNIZED_APPLICATION_IDS] = { "aiff" , "riff", "w64 " };`

The ID is mentioned in the documentation:
https://github.com/xiph/flac/blob/master/doc/foreign_metadata_storage.md?plain=1#L6

Also on the webpage:
https://xiph.org/flac/id.html

But seems to be missing from the website repo? There is no "w64 " or "FLAC Wave64 chunk storage":
https://github.com/xiph/flac-website/blob/main/id.html

**Comment by ktmf01** [comment]
Thanks! I'll have it fixed.

> But seems to be missing from the website repo? There is no "w64 " or "FLAC Wave64 chunk storage": https://github.com/xiph/flac-website/blob/main/id.html

That repo is very much out of date, it should mirror the one at https://gitlab.xiph.org/xiph/flac-website but doesn't.

**Comment by ktmf01** [comment]
You were just in time. [This document](https://datatracker.ietf.org/doc/draft-ietf-cellar-flac/) is about to be published, and it was still possible to change this. One week later, and it would have been an erratum instead of a change.

**Comment by ktmf01** [comment]
It is still on the website, but that table will be removed as soon as the document is published, so I won't bother updating it. I'll keep this issue open until that is done however, as a reminder.

**Comment by ktmf01** [comment]
https://xiph.org/flac/id.html has been updated
