### ISSUE TITLE
encoding/reencoding material - blocksize for > 48kHz

### ISSUE THREAD

**Issue by klslz** [xiph/flac#85]
I am in the process of re-encoding my collection. I own quite a number of HiRes albums.

Your "help"  on encoding says:
>Specify the block size in samples. Subset streams must use one of 192/576/1152/2304/4608/256/512/1024/2048/4096 (and 8192/16384 if the sample rate is >48kHz). The reference encoder uses the same block size for the entire stream.

I guess that'll also apply for re-encoding:
I actually planned to use following command (all tracks to c-level 0) to run that re-encoding process:

>flac --no-utf8-convert --totally-silent --no-error-on-compression-fail "Si" --force --compression-level-0

Now. Your (widely used) shortcuts e.g. compression-level-0:  

>-0, --compression-level-0, --fast  Synonymous with -l 0 -b 1152 -r 3

wouldn't meet the blocksize criteria as suggested in your "help" and as far I understood it.

1. flac still allows to apply the c-level-X shortcuts with the small blocksize  on >48kHz material - without issuing a warning/error (I tried that).
   Would that be an issue?

2. If I shouldn't be using the c-level-X shortcuts  on >48kHz material, I guess using e.g. "-l 0 -b 8192 -r 3"  would then the right way to do it, wouldn't it!?!? 

New feature idea:
If above blocksize considerations are relevant at all - perhaps I misunderstood something here - for samplerates >48kHz, it would be nice if flac would adjust the blocksize automatically at a given shortcut for SRs >48kHz.

**Comment by lvqcl** [comment]
> Now. Your (widely used) shortcuts e.g. compression-level-0:
> 
> > -0, --compression-level-0, --fast  Synonymous with -l 0 -b 1152 -r 3
> 
> wouldn't meet the blocksize criteria as suggested in your "help" and as far I understood it.

As I see it: "if the sample rate is >48kHz then additionally it can be 8192 or 16384".

**Comment by soundchekk** [comment]
1. There's a "must use" in the sentence.
2. I don't understand the logic behind all that. The way blocksize is used seems inconsistent.
    There seems to be a blocksize -> compression-level relation
    There seems to be a blocksize-> samplerate relation
3. I am still not sure if blocksize matters at all

**Comment by ktmf01** [comment]
Fixed in #253
