### ISSUE TITLE
flac_set_utf8_filenames is not exported

### ISSUE THREAD

**Issue by RafalSkorka** [xiph/flac#87]
Hi! 
I wanted to use libflac from vcpkg. I need to handle utf8 filenames under Windows and there are two issues:
1) include/share folder is not included in the resulting package. This is vcpkg issue and I can work around this by manually copying the folder to appropriate location.
2) flac_set_utf8_filenames is not exported so I am not able to call it from the main application. This would required modification of the libflac library.

Could you make the flac_set_utf8_filenames function exported?

**Comment by erikd** [comment]
That function was never intended to be exported. Any functions defined in `include/share` are designed to be internal APIs. The public C API is in `include/FLAC`

**Comment by RafalSkorka** [comment]
I see, is there then any other way to pass utf8 filename to the library under Windows?

**Comment by ktmf01** [comment]
#272 provides a way to pass UTF-8 filenames, but for now, this is not supported and instead a file descriptor or callbacks must be used for such files

**Comment by ktmf01** [comment]
Quoting the [api documentation](https://xiph.org/flac/api/group__flac__stream__encoder.html)
> FLAC__stream_encoder_init_file()
>
> Initialize the encoder instance to encode native FLAC files.
> 
> This flavor of initialization sets up the encoder to encode to a plain FLAC file. **If POSIX fopen() semantics are not sufficient (for example, with Unicode filenames on Windows), you must use FLAC__stream_encoder_init_FILE(), or FLAC__stream_encoder_init_stream() and provide callbacks for the I/O.**
