### ISSUE TITLE
[Website] Wrong navbar links on changelog page

### ISSUE THREAD

**Issue by vlakoff** [xiph/flac#88]
On website's [changelog](https://xiph.org/flac/changelog.html) page, last item of navbar is "more", and points to the website root.

(this is actually originating from FLAC's bundled HTML documentation, where there is such item "more", letting going from the local files to the online full website)

Therefore, this "more" item should be replaced with items "links" and "developers", as on the other pages.

**Comment by vlakoff** [comment]
Bump, that's a low-hanging fruit :)

**Comment by erikd** [comment]
The web site is in git: https://github.com/xiph/flac-website

PR gladly accepted.

**Comment by erikd** [comment]
PR gladly accepted.

**Comment by vlakoff** [comment]
Here it is: https://github.com/xiph/flac-website/pull/2.
