### ISSUE TITLE
The Link for OSX binaries on home page is broken/missing

### ISSUE THREAD

**Issue by SS64** [xiph/flac#91]
The Link for OSX binaries on home page is broken/missing

**Comment by erikd** [comment]
It would really help if you specified which page you are referring to and also which link is broken.

**Comment by SS64** [comment]
https://xiph.org/flac/download.html

The links for 'Windows: FLAC for Windows'
and 'Older versions: Older versions.'
both go to the same place, although it looks like they would be binaries, the files appear to be development source code.
The link for 'Mac OS X: FLAC tools for OS X from Homebrew'. is a 404

**Comment by ktmf01** [comment]
PR to fix this: https://github.com/xiph/flac-website/pull/4
